"use client";

import { useParams } from "next/navigation";
import { useCallback, useEffect, useRef, useState } from "react";
import { AppShell, EmptyState } from "../../components/AppShell";

type PaperData = { paper: Record<string, any>; questions: Array<Record<string, any>>; stats: { questionTypes: Record<string, number>; difficulties: Record<string, number>; knowledge: string[] } };
type PaperReview = { summary: string; strengths: string[]; risks: Array<{ level: string; title: string; evidence: string; recommendation: string }>; recommendedActions: string[]; evidenceSummary: string[]; uncertainty: string[] };

export default function PaperDetail() {
  const { id } = useParams<{ id: string }>(), [data, setData] = useState<PaperData | null>(null), [mode, setMode] = useState("student"), [message, setMessage] = useState(""), [exporting, setExporting] = useState("");
  const [files, setFiles] = useState<Array<Record<string, any>>>([]), [classes, setClasses] = useState<Array<Record<string, any>>>([]), [assignOpen, setAssignOpen] = useState(false), [assignment, setAssignment] = useState({ classId: "", dueAt: "", requirements: "完成整张试卷并订正错题" });
  const [aiReview, setAiReview] = useState<PaperReview | null>(null), [aiReviewBusy, setAiReviewBusy] = useState(false), [aiReviewMeta, setAiReviewMeta] = useState<{ sentFields: string[]; excludedFields: string[] } | null>(null);
  const documentRef = useRef<HTMLElement | null>(null);
  const load = useCallback(async () => { try { const [response, fileResponse, classResponse] = await Promise.all([fetch(`/api/papers/${id}`), fetch(`/api/papers/${id}/files`), fetch("/api/classes")]), payload = await response.json(), filePayload = await fileResponse.json(), classPayload = await classResponse.json(); if (!response.ok) throw new Error(payload.error || "无法读取试卷"); setData(payload); setFiles(fileResponse.ok ? filePayload.files || [] : []); setClasses(classResponse.ok ? classPayload.classes || [] : []); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "无法读取试卷"); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  const print = async () => { if (!confirm(`确认打印或导出${mode === "student" ? "学生版" : mode === "teacher" ? "教师备课版" : "答案解析版"}？`)) return; const response = await fetch("/api/audit", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "print", entityType: "paper", entityId: id, detail: { mode } }) }); if (!response.ok) { setMessage("未能记录导出操作，请稍后重试"); return; } window.print(); };
  const downloadDocx = async () => { if (exporting) return; setExporting("DOCX"); try { const response = await fetch(`/api/papers/${id}/export?mode=${mode}`); if (!response.ok) throw new Error((await response.json()).error || "Word 生成失败"); const blob = await response.blob(), url = URL.createObjectURL(blob), anchor = document.createElement("a"); anchor.href = url; anchor.download = decodeURIComponent(response.headers.get("Content-Disposition")?.match(/filename\*=UTF-8''(.+)$/)?.[1] || `试卷-${mode}.docx`); anchor.click(); URL.revokeObjectURL(url); setMessage("可编辑 Word 已生成，请使用 WPS 或 Microsoft Word 打开检查"); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Word 生成失败"); } finally { setExporting(""); } };
  const downloadPdf = async () => { if (exporting || !documentRef.current || !data) return; setExporting("PDF"); try { const jobResponse = await fetch(`/api/papers/${id}/export-job`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode }) }), job = await jobResponse.json(); if (!jobResponse.ok) throw new Error(job.error || "PDF 任务创建失败"); const label: Record<string, string> = { student: "学生版", teacher: "教师版", answer: "答案版", analysis: "解析版" }, filename = `${String(data.paper.title).replace(/[\\/:*?"<>|]/g, "-")}-${label[mode]}-${new Date().toISOString().slice(0, 10)}.pdf`; let blob: Blob; if (job.status === "completed") { const cached = await fetch(`/api/papers/${id}/export-job?jobId=${encodeURIComponent(job.jobId)}`); if (!cached.ok) throw new Error("已生成的 PDF 无法读取"); blob = await cached.blob(); } else { const { jsPDF } = await import("jspdf"); await import("html2canvas"); const pdf = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait", compress: true }); await pdf.html(documentRef.current, { x: 14, y: 12, width: 182, windowWidth: 900, autoPaging: "text", html2canvas: { scale: 1.7, useCORS: true, backgroundColor: "#ffffff" } }); blob = pdf.output("blob"); const formData = new FormData(); formData.append("jobId", job.jobId); formData.append("file", blob, filename); const complete = await fetch(`/api/papers/${id}/export-job`, { method: "PUT", body: formData }); if (!complete.ok) throw new Error((await complete.json()).error || "PDF 保存失败"); } const url = URL.createObjectURL(blob), anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); setMessage("PDF 已生成并保存到导出记录；建议首次使用时快速检查分页"); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "PDF 生成失败，请稍后重试或使用打印功能"); } finally { setExporting(""); } };
  const copy = async () => { const response = await fetch(`/api/papers/${id}`, { method: "POST" }), payload = await response.json(); if (!response.ok) { setMessage(payload.error || "复制试卷失败"); return; } setMessage(`已复制为“${payload.paper.title}”`); };
  const updateStatus = async (status: string) => { if (status === "archived" && !confirm("确认归档这份试卷？归档后仍可查看、复制和打印。")) return; const response = await fetch(`/api/papers/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }), payload = await response.json(); if (!response.ok) { setMessage(payload.error || "更新试卷状态失败"); return; } setMessage(status === "archived" ? "试卷已归档" : "试卷状态已更新"); load(); };
  const assignPaper = async () => { if (!assignment.classId) { setMessage("请选择需要布置试卷的班级"); return; } const response = await fetch(`/api/papers/${id}/files`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...assignment, title: `${data?.paper.title || "完整试卷"}作业` }) }), payload = await response.json(); if (!response.ok) { setMessage(payload.error || "布置作业失败"); return; } setAssignOpen(false); setMessage(`已布置给 ${payload.studentCount} 名学生，提交时间会用于课程反馈`); load(); };
  const generateAiReview = async () => { setAiReviewBusy(true); setMessage(""); const response = await fetch("/api/ai/paper-review", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ paperId: Number(id) }) }), payload = await response.json(); setAiReviewBusy(false); if (!response.ok) { setMessage(payload.error || "AI 试卷质检失败"); return; } setAiReview(payload.review); setAiReviewMeta({ sentFields: payload.sentFields || [], excludedFields: payload.excludedFields || [] }); setMessage("AI 结构质检已完成，试卷内容未被修改"); };
  if (message && !data) return <AppShell title="试卷详情"><EmptyState title="无法打开试卷" description={message} action={<button className="secondaryButton" onClick={load}>重新读取</button>} /></AppShell>;
  if (!data) return <AppShell title="试卷详情"><EmptyState title="正在读取试卷" description="请稍候…" /></AppShell>;
  const paper = data.paper, showAnswer = ["teacher", "answer", "analysis"].includes(mode), showAnalysis = ["teacher", "analysis"].includes(mode), showNotes = mode === "teacher" || mode === "analysis";
  return <AppShell title={String(paper.title)} subtitle={`${paper.type} · ${data.questions.length}题 · ${paper.total_score || paper.totalScore || 0}分`} actions={<><button className="secondaryButton" onClick={copy}>复制试卷</button><button disabled={Boolean(exporting)} onClick={downloadDocx}>{exporting === "DOCX" ? "正在生成 Word…" : "导出 Word"}</button><button disabled={Boolean(exporting)} onClick={downloadPdf}>{exporting === "PDF" ? "正在生成 PDF…" : "导出 PDF"}</button><button className="primaryButton" onClick={print}>打印</button></>}>
    {message && <div className="saveToast" role="status">{message}</div>}
    <div className="viewSwitch"><button className={mode === "student" ? "active" : ""} onClick={() => setMode("student")}>学生版</button><button className={mode === "teacher" ? "active" : ""} onClick={() => setMode("teacher")}>教师版</button><button className={mode === "answer" ? "active" : ""} onClick={() => setMode("answer")}>答案版</button><button className={mode === "analysis" ? "active" : ""} onClick={() => setMode("analysis")}>解析版</button></div>
    <div className="toolbar paperStatusToolbar"><span>当前状态：{{ draft: "草稿", completed: "已完成", used: "已使用", archived: "已归档" }[String(paper.status)] || String(paper.status)}</span><button onClick={() => updateStatus("completed")}>标记已完成</button><button onClick={() => updateStatus("used")}>标记已使用</button><button onClick={() => updateStatus("archived")}>归档</button></div>
    <section className="panel aiReviewPanel"><div className="panelTitle"><div><p>DeepSeek · 组卷后辅助</p><h2>试卷结构质检</h2></div><button className="aiButton" disabled={aiReviewBusy || !data.questions.length} onClick={generateAiReview}>{aiReviewBusy ? "正在质检…" : aiReview ? "重新质检" : "运行 AI 结构质检"}</button></div><p className="privacyNote">仅分析题干、题型、难度、分值、知识点和缺失状态；答案、解析正文、学生信息和原卷附件不会发送，AI 不会改题或改变试卷状态。</p>{aiReview && <><p>{aiReview.summary}</p><div className="prepContextGrid"><article><b>可保留之处</b><span>{aiReview.strengths.join("\n") || "未识别到有证据的优势"}</span></article>{aiReview.risks.slice(0, 3).map((risk, index) => <article key={`${risk.title}-${index}`}><b>{risk.level}风险 · {risk.title}</b><span>{risk.evidence}\n建议：{risk.recommendation}</span></article>)}</div>{aiReview.recommendedActions.length > 0 && <div className="aiUncertainty"><b>建议按顺序人工处理</b>{aiReview.recommendedActions.map((item) => <span key={item}>{item}</span>)}</div>}{aiReview.uncertainty.length > 0 && <div className="aiUncertainty"><b>质检边界</b>{aiReview.uncertainty.map((item) => <span key={item}>{item}</span>)}</div>}{aiReviewMeta && <details><summary>查看本次发送与排除字段</summary><p>发送：{aiReviewMeta.sentFields.join("、")}</p><p>排除：{aiReviewMeta.excludedFields.join("、")}</p></details>}</>}</section>
    {files.length > 0 && <section className="panel originalPaperFiles"><div className="panelTitle"><div><p>原始文件</p><h2>整张试卷版本</h2></div><button className="primaryButton" onClick={() => setAssignOpen(true)}>布置为作业</button></div><div className="paperFileList">{files.map((file) => <article key={file.id}><div><b>{{ student: "学生版", teacher: "教师版", answer: "答案版", analysis: "解析版" }[file.versionType as string] || file.versionType}</b><span>{file.originalName} · {(Number(file.size) / 1024 / 1024).toFixed(1)}MB</span><small>{file.parseMessage || "原卷已保存"}</small></div><a className="secondaryButton" href={`/api/papers/${id}/files/${file.id}?inline=1`} target="_blank" rel="noreferrer">打开并打印原卷</a><a href={`/api/papers/${id}/files/${file.id}`}>下载原文件</a></article>)}</div></section>}
    <section className="paperInsights"><div><b>知识点覆盖</b><span>{data.stats.knowledge.length ? data.stats.knowledge.join(" · ") : "暂未标注"}</span></div><div><b>题型分布</b><span>{Object.entries(data.stats.questionTypes).map(([type, count]) => `${type} ${count}题`).join(" · ") || "暂未分类"}</span></div><div><b>难度分布</b><span>{Object.entries(data.stats.difficulties).map(([level, count]) => `${level}级 ${count}题`).join(" · ") || "暂未标注"}</span></div></section>
    <section className="paperDocument" ref={documentRef}><header><h1>{paper.title}</h1>{paper.instructions && <p className="paperInstructions">{paper.instructions}</p>}<p>姓名：________　班级：________　日期：________ {paper.duration_minutes || paper.durationMinutes ? `　限时：${paper.duration_minutes || paper.durationMinutes} 分钟` : ""}</p></header>{data.questions.length === 0 ? <p className="originalPaperHint">本记录以整张原卷为主，请使用上方“打开并打印原卷”。后台拆题完成后，题目也会显示在这里。</p> : data.questions.map((question, index) => <article key={String(question.id)}>{question.group_title && <h2 className="paperGroupTitle">{question.group_title}</h2>}<h3>{index + 1}．{question.stem}<span>（{question.paperScore || question.paper_score || question.score || 0}分）</span></h3>{question.material && <blockquote>{question.material}</blockquote>}{question.options && <pre>{question.options}</pre>}{mode === "student" && <div className="answerSpace">{Array.from({ length: Math.max(1, Number(question.answer_space || 2)) }, (_, line) => <p key={line}>作答：________________________________________________________________</p>)}</div>}{showNotes && <div className="teacherQuestionMeta"><b>知识点：</b>{question.knowledge_points || question.knowledgePoints || "待标注"}　<b>难度：</b>{question.difficulty || "—"}级</div>}{showAnswer && <div className="answerBlock"><b>答案：</b>{question.answer || "待补充"}{showAnalysis && <><br /><b>解析：</b>{question.analysis || "待补充"}{question.standard_expression && <><br /><b>规范表述：</b>{question.standard_expression}</>}</>}</div>}</article>)}</section>
    {assignOpen && <div className="modalBackdrop"><div className="lessonModal" role="dialog" aria-modal="true"><div className="modalTitle"><div><p>关联课程与作业</p><h2>布置整张试卷</h2></div><button aria-label="关闭" onClick={() => setAssignOpen(false)}>×</button></div><div className="formGrid"><label>班级<select value={assignment.classId} onChange={(event) => setAssignment({ ...assignment, classId: event.target.value })}><option value="">请选择班级</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>预计提交时间<input type="datetime-local" value={assignment.dueAt} onChange={(event) => setAssignment({ ...assignment, dueAt: event.target.value })} /></label><label className="wide">作业要求<textarea value={assignment.requirements} onChange={(event) => setAssignment({ ...assignment, requirements: event.target.value })} /></label></div><div className="modalActions"><button onClick={() => setAssignOpen(false)}>取消</button><button className="primaryButton" onClick={assignPaper}>确认布置</button></div></div></div>}
  </AppShell>;
}
