const api = require("../../utils/api");
const tagLabels = ["观点不准确", "材料对应不足", "政治术语不规范", "答题层次不清", "采分点缺失"];
const outcomes = [{ value: "completed", label: "已完成" }, { value: "revision", label: "需订正" }, { value: "excellent", label: "优秀" }, { value: "incomplete", label: "未完成" }];

Page({
  data: { assignments: [], submissions: [], assignmentId: 0, submissionId: 0, current: null, tags: tagLabels.map((label) => ({ label, selected: false })), outcomes, outcomeIndex: 0, outcome: "completed", score: "", note: "", requirements: "", reviewAssets: [], loading: true, error: "", busy: false, recording: false },
  onLoad(options) { this.pending = options || {}; this.recorder = wx.getRecorderManager(); this.recorder.onStop((result) => this.uploadVoice(result.tempFilePath)); this.load(); },
  async load() { try { const data = await api.request("/api/mini/assignments"); this.setData({ assignments: data.assignments || [], loading: false }); if (this.pending.assignmentId) await this.selectAssignment(Number(this.pending.assignmentId), Number(this.pending.submissionId || 0)); } catch (error) { this.setData({ loading: false, error: error.error || "加载失败" }); } },
  async selectAssignment(assignmentId, preferred = 0) { const data = await api.request(`/api/mini/submissions?assignmentId=${assignmentId}`), submissions = data.submissions || [], current = submissions.find((item) => Number(item.id) === preferred) || null; this.setData({ assignmentId, submissions, submissionId: current ? Number(current.id) : 0, current }); if (current) this.hydrateCurrent(current); },
  async chooseAssignment(event) { await this.selectAssignment(Number(event.currentTarget.dataset.id)); },
  chooseSubmission(event) { const submissionId = Number(event.currentTarget.dataset.id), current = this.data.submissions.find((item) => Number(item.id) === submissionId); this.setData({ submissionId, current, score: current && current.score != null ? String(current.score) : "", note: "", requirements: "", reviewAssets: [] }); if (current) this.hydrateCurrent(current); },
  chooseOutcome(event) { const outcomeIndex = Number(event.detail.value); this.setData({ outcomeIndex, outcome: this.data.outcomes[outcomeIndex].value }); },
  toggleTag(event) { const index = Number(event.currentTarget.dataset.index), tags = this.data.tags.map((item, position) => position === index ? { ...item, selected: !item.selected } : item); this.setData({ tags }); },
  field(event) { this.setData({ [event.currentTarget.dataset.key]: event.detail.value }); },
  async hydrateCurrent(current) { const attachments = await Promise.all((current.attachments || []).map(async (item) => ({ ...item, localPath: await api.download(item.url) }))); if (this.data.submissionId === Number(current.id)) this.setData({ current: { ...current, attachments } }); },
  preview(event) { const urls = (this.data.current.attachments || []).map((item) => item.localPath).filter(Boolean); wx.previewImage({ current: urls[Number(event.currentTarget.dataset.index) || 0], urls }); },
  annotate(event) { const item = this.data.current.attachments[Number(event.currentTarget.dataset.index) || 0]; wx.navigateTo({ url: `/pages/annotate/index?url=${encodeURIComponent(item.url)}`, events: { done: (asset) => this.setData({ reviewAssets: [...this.data.reviewAssets, asset] }) } }); },
  toggleRecording() { if (this.data.recording) { this.recorder.stop(); this.setData({ recording: false }); } else { this.recorder.start({ duration: 60000, format: "mp3" }); this.setData({ recording: true }); } },
  async uploadVoice(path) { try { const asset = await api.upload(path, "review-voice", api.operationId("voice")); this.setData({ reviewAssets: [...this.data.reviewAssets, asset] }); wx.showToast({ title: "语音评语已添加" }); } catch (error) { wx.showModal({ title: "语音保存失败", content: error.error || "请重试", showCancel: false }); } },
  async save(event) { if (!this.data.submissionId || this.data.busy) return; const confirm = Boolean(event.currentTarget.dataset.confirm); this.setData({ busy: true }); try { await api.request("/api/mini/submissions", { method: "POST", data: { action: confirm ? "confirm-review" : "save-review", submissionId: this.data.submissionId, outcome: this.data.outcome, score: this.data.score === "" ? null : Number(this.data.score), reviewTags: this.data.tags.filter((item) => item.selected).map((item) => item.label), teacherNote: this.data.note, revisionRequirements: this.data.requirements, reviewAssetIds: this.data.reviewAssets.map((item) => item.id), operationId: api.operationId("review") } }); wx.showToast({ title: confirm ? "已确认回传" : "草稿已保存" }); if (confirm) { const index = this.data.submissions.findIndex((item) => Number(item.id) === this.data.submissionId), next = this.data.submissions[index + 1]; if (next) this.chooseSubmission({ currentTarget: { dataset: { id: next.id } } }); else await this.selectAssignment(this.data.assignmentId); } } catch (error) { wx.showModal({ title: "保存失败", content: error.error || "请重试", showCancel: false }); } finally { this.setData({ busy: false }); } },
});
