"use client";import {useEffect,useState} from "react";import {AppShell,EmptyState} from "../components/AppShell";
type Data=Record<string,any>;const metric=(label:string,value:any,definition:string)=><article className="analyticsMetric"><span>{label}</span><b>{value==null?"—":value}</b><details><summary>口径说明</summary><p>{definition}</p></details></article>;
export default function AnalyticsPage(){const [range,setRange]=useState("week"),[d,setD]=useState<Data|null>(null);const load=()=>fetch(`/api/analytics?range=${range}`).then(r=>r.json()).then(setD);useEffect(()=>{load()},[range]);if(!d)return <AppShell title="数据中心"><EmptyState title="正在计算真实数据" description="请稍候…"/></AppShell>;const insufficient=d.teaching.lessons===0&&d.questionBank.total===0&&d.growth.reflections===0,max=Math.max(1,...d.questionBank.difficulty.map((x:any)=>Number(x.count)));return <AppShell title="数据中心" subtitle="所有指标均来自已录入记录，不生成推测性结论"><div className="rangeTabs"><button className={range==="week"?"active":""} onClick={()=>setRange("week")}>周</button><button className={range==="month"?"active":""} onClick={()=>setRange("month")}>月</button><button className={range==="term"?"active":""} onClick={()=>setRange("term")}>学期</button><span>统计起始：{d.start}</span></div>{insufficient&&<div className="noticeStrip"><b>数据不足，继续记录后可查看趋势</b><span>完成课时、学生表现、题目和反思记录后，图表会自动更新。</span></div>}
 <section className="analyticsSection"><div className="panelTitle"><div><p>教学</p><h2>教学记录质量</h2></div></div><div className="analyticsGrid">{metric("课时数",d.teaching.lessons,"所选时间范围内创建的全部课时。")}{metric("备课完成率",d.teaching.prepRate==null?null:`${d.teaching.prepRate}%`,"同时填写教学目标和重点的课时数 ÷ 全部课时数。")}{metric("课时记录完成率",d.teaching.completedRate==null?null:`${d.teaching.completedRate}%`,"状态为“已完成”的课时数 ÷ 全部课时数。")}{metric("反馈及时率",d.teaching.feedbackRate==null?null:`${d.teaching.feedbackRate}%`,"关联课时且在课后 48 小时内确认的反馈数 ÷ 所选范围内反馈总数。")}</div></section>
 <section className="analyticsColumns"><div className="analyticsSection"><div className="panelTitle"><div><p>班级与学生</p><h2>学习记录</h2></div></div><div className="analyticsGrid two">{metric("出勤率",d.classroom.attendanceRate==null?null:`${d.classroom.attendanceRate}%`,"标记为出勤的记录数 ÷ 全部出勤记录。")}{metric("作业完成率",d.classroom.homeworkRate==null?null:`${d.classroom.homeworkRate}%`,"状态为已完成的提交数 ÷ 全部作业提交记录。")}{metric("测验平均分",d.classroom.assessmentAverage,"所选范围内已有成绩的测验结果算术平均值。")}{metric("测验记录",d.classroom.assessmentCount,"所选范围内已录入成绩的测验结果数量。")}</div>{d.studentTrend.length<2?<p className="dataEmpty">数据不足，至少记录两个日期的学生表现后可查看趋势。</p>:<div className="trendBars">{d.studentTrend.map((x:any)=><div key={x.date}><span>{x.date.slice(5)}</span><i style={{height:`${Number(x.participation||0)*18}px`}}></i><em style={{height:`${Number(x.understanding||0)*18}px`}}></em></div>)}</div>}</div>
 <div className="analyticsSection"><div className="panelTitle"><div><p>题库</p><h2>覆盖与难度</h2></div></div><div className="analyticsGrid two">{metric("正式题目",d.questionBank.total,"状态为“正式题库”的题目数量。")}{metric("知识点覆盖率",d.questionBank.coverageRate==null?null:`${d.questionBank.coverageRate}%`,"已标注知识点的正式题目数 ÷ 正式题目总数。")}</div>{d.questionBank.difficulty.length===0?<p className="dataEmpty">数据不足，添加正式题目后可查看难度分布。</p>:<div className="difficultyChart">{[1,2,3,4,5].map(n=>{const x=d.questionBank.difficulty.find((v:any)=>Number(v.difficulty)===n),count=Number(x?.count||0);return <div key={n}><b style={{height:`${count/max*110}px`}}></b><span>{n}级</span><em>{count}</em></div>})}</div>}{d.questionBank.frequent?.length>0&&<div className="analyticsList"><b>常用题目</b>{d.questionBank.frequent.map((x:any)=><p key={x.id}><span>{x.stem}</span><em>使用 {x.useCount} 次</em></p>)}</div>}</div></section>
 <section className="analyticsSection"><div className="panelTitle"><div><p>趋势补充</p><h2>作业与知识点记录</h2></div></div><div className="analyticsColumns"><div>{d.homeworkTrend?.length<2?<p className="dataEmpty">数据不足，至少记录两个日期的作业提交后可查看作业趋势。</p>:<div className="analyticsList"><b>按课时日期的作业完成</b>{d.homeworkTrend.map((x:any)=><p key={x.date}><span>{x.date}</span><em>{x.completed}/{x.total} 已完成</em></p>)}</div>}</div><div>{d.classroom.knowledgeMastery?.length===0?<p className="dataEmpty">数据不足，录入测验知识点掌握记录后可查看。</p>:<div className="analyticsList"><b>测验中的知识点掌握记录</b>{d.classroom.knowledgeMastery.map((x:any)=><p key={x.mastery}><span>{x.mastery}</span><em>{x.count} 条</em></p>)}</div>}</div></div></section>
 <section className="analyticsSection"><div className="panelTitle"><div><p>自我成长</p><h2>反思与改进</h2></div></div><div className="analyticsGrid">{metric("反思数量",d.growth.reflections,"所选范围内的私密教学反思数量。")}{metric("改进动作完成率",d.growth.actionRate==null?null:`${d.growth.actionRate}%`,"标记为已完成的改进动作 ÷ 全部反思。")}{metric("沉淀教学策略",d.growth.strategies,"已标记为可复用教学策略的反思数量。")}{metric("重复问题",d.growth.repeatedProblems.length,"完全相同且重复出现两次以上的困难记录。")}</div>{d.growth.repeatedProblems.length>0&&<div className="analyticsList"><b>重复出现的问题</b>{d.growth.repeatedProblems.map((x:any)=><p key={x.difficulties}><span>{x.difficulties}</span><em>{x.count} 次</em></p>)}</div>}</section>
 </AppShell>}
