"use client";
import { useCallback, useEffect, useState } from "react";
type Approval = { id: string; title: string; summary: string; actionType: string; entityType: string; confidence: number | null; evidence: unknown[]; createdAt: string; createdByName: string | null };
type Job = { id: string; type: string; state: string; stage: string; progress: number; processed: number; total: number; updatedAt: string };
export function ApprovalCenter() {
  const [items, setItems] = useState<Approval[]>([]), [jobs, setJobs] = useState<Job[]>([]), [jobBusy, setJobBusy] = useState(""), [canDecide, setCanDecide] = useState(false), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const load = useCallback(async () => { try { const response = await fetch("/api/v2/approvals?state=pending", { cache: "no-store" }), data = await response.json() as { approvals?: Approval[]; activeJobs?: Job[]; canDecide?: boolean; error?: string }; if (!response.ok) throw new Error(data.error || "读取失败"); setItems(data.approvals || []); setJobs(data.activeJobs || []); setCanDecide(Boolean(data.canDecide)); } catch (reason) { setError(reason instanceof Error ? reason.message : "读取失败"); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); const timer = setInterval(load, 15000); return () => clearInterval(timer); }, [load]);
  async function decide(id: string, decision: "approved" | "rejected") { setError(""); const response = await fetch(`/api/v2/approvals/${id}`, { method: "POST", headers: { "Content-Type": "application/json", "X-Operation-Id": crypto.randomUUID() }, body: JSON.stringify({ decision }) }), result = await response.json() as { error?: string }; if (!response.ok) return setError(result.error || "操作失败"); setItems((current) => current.filter((item) => item.id !== id)); }
  async function jobAction(job: Job, action: "retry" | "cancel") { setJobBusy(job.id); setError(""); const response = await fetch(`/api/v2/jobs/${job.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action }) }), result = await response.json() as { error?: string }; setJobBusy(""); if (!response.ok) return setError(result.error || "任务操作失败"); await load(); }
  return <><section className="v2-hero"><div><p className="v2-eyebrow">HUMAN-IN-THE-LOOP CONTROL</p><h2>所有影响正式业务的动作，在这里最后确认。</h2><p>AI 可以准备建议与草稿，但调整课表、修改题库、发布作业和发送反馈都不会绕过此处。每次决定都会写入审计记录。</p></div><div className="v2-hero-actions"><span className="v2-primary">{items.length} 项待确认</span></div></section>
    <div className="v2-grid" style={{ marginTop: 17 }}><section className="v2-card"><header className="v2-card-head"><div><h2>待确认建议</h2><p>{canDecide ? "建议先看依据和置信度，再决定是否采用" : "助教可准备建议；主教师会在这里完成最终确认"}</p></div></header>{error && <div className="v2-alert v2-error">{error}</div>}{loading ? <div className="v2-empty">正在载入…</div> : items.length ? items.map((item) => <article className="v2-approval" key={item.id}><div><h3>{item.title}</h3><p>{item.summary}</p><div className="v2-reasons"><span>{item.actionType}</span><span>{item.entityType}</span>{item.createdByName && <span>创建人 {item.createdByName}</span>}{item.confidence != null && <span>置信度 {Math.round(item.confidence * 100)}%</span>}</div></div>{canDecide ? <div className="v2-approval-actions"><button onClick={() => decide(item.id, "approved")}>确认采用</button><button onClick={() => decide(item.id, "rejected")}>拒绝</button></div> : <span className="v2-status pending">等待主教师</span>}</article>) : <div className="v2-empty"><b>没有等待确认的动作</b>AI 生成的正式业务建议会自动汇入这里。</div>}</section>
      <aside className="v2-card"><header className="v2-card-head"><div><h2>后台任务</h2><p>每 15 秒更新，可关闭页面</p></div></header><div className="v2-action-list">{jobs.length ? jobs.map((job) => <article key={job.id}><i>{job.progress}</i><span><b>{job.type}</b><small>{job.stage} · {job.processed}/{job.total || "—"}</small><small>{["failed", "partial", "cancelled"].includes(job.state) && ["schedule-import", "question-import"].includes(job.type) ? <button className="v2-row-inline-button" disabled={jobBusy === job.id} onClick={() => void jobAction(job, "retry")}>从原文件重试</button> : ["queued", "running"].includes(job.state) ? <button className="v2-row-inline-button" disabled={jobBusy === job.id} onClick={() => void jobAction(job, "cancel")}>取消任务</button> : null}</small></span><em className={`v2-status ${job.state}`}>{job.state}</em></article>) : <div className="v2-empty"><b>没有活跃任务</b>批量识别和分析会显示在这里。</div>}</div></aside></div></>;
}
