"use client";

import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { AppShell, EmptyState } from "../../components/AppShell";

type Data = { student: Record<string, any>; lessonRecords: any[]; submissions: any[]; feedback: any[]; results: any[] };

export default function StudentDetail() {
  const { id } = useParams<{ id: string }>(), [data, setData] = useState<Data | null>(null), [contact, setContact] = useState(""), [message, setMessage] = useState(""), [editing, setEditing] = useState(false), [form, setForm] = useState<Record<string, any>>({});
  const load = useCallback(async () => { try { const response = await fetch(`/api/students/${id}`), payload = await response.json(); if (!response.ok) throw new Error(payload.error || "无法读取学生档案"); setData(payload); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "无法读取学生档案"); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  const reveal = async () => { if (!confirm("监护人联系方式属于敏感信息。确认因教学沟通需要查看，并记录本次操作？")) return; const response = await fetch(`/api/students/${id}/private`), result = await response.json(); setContact(response.ok ? result.guardianContact : result.error || "当前角色无权查看"); };
  const edit = () => { if (!data) return; setForm({ ...data.student, riskConfirmed: Boolean(data.student.riskConfirmed) }); setEditing(true); };
  const save = async () => { const response = await fetch(`/api/students/${id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }), payload = await response.json(); if (!response.ok) { setMessage(payload.error || "保存学生档案失败"); return; } setEditing(false); setMessage("学生档案已更新"); load(); };
  const archive = async () => { if (!data || !confirm("确认归档该学生？归档不会删除课程、作业、反馈和测验历史。")) return; const response = await fetch(`/api/students/${id}`, { method: "DELETE" }), payload = await response.json(); setMessage(response.ok ? "学生已归档" : payload.error || "归档失败"); if (response.ok) load(); };
  if (message && !data) return <AppShell title="学生档案"><EmptyState title="无法打开学生档案" description={message} action={<button className="secondaryButton" onClick={load}>重新读取</button>} /></AppShell>;
  if (!data?.student) return <AppShell title="学生档案"><EmptyState title="正在读取档案" description="请稍候…" /></AppShell>;
  const student = data.student, total = data.lessonRecords.length + data.submissions.length + data.feedback.length + data.results.length, items = [...data.lessonRecords.map((item) => ({ date: item.date, type: "课时表现", title: item.topic || item.courseName, detail: `参与 ${item.participation || "—"}/5 · 理解 ${item.understanding || "—"}/5 · 完成 ${item.completion || "—"}/5${item.teacherNote ? ` · ${item.teacherNote}` : ""}` })), ...data.submissions.map((item) => ({ date: item.lessonDate, type: "作业", title: item.title, detail: item.status === "completed" ? "已完成" : "待完成" })), ...data.feedback.map((item) => ({ date: item.lessonDate || item.created_at, type: "反馈", title: item.topic || "课程反馈", detail: item.status === "confirmed" ? "已确认" : "草稿" })), ...data.results.map((item) => ({ date: item.date, type: "测验", title: item.title, detail: item.score == null ? "待录入成绩" : `${item.score} 分` }))].sort((a, b) => String(b.date || "").localeCompare(String(a.date || "")));
  return <AppShell title={String(student.name)} subtitle={`${String(student.grade || "")} · 学习成长档案`} actions={<><button className="secondaryButton" onClick={edit}>编辑档案</button><button className="dangerButton" onClick={archive}>归档学生</button></>}>
    {message && <div className="saveToast" role="status">{message}</div>}
    <div className="profileGrid"><section className="panel profileCard"><div className="profileHead"><span>{String(student.name).slice(0, 1)}</span><div><h2>{String(student.name)}</h2><p>{String(student.nickname || "未设置昵称")}</p></div>{Boolean(student.riskConfirmed) && <em className="riskBadge">教师确认关注 · {String(student.riskTags || "")}</em>}</div><dl><div><dt>学校 / 教材</dt><dd>{String(student.school || "待记录")} · {String(student.textbookVersion || "待记录")}</dd></div><div><dt>选科 / 考试目标</dt><dd>{String(student.subjectChoice || "待记录")} · {String(student.examGoal || "待记录")}</dd></div><div><dt>基础水平</dt><dd>{String(student.foundationLevel || "待记录")}</dd></div><div><dt>优势</dt><dd>{String(student.strengths || "待记录")}</dd></div><div><dt>薄弱知识点</dt><dd>{String(student.weakKnowledge || "待记录")}</dd></div><div><dt>学习习惯</dt><dd>{String(student.learningHabits || "待记录")}</dd></div><div><dt>阶段目标</dt><dd>{String(student.stageGoal || "待制定")}</dd></div></dl><div className="privacyNote">监护人联系方式属于敏感信息，普通档案视图不展示。{contact ? <b> {contact}</b> : <button onClick={reveal}>教师确认后查看</button>}</div></section><section className="panel span2"><div className="panelTitle"><div><p>真实记录</p><h2>成长时间线</h2></div></div>{total === 0 ? <EmptyState title="还没有成长记录" description="完成课时表现、作业、测验或反馈后，会按时间显示在这里。" /> : <><div className="summaryCounts"><span>课时表现 <b>{data.lessonRecords.length}</b></span><span>作业记录 <b>{data.submissions.length}</b></span><span>课程反馈 <b>{data.feedback.length}</b></span><span>测验结果 <b>{data.results.length}</b></span></div><div className="growthTimeline">{items.map((item, index) => <article key={`${item.type}-${index}`}><time>{String(item.date || "日期待补")}</time><span>{item.type}</span><div><b>{String(item.title || "")}</b><p>{item.detail}</p></div></article>)}</div></>}</section></div>
    {editing && <div className="modalBackdrop"><div className="lessonModal" role="dialog" aria-modal="true" aria-labelledby="student-edit-title"><div className="modalTitle"><div><p>更新成长档案</p><h2 id="student-edit-title">编辑学生信息</h2></div><button aria-label="关闭" onClick={() => setEditing(false)}>×</button></div><div className="formGrid"><label>姓名<input value={form.name || ""} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>昵称<input value={form.nickname || ""} onChange={(event) => setForm({ ...form, nickname: event.target.value })} /></label><label>年级<select value={form.grade || "高一"} onChange={(event) => setForm({ ...form, grade: event.target.value })}>{["七年级", "八年级", "九年级", "高一", "高二", "高三"].map((item) => <option key={item}>{item}</option>)}</select></label><label>学校<input value={form.school || ""} onChange={(event) => setForm({ ...form, school: event.target.value })} /></label><label>教材版本<input value={form.textbookVersion || ""} onChange={(event) => setForm({ ...form, textbookVersion: event.target.value })} /></label><label>选科 / 考试方向<input value={form.subjectChoice || ""} onChange={(event) => setForm({ ...form, subjectChoice: event.target.value })} /></label><label>考试目标<input value={form.examGoal || ""} onChange={(event) => setForm({ ...form, examGoal: event.target.value })} /></label><label>基础水平<input value={form.foundationLevel || ""} onChange={(event) => setForm({ ...form, foundationLevel: event.target.value })} /></label><label>优势<input value={form.strengths || ""} onChange={(event) => setForm({ ...form, strengths: event.target.value })} /></label><label>薄弱知识点<input value={form.weakKnowledge || ""} onChange={(event) => setForm({ ...form, weakKnowledge: event.target.value })} /></label><label>学习习惯<input value={form.learningHabits || ""} onChange={(event) => setForm({ ...form, learningHabits: event.target.value })} /></label><label>风险标签<input value={form.riskTags || ""} onChange={(event) => setForm({ ...form, riskTags: event.target.value })} /></label><label className="checkLabel"><input type="checkbox" checked={Boolean(form.riskConfirmed)} onChange={(event) => setForm({ ...form, riskConfirmed: event.target.checked })} />教师确认关注</label><label className="wide">阶段目标<textarea value={form.stageGoal || ""} onChange={(event) => setForm({ ...form, stageGoal: event.target.value })} /></label><label className="wide">备注<textarea value={form.notes || ""} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></label></div><div className="privacyNote">如果需要更新监护人联系方式，请使用下方“教师确认后查看”入口核对后再另行录入；普通编辑不会覆盖原有联系方式。</div><div className="modalActions"><button onClick={() => setEditing(false)}>取消</button><button className="primaryButton" onClick={save}>保存档案</button></div></div></div>}
  </AppShell>;
}
