"use client";

import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { AppShell, EmptyState } from "../../components/AppShell";

type Data = { student: Record<string, any>; attention: Array<{ level: string; title: string; evidence: string }>; lessonRecords: any[]; submissions: any[]; feedback: any[]; results: any[]; wrongQuestions: any[] };

export default function StudentDetail() {
  const { id } = useParams<{ id: string }>(), [data, setData] = useState<Data | null>(null), [mastery, setMastery] = useState<Record<string, any> | null>(null), [contact, setContact] = useState(""), [message, setMessage] = useState(""), [editing, setEditing] = useState(false), [form, setForm] = useState<Record<string, any>>({}), [wrongOpen, setWrongOpen] = useState(false), [questionChoices, setQuestionChoices] = useState<Array<Record<string, any>>>([]), [wrongForm, setWrongForm] = useState({ questionId: "", incorrectAnswer: "", reason: "" }), [masteryOpen, setMasteryOpen] = useState(false), [masteryScore, setMasteryScore] = useState(""), [masteryReason, setMasteryReason] = useState("");
  const load = useCallback(async () => { try { const [response, masteryResponse] = await Promise.all([fetch(`/api/students/${id}`), fetch(`/api/students/${id}/mastery`)]), payload = await response.json(), masteryPayload = await masteryResponse.json(); if (!response.ok) throw new Error(payload.error || "无法读取学生档案"); setData(payload); setMastery(masteryResponse.ok ? masteryPayload.mastery : null); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "无法读取学生档案"); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  const reveal = async () => { if (!confirm("监护人联系方式属于敏感信息。确认因教学沟通需要查看，并记录本次操作？")) return; const response = await fetch(`/api/students/${id}/private`), result = await response.json(); setContact(response.ok ? result.guardianContact : result.error || "当前角色无权查看"); };
  const edit = () => { if (!data) return; setForm({ ...data.student, riskConfirmed: Boolean(data.student.riskConfirmed) }); setEditing(true); };
  const save = async () => { const response = await fetch(`/api/students/${id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }), payload = await response.json(); if (!response.ok) { setMessage(payload.error || "保存学生档案失败"); return; } setEditing(false); setMessage("学生档案已更新"); load(); };
  const archive = async () => { if (!data || !confirm("确认归档该学生？归档不会删除课程、作业、反馈和测验历史。")) return; const response = await fetch(`/api/students/${id}`, { method: "DELETE" }), payload = await response.json(); setMessage(response.ok ? "学生已归档" : payload.error || "归档失败"); if (response.ok) load(); };
  const openWrongQuestion = async () => { try { const response = await fetch("/api/questions?status=active"), payload = await response.json(); if (!response.ok) throw new Error(payload.error || "无法读取正式题库"); setQuestionChoices(payload.questions || []); setWrongForm({ questionId: "", incorrectAnswer: "", reason: "" }); setWrongOpen(true); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "无法读取正式题库"); } };
  const saveWrongQuestion = async () => { if (!wrongForm.questionId) { setMessage("请先选择一道正式题目"); return; } const response = await fetch(`/api/students/${id}/wrong-questions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(wrongForm) }), payload = await response.json(); if (!response.ok) { setMessage(payload.error || "错题登记失败"); return; } setWrongOpen(false); setMessage(payload.updated ? "错题记录已更新并重新纳入巩固" : "错题已登记到学生档案"); load(); };
  const setWrongStatus = async (wrongQuestionId: number, status: "active" | "mastered") => { const response = await fetch(`/api/students/${id}/wrong-questions`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ wrongQuestionId, status }) }), payload = await response.json(); setMessage(response.ok ? (status === "mastered" ? "已标记为掌握" : "已重新纳入错题巩固") : payload.error || "更新错题状态失败"); if (response.ok) load(); };
  const removeWrongQuestion = async (wrongQuestionId: number) => { if (!confirm("确认删除这条错题记录？删除后无法恢复。")) return; const response = await fetch(`/api/students/${id}/wrong-questions`, { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ wrongQuestionId }) }), payload = await response.json(); setMessage(response.ok ? "错题记录已删除" : payload.error || "删除错题记录失败"); if (response.ok) load(); };
  const openMastery = () => { setMasteryScore(String(mastery?.effectiveScore ?? mastery?.score ?? "")); setMasteryReason(""); setMasteryOpen(true); };
  const saveMastery = async () => { const response = await fetch(`/api/students/${id}/mastery`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ score: Number(masteryScore), reason: masteryReason }) }), payload = await response.json(); if (!response.ok) { setMessage(payload.error || "保存掌握度修正失败"); return; } setMastery(payload.mastery); setMasteryOpen(false); setMessage("掌握度人工修正已保存，并记录了修正依据"); };
  if (message && !data) return <AppShell title="学生档案"><EmptyState title="无法打开学生档案" description={message} action={<button className="secondaryButton" onClick={load}>重新读取</button>} /></AppShell>;
  if (!data?.student) return <AppShell title="学生档案"><EmptyState title="正在读取档案" description="请稍候…" /></AppShell>;
  const student = data.student, wrongQuestions = data.wrongQuestions || [], total = data.lessonRecords.length + data.submissions.length + data.feedback.length + data.results.length + wrongQuestions.length, items = [...data.lessonRecords.map((item) => ({ date: item.date, type: "课时表现", title: item.topic || item.courseName, detail: `参与 ${item.participation || "—"}/5 · 理解 ${item.understanding || "—"}/5 · 完成 ${item.completion || "—"}/5${item.teacherNote ? ` · ${item.teacherNote}` : ""}` })), ...data.submissions.map((item) => ({ date: item.lessonDate, type: "作业", title: item.title, detail: item.status === "completed" ? "已完成" : "待完成" })), ...data.feedback.map((item) => ({ date: item.lessonDate || item.created_at, type: "反馈", title: item.topic || "课程反馈", detail: item.status === "confirmed" ? "已确认" : "草稿" })), ...data.results.map((item) => ({ date: item.date, type: "测验", title: item.title, detail: item.score == null ? "待录入成绩" : `${item.score} 分` })), ...wrongQuestions.map((item: Record<string, any>) => ({ date: item.occurredAt, type: "错题", title: item.stem || "政治错题", detail: item.status === "mastered" ? "已掌握" : `待巩固${item.knowledgePoints ? ` · ${item.knowledgePoints}` : ""}` }))].sort((a, b) => String(b.date || "").localeCompare(String(a.date || "")));
  return <AppShell title={String(student.name)} subtitle={`${String(student.grade || "")} · 学习成长档案`} actions={<><a className="secondaryButton" href={`/feedback?new=1&type=stage&student=${id}`}>生成阶段总结</a><button className="secondaryButton" onClick={openWrongQuestion}>＋ 登记错题</button><button className="secondaryButton" onClick={edit}>编辑档案</button><button className="dangerButton" onClick={archive}>归档学生</button></>}>
    {message && <div className="saveToast" role="status">{message}</div>}
    <section className="panel studentAttention"><div className="panelTitle"><div><p>当前需要处理</p><h2>学习关注事项</h2></div><span>均显示判断依据</span></div>{data.attention?.length ? <div className="attentionList">{data.attention.map((item, index) => <article className={item.level} key={`${item.title}-${index}`}><b>{item.title}</b><p>{item.evidence}</p></article>)}</div> : <p className="privacyNote">当前没有需要特别处理的事项。系统不会在缺少真实记录时生成风险结论。</p>}</section>
    <section className="panel"><div className="panelTitle"><div><p>可解释计算</p><h2>综合学习掌握度</h2></div><button className="secondaryButton" onClick={openMastery}>教师人工修正</button></div>{mastery?.score == null ? <EmptyState title="暂无足够数据" description={mastery?.explanation || "录入测验、作业、课堂理解度或错题掌握状态后计算。"} /> : <><div className="summaryCounts"><span>当前掌握度 <b>{mastery.effectiveScore}%</b></span><span>系统计算 <b>{mastery.score}%</b></span>{mastery.manualAdjustment && <span>人工修正 <b>{mastery.manualAdjustment.overrideScore}%</b></span>}</div><p className="privacyNote">{mastery.explanation}</p><div className="analyticsList">{mastery.components?.map((item: Record<string, any>) => <p key={item.key}><span>{item.label} · {item.normalized} 分 · 有效权重 {item.effectiveWeight}%</span><em>贡献 {Math.round(item.contribution)} 分</em></p>)}</div>{mastery.manualAdjustment && <p className="privacyNote"><b>最近修正依据：</b>{mastery.manualAdjustment.reason} · {mastery.manualAdjustment.createdBy}</p>}</>}</section>
    <div className="profileGrid"><section className="panel profileCard"><div className="profileHead"><span>{String(student.name).slice(0, 1)}</span><div><h2>{String(student.name)}</h2><p>{String(student.nickname || "未设置昵称")}</p></div>{Boolean(student.riskConfirmed) && <em className="riskBadge">教师确认关注 · {String(student.riskTags || "")}</em>}</div><dl><div><dt>学校 / 教材</dt><dd>{String(student.school || "待记录")} · {String(student.textbookVersion || "待记录")}</dd></div><div><dt>选科 / 考试目标</dt><dd>{String(student.subjectChoice || "待记录")} · {String(student.examGoal || "待记录")}</dd></div><div><dt>基础水平</dt><dd>{String(student.foundationLevel || "待记录")}</dd></div><div><dt>优势</dt><dd>{String(student.strengths || "待记录")}</dd></div><div><dt>薄弱知识点</dt><dd>{String(student.weakKnowledge || "待记录")}</dd></div><div><dt>学习习惯</dt><dd>{String(student.learningHabits || "待记录")}</dd></div><div><dt>阶段目标</dt><dd>{String(student.stageGoal || "待制定")}</dd></div></dl><div className="privacyNote">监护人联系方式属于敏感信息，普通档案视图不展示。{contact ? <b> {contact}</b> : <button onClick={reveal}>教师确认后查看</button>}</div></section><section className="panel span2"><div className="panelTitle"><div><p>真实记录</p><h2>成长时间线</h2></div></div>{total === 0 ? <EmptyState title="还没有成长记录" description="完成课时表现、作业、测验、反馈或错题登记后，会按时间显示在这里。" /> : <><div className="summaryCounts"><span>课时表现 <b>{data.lessonRecords.length}</b></span><span>作业记录 <b>{data.submissions.length}</b></span><span>课程反馈 <b>{data.feedback.length}</b></span><span>测验结果 <b>{data.results.length}</b></span><span>待巩固错题 <b>{wrongQuestions.filter((item: Record<string, any>) => item.status === "active").length}</b></span></div><div className="growthTimeline">{items.map((item, index) => <article key={`${item.type}-${index}`}><time>{String(item.date || "日期待补")}</time><span>{item.type}</span><div><b>{String(item.title || "")}</b><p>{item.detail}</p></div></article>)}</div></>}</section></div>
    <section className="panel wrongQuestionPanel"><div className="panelTitle"><div><p>错题闭环</p><h2>错题与掌握状态</h2></div><button className="secondaryButton" onClick={openWrongQuestion}>＋ 登记错题</button></div>{wrongQuestions.length === 0 ? <EmptyState title="还没有错题记录" description="登记真实错题后，可追踪巩固和掌握状态。" /> : <div className="wrongQuestionList">{wrongQuestions.map((item: Record<string, any>) => <article key={item.id}><div><span className={`statusBadge ${item.status === "mastered" ? "completed" : "draft"}`}>{item.status === "mastered" ? "已掌握" : "待巩固"}</span><b>{item.stem}</b><small>{item.knowledgePoints || "知识点待标注"}{item.lessonTopic ? ` · ${item.lessonTopic}` : ""}</small>{item.incorrectAnswer && <p>学生作答：{item.incorrectAnswer}</p>}{item.reason && <p>错因备注：{item.reason}</p>}</div><div className="cardActions"><button onClick={() => setWrongStatus(Number(item.id), item.status === "mastered" ? "active" : "mastered")}>{item.status === "mastered" ? "重新巩固" : "标记已掌握"}</button><button onClick={() => removeWrongQuestion(Number(item.id))}>删除</button></div></article>)}</div>}</section>
    {wrongOpen && <div className="modalBackdrop"><div className="lessonModal" role="dialog" aria-modal="true" aria-labelledby="wrong-question-title"><div className="modalTitle"><div><p>基于正式题库</p><h2 id="wrong-question-title">登记学生错题</h2></div><button aria-label="关闭" onClick={() => setWrongOpen(false)}>×</button></div><div className="formGrid"><label className="wide">选择题目<select value={wrongForm.questionId} onChange={(event) => setWrongForm({ ...wrongForm, questionId: event.target.value })}><option value="">请选择正式题库题目</option>{questionChoices.map((question) => <option key={question.id} value={question.id}>{question.questionType} · {String(question.stem).slice(0, 48)}</option>)}</select></label><label>学生本次作答<input value={wrongForm.incorrectAnswer} onChange={(event) => setWrongForm({ ...wrongForm, incorrectAnswer: event.target.value })} placeholder="如：选 B 或简要写法" /></label><label>错因 / 巩固建议<input value={wrongForm.reason} onChange={(event) => setWrongForm({ ...wrongForm, reason: event.target.value })} placeholder="如：混淆概念、审题遗漏" /></label></div><div className="privacyNote">登记后会进入该学生的成长时间线；教师确认掌握后可保留历史记录。</div><div className="modalActions"><button onClick={() => setWrongOpen(false)}>取消</button><button className="primaryButton" onClick={saveWrongQuestion}>保存错题</button></div></div></div>}
    {masteryOpen && <div className="modalBackdrop"><div className="lessonModal small" role="dialog" aria-modal="true" aria-labelledby="mastery-title"><div className="modalTitle"><div><p>保留系统计算与修正记录</p><h2 id="mastery-title">人工修正掌握度</h2></div><button aria-label="关闭" onClick={() => setMasteryOpen(false)}>×</button></div><div className="formGrid"><label>掌握度（0–100）<input type="number" min="0" max="100" value={masteryScore} onChange={(event) => setMasteryScore(event.target.value)} /></label><label className="wide">修正依据<textarea value={masteryReason} onChange={(event) => setMasteryReason(event.target.value)} placeholder="例如：最近口头检测表现明显提升，系统尚未录入该次成绩" /></label></div><div className="privacyNote">系统原始分不会被覆盖；每次修正都会记录教师、时间、原始分与理由。</div><div className="modalActions"><button onClick={() => setMasteryOpen(false)}>取消</button><button className="primaryButton" onClick={saveMastery}>保存修正</button></div></div></div>}
    {editing && <div className="modalBackdrop"><div className="lessonModal" role="dialog" aria-modal="true" aria-labelledby="student-edit-title"><div className="modalTitle"><div><p>更新成长档案</p><h2 id="student-edit-title">编辑学生信息</h2></div><button aria-label="关闭" onClick={() => setEditing(false)}>×</button></div><div className="formGrid"><label>姓名<input value={form.name || ""} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>昵称<input value={form.nickname || ""} onChange={(event) => setForm({ ...form, nickname: event.target.value })} /></label><label>年级<select value={form.grade || "高一"} onChange={(event) => setForm({ ...form, grade: event.target.value })}>{["七年级", "八年级", "九年级", "高一", "高二", "高三"].map((item) => <option key={item}>{item}</option>)}</select></label><label>学校<input value={form.school || ""} onChange={(event) => setForm({ ...form, school: event.target.value })} /></label><label>教材版本<input value={form.textbookVersion || ""} onChange={(event) => setForm({ ...form, textbookVersion: event.target.value })} /></label><label>选科 / 考试方向<input value={form.subjectChoice || ""} onChange={(event) => setForm({ ...form, subjectChoice: event.target.value })} /></label><label>考试目标<input value={form.examGoal || ""} onChange={(event) => setForm({ ...form, examGoal: event.target.value })} /></label><label>基础水平<input value={form.foundationLevel || ""} onChange={(event) => setForm({ ...form, foundationLevel: event.target.value })} /></label><label>优势<input value={form.strengths || ""} onChange={(event) => setForm({ ...form, strengths: event.target.value })} /></label><label>薄弱知识点<input value={form.weakKnowledge || ""} onChange={(event) => setForm({ ...form, weakKnowledge: event.target.value })} /></label><label>学习习惯<input value={form.learningHabits || ""} onChange={(event) => setForm({ ...form, learningHabits: event.target.value })} /></label><label>风险标签<input value={form.riskTags || ""} onChange={(event) => setForm({ ...form, riskTags: event.target.value })} /></label><label className="checkLabel"><input type="checkbox" checked={Boolean(form.riskConfirmed)} onChange={(event) => setForm({ ...form, riskConfirmed: event.target.checked })} />教师确认关注</label><label className="wide">阶段目标<textarea value={form.stageGoal || ""} onChange={(event) => setForm({ ...form, stageGoal: event.target.value })} /></label><label className="wide">备注<textarea value={form.notes || ""} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></label></div><div className="privacyNote">如果需要更新监护人联系方式，请使用下方“教师确认后查看”入口核对后再另行录入；普通编辑不会覆盖原有联系方式。</div><div className="modalActions"><button onClick={() => setEditing(false)}>取消</button><button className="primaryButton" onClick={save}>保存档案</button></div></div></div>}
  </AppShell>;
}
