"use client";

import { useEffect, useState } from "react";
import { AppShell, EmptyState } from "../components/AppShell";
import { parseAnswerCardOcr } from "../lib/answer-card-ocr";
import { recognizeChineseImage } from "../lib/local-ocr";

type Row = Record<string, any> & { id: number; name?: string; title?: string };
type Item = Record<string, any> & { questionNumber?: string; teacherScore?: string | number; maxScore?: string | number };
const blankItem = (number = 1): Item => ({ questionNumber: String(number), studentAnswer: "", standardAnswer: "", teacherScore: "", maxScore: "", knowledgePoints: "", confidence: 0, reviewStatus: "pending" });
export default function RecognitionPage() {
  const [students, setStudents] = useState<Row[]>([]), [assessments, setAssessments] = useState<Row[]>([]), [studentId, setStudentId] = useState(""), [assessmentId, setAssessmentId] = useState(""), [file, setFile] = useState<File | null>(null), [assetId, setAssetId] = useState<number | null>(null), [items, setItems] = useState<Item[]>([blankItem()]), [jobId, setJobId] = useState<number | null>(null), [message, setMessage] = useState(""), [ocrText, setOcrText] = useState(""), [ocrMeta, setOcrMeta] = useState<Record<string, any> | null>(null), [busy, setBusy] = useState(false), [progress, setProgress] = useState(0);
  useEffect(() => { Promise.all([fetch("/api/students").then((response) => response.json()), fetch("/api/assessments").then((response) => response.json())]).then(([studentData, assessmentData]) => { setStudents(studentData.students || []); setAssessments(assessmentData.assessments || []); }); }, []);
  const uploadAndRecognize = async () => {
    if (!file) return; setBusy(true); setMessage("正在本机预处理和OCR识别…");
    try {
      const form = new FormData(); form.append("file", file); form.append("purpose", "answer-card");
      const [uploadResponse, ocr] = await Promise.all([fetch("/api/files", { method: "POST", body: form }), recognizeChineseImage(file, (event) => setProgress(Math.round(event.progress * 100)))]), uploadData = await uploadResponse.json();
      if (!uploadResponse.ok) throw new Error(uploadData.error || "原图保存失败");
      const parsed = parseAnswerCardOcr(ocr.text, students as Array<{ id: number; name: string }>, assessments as Array<{ id: number; title: string }>, ocr.confidence);
      setAssetId(uploadData.id); setOcrText(ocr.text); setOcrMeta(parsed); setStudentId(parsed.studentId ? String(parsed.studentId) : ""); setAssessmentId(parsed.assessmentId ? String(parsed.assessmentId) : ""); setItems(parsed.items); setMessage(`本机OCR完成（约${Math.round(ocr.confidence * 100)}%）。姓名、考试与分数均须人工确认；空分数可手填。`);
    } catch (error) { setMessage(error instanceof Error ? error.message : "识别失败，请人工录入"); }
    finally { setBusy(false); }
  };
  const create = async () => { if (!assetId) return; const response = await fetch("/api/recognition", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "create", studentId: Number(studentId), assessmentId: Number(assessmentId), sourceAssetId: assetId, items }) }), data = await response.json(); if (!response.ok) { setMessage(data.error || "保存失败"); return; } setJobId(data.id); const detail = await fetch(`/api/recognition?id=${data.id}`).then((result) => result.json()); setItems(detail.items || items); setMessage("校对任务已保存，确认前不会写入正式成绩。"); };
  const confirmResult = async () => { if (!jobId) return; const save = await fetch("/api/recognition", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "save", jobId, progress: 100, items: items.map((item) => ({ ...item, reviewStatus: "confirmed", teacherScore: Number(item.teacherScore ?? item.teacher_score), maxScore: Number(item.maxScore ?? item.max_score) })) }) }); if (!save.ok) { setMessage("逐题分数保存失败"); return; } const response = await fetch("/api/recognition", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "confirm", jobId }) }), data = await response.json(); setMessage(response.ok ? `已确认${data.count}题，总分${data.score}，正式写入学情。` : data.error || "确认失败"); };
  const update = (index: number, key: string, value: unknown) => setItems((rows) => rows.map((item, rowIndex) => rowIndex === index ? { ...item, [key]: value } : item));
  return <AppShell title="答题卡校对" subtitle="本机OCR初识别；原图保留、存疑必核、教师确认后才进入成绩">
    {message && <div className="saveToast" role="status">{message}</div>}
    <section className="panel"><div className="panelTitle"><div><p>上传 → OCR → 校对 → 确认</p><h2>新建答题卡任务</h2></div><span>OCR资源按需加载，不进入首页</span></div><div className="formGrid"><label>学生<select value={studentId} onChange={(event) => setStudentId(event.target.value)}><option value="">【存疑】请选择</option>{students.map((student) => <option value={student.id} key={student.id}>{student.name}</option>)}</select></label><label>考试/测验<select value={assessmentId} onChange={(event) => setAssessmentId(event.target.value)}><option value="">【存疑】请选择</option>{assessments.map((assessment) => <option value={assessment.id} key={assessment.id}>{assessment.title}</option>)}</select></label><label className="wide">答题卡图片<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => setFile(event.target.files?.[0] || null)} /></label></div><button className="primaryButton" disabled={!file || busy} onClick={() => void uploadAndRecognize()}>{busy ? `本机识别 ${progress}%` : "保存原图并开始OCR"}</button>{ocrMeta && <div className="recognitionMeta"><span>识别考试：{ocrMeta.assessmentTitle || "【存疑】"}</span><span>日期：{ocrMeta.date || "【存疑】"}</span><span>总分：{ocrMeta.totalScore ?? "【存疑】"}</span></div>}{ocrText && <details><summary>核对OCR原文</summary><pre>{ocrText}</pre></details>}</section>
    {assetId ? <section className="panel tablePanel"><div className="panelTitle"><div><p>低置信或缺失字段显示【存疑】</p><h2>逐题校对</h2></div><button onClick={() => setItems([...items, blankItem(items.length + 1)])}>＋ 添加题目</button></div><div className="tableScroll"><table><thead><tr><th>题号</th><th>学生答案</th><th>标准答案</th><th>得分/满分</th><th>知识点</th><th>状态</th></tr></thead><tbody>{items.map((item, index) => <tr key={item.id || index}><td><input value={item.question_number ?? item.questionNumber ?? ""} onChange={(event) => update(index, "questionNumber", event.target.value)} /></td><td><input value={item.student_answer ?? item.studentAnswer ?? ""} onChange={(event) => update(index, "studentAnswer", event.target.value)} /></td><td><input value={item.standard_answer ?? item.standardAnswer ?? ""} onChange={(event) => update(index, "standardAnswer", event.target.value)} /></td><td><input aria-label="得分" type="number" value={item.teacher_score ?? item.teacherScore ?? ""} onChange={(event) => update(index, "teacherScore", event.target.value)} /><input aria-label="满分" type="number" value={item.max_score ?? item.maxScore ?? ""} onChange={(event) => update(index, "maxScore", event.target.value)} /></td><td><input value={item.knowledge_points ?? item.knowledgePoints ?? ""} onChange={(event) => update(index, "knowledgePoints", event.target.value)} /></td><td><span className="statusBadge review">{Number(item.confidence || 0) >= .82 && (item.teacherScore ?? item.teacher_score) !== "" ? "待确认" : "【存疑】"}</span></td></tr>)}</tbody></table></div><div className="modalActions">{!jobId ? <button className="primaryButton" disabled={!studentId || !assessmentId} onClick={() => void create()}>保存校对任务</button> : <button className="primaryButton" onClick={() => void confirmResult()}>确认并写入正式学情</button>}</div></section> : <EmptyState title="尚未上传答题卡图片" description="识别发生在本机浏览器；不会把学生图片发送给外部OCR服务。" />}
  </AppShell>;
}
