import { env } from "cloudflare:workers";

export async function GET(_:Request,c:{params:Promise<{id:string}>}){const {id}=await c.params,n=Number(id);const [members,assignments,feedback,reflections]=await Promise.all([
 env.DB.prepare("SELECT s.id,s.name,s.grade,a.status AS attendanceStatus,a.notes AS attendanceNote,r.participation,r.understanding,r.completion,r.teacher_note AS teacherNote,r.risk_tags AS riskTags,r.risk_confirmed AS riskConfirmed FROM lessons l JOIN enrollments e ON e.class_id=l.class_id AND e.status='active' JOIN students s ON s.id=e.student_id LEFT JOIN attendance a ON a.lesson_id=l.id AND a.student_id=s.id LEFT JOIN student_lesson_records r ON r.lesson_id=l.id AND r.student_id=s.id WHERE l.id=? ORDER BY s.name").bind(n).all(),
 env.DB.prepare("SELECT * FROM assignments WHERE lesson_id=? ORDER BY created_at DESC").bind(n).all(),
 env.DB.prepare("SELECT f.*,s.name AS studentName FROM feedback f LEFT JOIN students s ON s.id=f.student_id WHERE f.lesson_id=? ORDER BY f.created_at DESC").bind(n).all(),
 env.DB.prepare("SELECT * FROM reflections WHERE lesson_id=? ORDER BY created_at DESC").bind(n).all(),
]);return Response.json({members:members.results,assignments:assignments.results,feedback:feedback.results,reflections:reflections.results});}

export async function POST(request:Request,c:{params:Promise<{id:string}>}){const {id}=await c.params,lessonId=Number(id),p=await request.json() as Record<string,unknown>;
 if(p.action==="studentRecord"){const studentId=Number(p.studentId);await env.DB.batch([
  env.DB.prepare("INSERT INTO attendance (lesson_id,student_id,status,notes) VALUES (?,?,?,?) ON CONFLICT(lesson_id,student_id) DO UPDATE SET status=excluded.status,notes=excluded.notes").bind(lessonId,studentId,String(p.attendanceStatus||"present"),String(p.attendanceNote||"")),
  env.DB.prepare("INSERT INTO student_lesson_records (lesson_id,student_id,participation,understanding,completion,teacher_note,risk_tags,risk_confirmed) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(lesson_id,student_id) DO UPDATE SET participation=excluded.participation,understanding=excluded.understanding,completion=excluded.completion,teacher_note=excluded.teacher_note,risk_tags=excluded.risk_tags,risk_confirmed=excluded.risk_confirmed,updated_at=CURRENT_TIMESTAMP").bind(lessonId,studentId,Number(p.participation||0)||null,Number(p.understanding||0)||null,Number(p.completion||0)||null,String(p.teacherNote||""),String(p.riskTags||""),p.riskConfirmed?1:0),
 ]);return Response.json({ok:true});}
 if(p.action==="assignment"){const result=await env.DB.prepare("INSERT INTO assignments (lesson_id,title,requirements,due_at) VALUES (?,?,?,?) RETURNING id").bind(lessonId,String(p.title||"课后作业"),String(p.requirements||""),String(p.dueAt||"")).first<{id:number}>();if(result){const members=await env.DB.prepare("SELECT e.student_id AS id FROM lessons l JOIN enrollments e ON e.class_id=l.class_id AND e.status='active' WHERE l.id=?").bind(lessonId).all<{id:number}>();if(members.results.length)await env.DB.batch(members.results.map(m=>env.DB.prepare("INSERT INTO assignment_submissions (assignment_id,student_id,status) VALUES (?,?,'pending')").bind(result.id,m.id)));}return Response.json({ok:true});}
 if(p.action==="feedback"){await env.DB.prepare("INSERT INTO feedback (lesson_id,student_id,class_id,type,tone,content,status) SELECT id,?,?,?, ?,?, 'draft' FROM lessons WHERE id=?").bind(p.studentId?Number(p.studentId):null,p.classId?Number(p.classId):null,String(p.type||"lesson"),String(p.tone||"专业简洁"),String(p.content||""),lessonId).run();return Response.json({ok:true});}
 return Response.json({error:"不支持的操作"},{status:400});}
