// Generated by `npm run release:domain -- your-domain.cn`.
module.exports = Object.freeze({
  configured: true,
  rootDomain: "daofazuoye.cn",
  webOrigin: "https://daofazuoye.cn",
  apiOrigin: "https://daofazuoye.cn",
});
