import { env } from "cloudflare:workers";
import { audit, isDenied, requirePermission } from "../../../lib/access";

type Row = { id: number };
const now = () => new Date().toISOString();

const saveRecord = (runId: string, entityType: string, entityId: number) => env.DB.prepare("INSERT INTO demo_records(run_id,entity_type,entity_id) VALUES(?,?,?)").bind(runId, entityType, entityId).run();

export async function GET() {
  const access = await requirePermission("settings:read"); if (isDenied(access)) return access;
  const rows = await env.DB.prepare("SELECT run_id AS runId,COUNT(*) AS count,MAX(created_at) AS createdAt FROM demo_records GROUP BY run_id ORDER BY createdAt DESC").all();
  return Response.json({ runs: rows.results });
}

export async function POST() {
  const access = await requirePermission("settings:write"); if (isDenied(access)) return access;
  const existing = await env.DB.prepare("SELECT id FROM demo_records LIMIT 1").first();
  if (existing) return Response.json({ error: "当前工作区已有演示数据，请先清除后再创建新的演示数据" }, { status: 409 });
  const runId = `demo-${Date.now()}`, date = new Date().toISOString().slice(0, 10), db = env.DB;
  const [juniorClass, seniorClass] = await Promise.all([
    db.prepare("INSERT INTO classes(owner_id,name,stage,grade,course_type,start_date,schedule,notes,status) VALUES(?,?,?,?,?,?,?,?,?) RETURNING id").bind(access.id, "【演示】初三政治冲刺班", "初中", "九年级", "小班课", date, "每周六 09:00–11:00", "演示数据：可一键清除", "active").first<Row>(),
    db.prepare("INSERT INTO classes(owner_id,name,stage,grade,course_type,start_date,schedule,notes,status) VALUES(?,?,?,?,?,?,?,?,?) RETURNING id").bind(access.id, "【演示】高一政治提高班", "高中", "高一", "小班课", date, "每周日 14:00–16:00", "演示数据：可一键清除", "active").first<Row>(),
  ]);
  if (!juniorClass || !seniorClass) return Response.json({ error: "创建演示班级失败" }, { status: 500 });
  await Promise.all([saveRecord(runId, "class", juniorClass.id), saveRecord(runId, "class", seniorClass.id)]);
  const studentIds: number[] = [];
  for (let index = 0; index < 10; index += 1) { const classId = index < 5 ? juniorClass.id : seniorClass.id, grade = index < 5 ? "九年级" : "高一", student = await db.prepare("INSERT INTO students(name,grade,school,textbook_version,foundation_level,strengths,weak_knowledge,learning_habits,stage_goal,risk_tags,risk_confirmed,status,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) RETURNING id").bind(`【演示】${grade}学生${index + 1}`, grade, "演示学校", "统编版", index % 3 === 0 ? "基础待巩固" : "中等", "材料阅读", index % 3 === 0 ? "法治意识" : "无", "按时完成", index < 5 ? "中考道法提分" : "必修三夯实", index % 4 === 0 ? "知识漏洞" : "", index % 4 === 0 ? 1 : 0, "active", "演示数据：可一键清除").first<Row>(); if (!student) continue; studentIds.push(student.id); await db.prepare("INSERT INTO enrollments(class_id,student_id,status) VALUES(?,?,'active')").bind(classId, student.id).run(); await Promise.all([saveRecord(runId, "student", student.id), saveRecord(runId, "enrollment", student.id)]); }
  const lessonIds: number[] = [];
  for (let index = 0; index < 12; index += 1) { const classId = index % 2 ? seniorClass.id : juniorClass.id, stage = index % 2 ? "高中" : "初中", grade = index % 2 ? "高一" : "九年级", lessonDate = new Date(Date.now() - (11 - index) * 86400000).toISOString().slice(0, 10), topic = index % 2 ? "人民代表大会制度" : "法治中国建设", lesson = await db.prepare("INSERT INTO lessons(class_id,date,start_time,end_time,mode,location,course_name,stage,grade,textbook_version,volume,unit,topic,teaching_goals,key_points,actual_content,homework,next_plan,participation,understanding,completion,status,fee,fee_status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) RETURNING id").bind(classId, lessonDate, index % 2 ? "14:00" : "09:00", index % 2 ? "16:00" : "11:00", "offline", "教室", "【演示】思想政治辅导", stage, grade, "统编版", index % 2 ? "必修3 政治与法治" : "九年级上册", "第二单元", topic, "理解制度优势与法治意义", "结合材料提取观点", "演示课堂记录", "完成对应练习", "下次进行材料分析", 4, 3, 4, index < 10 ? "completed" : "scheduled", 200, index % 3 ? "paid" : "unpaid").first<Row>(); if (!lesson) continue; lessonIds.push(lesson.id); await saveRecord(runId, "lesson", lesson.id); }
  const questionIds: number[] = [];
  for (let index = 0; index < 30; index += 1) { const stage = index < 15 ? "初中" : "高中", grade = index < 15 ? "九年级" : "高一", type = index % 3 === 0 ? "材料题" : "单选题", stem = `【演示】${stage}政治题 ${index + 1}：请根据材料分析人民当家作主与法治建设的关系。`, fingerprint = `demo-${runId}-${index}`, question = await db.prepare("INSERT INTO questions(stem,material,options,answer,analysis,question_type,difficulty,score,stage,grade,textbook_version,volume,unit,topic,knowledge_points,core_competencies,source,source_file,exam_type,fingerprint,reviewed,tags,recorded_by,status,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) RETURNING id").bind(stem, type === "材料题" ? "【演示材料】全过程人民民主和法治建设相互促进。" : "", type === "单选题" ? "A．人民当家作主\nB．资本决定政治\nC．权力没有约束\nD．法律没有作用" : "", type === "单选题" ? "A" : "围绕人民当家作主、法治保障作答", "演示解析：回扣教材观点并结合材料。", type, index % 5 + 1, type === "单选题" ? 3 : 8, stage, grade, "统编版", stage === "高中" ? "必修3 政治与法治" : "九年级上册", "第二单元", index % 2 ? "人民民主" : "法治中国", index % 2 ? "全过程人民民主" : "法治中国", "政治认同", "【演示数据】", "【演示数据】", "阶段练习", fingerprint, 1, "演示数据", access.name, "active", "演示数据：可一键清除").first<Row>(); if (!question) continue; questionIds.push(question.id); await saveRecord(runId, "question", question.id); }
  for (let index = 0; index < 2; index += 1) { const ids = questionIds.slice(index * 10, index * 10 + 10), paper = await db.prepare("INSERT INTO papers(title,type,stage,grade,textbook_version,duration_minutes,instructions,total_score,status) VALUES(?,?,?,?,?,?,?,?,?) RETURNING id").bind(`【演示】${index ? "高一" : "初三"}政治阶段练习`, "阶段测", index ? "高中" : "初中", index ? "高一" : "九年级", "统编版", 45, "演示试卷：请在规定时间内完成。", ids.length * 5, "draft").first<Row>(); if (!paper) continue; await saveRecord(runId, "paper", paper.id); for (let position = 0; position < ids.length; position += 1) await db.prepare("INSERT INTO paper_questions(paper_id,question_id,position,score) VALUES(?,?,?,?)").bind(paper.id, ids[position], position + 1, 5).run(); }
  for (let index = 0; index < 5; index += 1) { const lessonId = lessonIds[index], studentId = studentIds[index]; if (!lessonId || !studentId) continue; const feedback = await db.prepare("INSERT INTO feedback(lesson_id,student_id,type,tone,content,learning_content,highlights,consolidate,status,confirmed_at) VALUES(?,?,?,?,?,?,?,?,?,?) RETURNING id").bind(lessonId, studentId, "lesson", "温和鼓励", "【演示】本节课已完成重点内容梳理，请结合错题巩固。", "人民民主与法治", "能够提取材料观点", "加强规范表述", "confirmed", now()).first<Row>(); if (feedback) await saveRecord(runId, "feedback", feedback.id); const reflection = await db.prepare("INSERT INTO reflections(lesson_id,date,tags,problem_type,expected_vs_actual,effective_practices,difficulties,student_evidence,next_action,action_completed,reusable_material,is_private) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) RETURNING id").bind(lessonId, date, "演示数据,材料分析", "教学节奏", "【演示】目标基本达成", "材料圈画关键词有效", "规范表述不完整", "课堂回答记录", "下次先示范答题框架", index % 2, "材料分析四步法", 1).first<Row>(); if (reflection) await saveRecord(runId, "reflection", reflection.id); }
  const reviewSet = await db.prepare("INSERT INTO question_sets(name,source_file,source_fingerprint,import_report,status) VALUES(?,?,?,?,?) RETURNING id").bind("【演示】Word 导入待校对试卷", "【演示】高中政治试卷.docx", `demo-review-${runId}`, JSON.stringify({ total: 1, imported: 1, reviewed: 0, incomplete: 1 }), "review").first<Row>();
  if (reviewSet) {
    await saveRecord(runId, "question_set", reviewSet.id);
    const reviewQuestion = await db.prepare("INSERT INTO questions(question_set_id,stem,options,answer,analysis,question_type,difficulty,score,stage,grade,textbook_version,volume,unit,knowledge_points,source,source_file,fingerprint,reviewed,tags,recorded_by,status,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) RETURNING id").bind(reviewSet.id, "【演示待校对】全过程人民民主是最广泛、最真实、最管用的民主。", "A．人民当家作主\nB．资本决定政治", "A", "【待教师核对】请补充排误依据与知识点。", "单选题", 3, 3, "高中", "高一", "统编版", "必修3 政治与法治", "第二单元", "全过程人民民主", "【演示 Word 导入】", "【演示】高中政治试卷.docx", `demo-review-question-${runId}`, 0, "演示数据,待校对", access.name, "review", "演示数据：可一键清除").first<Row>();
    if (reviewQuestion) await saveRecord(runId, "question", reviewQuestion.id);
  }
  const assessment = await db.prepare("INSERT INTO assessments(class_id,title,date) VALUES(?,?,?) RETURNING id").bind(juniorClass.id, "【演示】初三政治阶段测验", date).first<Row>();
  if (assessment) {
    await saveRecord(runId, "assessment", assessment.id);
    for (let index = 0; index < Math.min(5, studentIds.length); index += 1) { const result = await db.prepare("INSERT INTO assessment_results(assessment_id,student_id,score,knowledge_mastery) VALUES(?,?,?,?) RETURNING id").bind(assessment.id, studentIds[index], 68 + index * 5, index % 2 ? "法治意识" : "全过程人民民主").first<Row>(); if (result) await saveRecord(runId, "assessment_result", result.id); }
  }
  for (let index = 0; index < Math.min(2, studentIds.length, questionIds.length); index += 1) { const wrong = await db.prepare("INSERT INTO wrong_questions(student_id,question_id,lesson_id,incorrect_answer,reason,status,occurred_at) VALUES(?,?,?,?,?,'active',?) RETURNING id").bind(studentIds[index], questionIds[index], lessonIds[index] || null, index ? "材料要点不完整" : "B", index ? "规范表述遗漏教材观点" : "混淆人民民主与资本政治", now()).first<Row>(); if (wrong) await saveRecord(runId, "wrong_question", wrong.id); }
  await audit(access, "seed_demo", "demo", runId, { classes: 2, students: studentIds.length, lessons: lessonIds.length, questions: questionIds.length + 1, papers: 2, assessment: Boolean(assessment), reviewSet: Boolean(reviewSet) });
  return Response.json({ ok: true, runId, summary: { classes: 2, students: studentIds.length, lessons: lessonIds.length, questions: questionIds.length + 1, papers: 2, assessments: assessment ? 1 : 0, wrongQuestions: Math.min(2, studentIds.length, questionIds.length), reviewSets: reviewSet ? 1 : 0 } }, { status: 201 });
}

export async function DELETE(request: Request) {
  const access = await requirePermission("settings:write"); if (isDenied(access)) return access;
  const body = await request.json() as { confirmation?: string }; if (body.confirmation !== "清除演示数据") return Response.json({ error: "请输入“清除演示数据”确认" }, { status: 400 });
  const records = await env.DB.prepare("SELECT run_id AS runId,entity_type AS entityType,entity_id AS entityId FROM demo_records").all<{ runId: string; entityType: string; entityId: number }>();
  if (!records.results.length) return Response.json({ error: "当前没有可清除的演示数据" }, { status: 404 });
  const ids = (type: string) => records.results.filter((row) => row.entityType === type).map((row) => row.entityId), questionIds = ids("question"), lessonIds = ids("lesson"), paperIds = ids("paper"), assessmentIds = ids("assessment"), wrongQuestionIds = ids("wrong_question"), questionSetIds = ids("question_set"), studentIds = ids("student"), classIds = ids("class"), marks = (values: number[]) => values.map(() => "?").join(",") || "NULL";
  const statements = [
    env.DB.prepare(`DELETE FROM paper_questions WHERE paper_id IN (${marks(paperIds)})`).bind(...paperIds), env.DB.prepare(`DELETE FROM papers WHERE id IN (${marks(paperIds)})`).bind(...paperIds), env.DB.prepare(`DELETE FROM lesson_questions WHERE lesson_id IN (${marks(lessonIds)})`).bind(...lessonIds), env.DB.prepare(`DELETE FROM wrong_questions WHERE id IN (${marks(wrongQuestionIds)}) OR student_id IN (${marks(studentIds)})`).bind(...wrongQuestionIds, ...studentIds), env.DB.prepare(`DELETE FROM assessment_results WHERE assessment_id IN (${marks(assessmentIds)})`).bind(...assessmentIds), env.DB.prepare(`DELETE FROM assessments WHERE id IN (${marks(assessmentIds)})`).bind(...assessmentIds), env.DB.prepare(`DELETE FROM attendance WHERE lesson_id IN (${marks(lessonIds)})`).bind(...lessonIds), env.DB.prepare(`DELETE FROM student_lesson_records WHERE lesson_id IN (${marks(lessonIds)})`).bind(...lessonIds), env.DB.prepare(`DELETE FROM assignment_submissions WHERE student_id IN (${marks(studentIds)})`).bind(...studentIds), env.DB.prepare(`DELETE FROM assignments WHERE lesson_id IN (${marks(lessonIds)})`).bind(...lessonIds), env.DB.prepare(`DELETE FROM feedback WHERE id IN (${marks(ids("feedback"))})`).bind(...ids("feedback")), env.DB.prepare(`DELETE FROM reflections WHERE id IN (${marks(ids("reflection"))})`).bind(...ids("reflection")), env.DB.prepare(`DELETE FROM questions WHERE id IN (${marks(questionIds)})`).bind(...questionIds), env.DB.prepare(`DELETE FROM question_sets WHERE id IN (${marks(questionSetIds)})`).bind(...questionSetIds), env.DB.prepare(`DELETE FROM lessons WHERE id IN (${marks(lessonIds)})`).bind(...lessonIds), env.DB.prepare(`DELETE FROM enrollments WHERE student_id IN (${marks(studentIds)}) OR class_id IN (${marks(classIds)})`).bind(...studentIds, ...classIds), env.DB.prepare(`DELETE FROM staff_class_access WHERE class_id IN (${marks(classIds)})`).bind(...classIds), env.DB.prepare(`DELETE FROM students WHERE id IN (${marks(studentIds)})`).bind(...studentIds), env.DB.prepare(`DELETE FROM classes WHERE id IN (${marks(classIds)})`).bind(...classIds), env.DB.prepare("DELETE FROM demo_records"),
  ];
  await env.DB.batch(statements); await audit(access, "clear_demo", "demo", null, { runs: [...new Set(records.results.map((row) => row.runId))] });
  return Response.json({ ok: true });
}
