import { and, desc, eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { feedback } from "../../../db/schema";
import { audit, isDenied, requirePermission } from "../../lib/access";

const values = (p: Record<string, unknown>) => ({ lessonId: p.lessonId ? Number(p.lessonId) : null, studentId: p.studentId ? Number(p.studentId) : null, classId: p.classId ? Number(p.classId) : null, type: String(p.type || "lesson"), tone: String(p.tone || "专业简洁"), content: String(p.content || ""), learningContent: String(p.learningContent || ""), highlights: String(p.highlights || ""), consolidate: String(p.consolidate || ""), homeworkRequirements: String(p.homeworkRequirements || ""), parentAdvice: String(p.parentAdvice || ""), nextFocus: String(p.nextFocus || ""), periodStart: String(p.periodStart || ""), periodEnd: String(p.periodEnd || ""), periodSummary: String(p.periodSummary || ""), progress: String(p.progress || ""), problems: String(p.problems || ""), goals: String(p.goals || ""), suggestions: String(p.suggestions || ""), status: String(p.status || "draft"), confirmedAt: p.status === "confirmed" ? new Date().toISOString() : null });

export async function GET(request: Request) { const access = await requirePermission("feedback:read"); if (isDenied(access)) return access; const params = new URL(request.url).searchParams, type = params.get("type") || "", status = params.get("status") || "", conditions = []; if (type) conditions.push(eq(feedback.type, type)); if (status) conditions.push(eq(feedback.status, status)); const rows = await getDb().select().from(feedback).where(conditions.length ? and(...conditions) : undefined).orderBy(desc(feedback.updatedAt)); return Response.json({ feedback: rows }); }
export async function POST(request: Request) { const access = await requirePermission("feedback:write"); if (isDenied(access)) return access; const body = await request.json() as Record<string, unknown>, [row] = await getDb().insert(feedback).values(values(body)).returning(); await audit(access, "create", "feedback", row.id, { status: row.status, type: row.type }); return Response.json({ feedback: row }, { status: 201 }); }
