"use client";

import { useCallback, useEffect, useState } from "react";
import { AppShell, EmptyState } from "../components/AppShell";

export default function MiniSettingsPage() {
  const [students, setStudents] = useState<any[]>([]), [bindings, setBindings] = useState<any[]>([]), [studentId, setStudentId] = useState(""), [role, setRole] = useState("parent"), [invite, setInvite] = useState<any>(null), [message, setMessage] = useState("");
  const load = useCallback(async () => { const [s, b] = await Promise.all([fetch("/api/students").then((r) => r.json()), fetch("/api/mini/invites").then((r) => r.json())]); setStudents(s.students || []); setBindings(b.bindings || []); }, []);
  useEffect(() => { void load(); }, [load]);
  const create = async () => { const response = await fetch("/api/mini/invites", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ studentId: Number(studentId), role }) }), data = await response.json(); if (!response.ok) { setMessage(data.error || "生成失败"); return; } setInvite(data); setMessage("邀请码已生成；输入后仍需教师在本页确认") };
  const decide = async (id: number, decision: string) => { const label = decision === "confirm" ? "确认" : decision === "reject" ? "拒绝" : "停用"; if (!confirm(`${label}这条绑定关系？停用后旧会话将立即失去该学生的数据权限。`)) return; const response = await fetch(`/api/mini/bindings/${id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decision }) }), data = await response.json(); setMessage(response.ok ? `已${label}绑定` : data.error || `${label}失败`); if (response.ok) load(); };
  return <AppShell title="微信小程序" subtitle="测试登录、两步绑定、会话与开发配置"><section className="securityBanner"><div><b>当前为开发预览阶段</b><span>无正式 AppID，不会提交微信审核或对外发布。</span></div><p>正式接入前需配置合法域名、AppID、密钥、隐私协议和订阅消息模板；生产必须关闭测试登录。</p></section>{message && <div className="saveToast">{message}</div>}<section className="panel"><div className="panelTitle"><div><p>第一步</p><h2>生成7天有效的一次性邀请码</h2></div></div><div className="formGrid"><label>学生<select value={studentId} onChange={(event) => setStudentId(event.target.value)}><option value="">请选择</option>{students.map((student) => <option value={student.id} key={student.id}>{student.name} · {student.grade}</option>)}</select></label><label>身份<select value={role} onChange={(event) => setRole(event.target.value)}><option value="parent">家长</option><option value="student">学生</option></select></label></div><button className="primaryButton" disabled={!studentId} onClick={create}>生成邀请码</button>{invite && <div className="metricCard"><span>{role === "parent" ? "家长" : "学生"}邀请码</span><b>{invite.code}</b><small>有效期至 {String(invite.expiresAt).slice(0, 16)}；使用后进入待确认，不会立即开放学生数据。</small></div>}</section><section className="panel"><div className="panelTitle"><div><p>第二步</p><h2>教师确认绑定</h2></div></div>{bindings.length === 0 ? <EmptyState title="暂无绑定申请" description="学生或家长输入邀请码后，申请会出现在这里。" /> : <div className="accountList">{bindings.map((item) => <article key={item.id}><div><b>{item.displayName || "微信用户"} → {item.studentName}</b><span>{item.role === "parent" ? "家长" : "学生"} · {item.status === "pending" ? "待确认" : item.status === "active" ? "已生效" : item.status === "disabled" ? "已停用" : "已拒绝"}</span></div><em>{String(item.createdAt || "").slice(0, 16)}</em>{item.status === "pending" && <><button onClick={() => decide(item.id, "confirm")}>确认</button><button onClick={() => decide(item.id, "reject")}>拒绝</button></>}{item.status === "active" && <button onClick={() => decide(item.id, "disable")}>停用</button>}</article>)}</div>}</section><section className="panel"><h2>一期明确范围</h2><p>整张试卷布置、多附件提交、家长代交、批改草稿、订正版本、增量同步和隐私遮罩后的优秀作业。不开发聊天、点赞、评论、排行、收费商城或自动群发。</p></section></AppShell>;
}
