"use client";

import { useCallback, useEffect, useState } from "react";
import { AppShell, EmptyState } from "../components/AppShell";

export default function MiniSettingsPage() {
  const [students, setStudents] = useState<any[]>([]), [bindings, setBindings] = useState<any[]>([]), [accounts, setAccounts] = useState<any[]>([]), [studentId, setStudentId] = useState(""), [role, setRole] = useState("parent"), [invite, setInvite] = useState<any>(null), [message, setMessage] = useState("");
  const load = useCallback(async () => { const [s, b, a] = await Promise.all([fetch("/api/students").then((r) => r.json()), fetch("/api/mini/invites").then((r) => r.json()), fetch("/api/mini/accounts").then((r) => r.json())]); setStudents(s.students || []); setBindings(b.bindings || []); setAccounts(a.accounts || []); }, []);
  useEffect(() => { void load(); }, [load]);
  const create = async () => { const response = await fetch("/api/mini/invites", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ studentId: Number(studentId), role }) }), data = await response.json(); if (!response.ok) { setMessage(data.error || "生成失败"); return; } setInvite(data); setMessage("邀请码已生成；输入后仍需教师在本页确认") };
  const decide = async (id: number, decision: string) => { const label = decision === "confirm" ? "确认" : decision === "reject" ? "拒绝" : "停用"; if (!confirm(`${label}这条绑定关系？停用后旧会话将立即失去该学生的数据权限。`)) return; const response = await fetch(`/api/mini/bindings/${id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decision }) }), data = await response.json(); setMessage(response.ok ? `已${label}绑定` : data.error || `${label}失败`); if (response.ok) load(); };
  const linkTeacher = async (accountId: number) => { if (!confirm(`确认把微信账号 #${accountId} 关联为您的教师端？请先核对小程序显示的账号编号。`)) return; const response = await fetch("/api/mini/accounts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ accountId, action: "linkTeacher" }) }), data = await response.json(); setMessage(response.ok ? `微信账号 #${accountId} 已关联为教师端` : data.error || "关联失败"); if (response.ok) void load(); };
  return <AppShell title="微信小程序" subtitle="正式登录、两步绑定与教师端关联"><section className="securityBanner"><div><b>“来写作业吧”正式 AppID 已配置</b><span>wxfec0f64566c68a2c</span></div><p>正式服务从服务器密钥系统读取 AppSecret，并使用微信公众平台登记的合法域名；生产环境不会显示测试登录。</p></section>{message && <div className="saveToast">{message}</div>}<section className="panel"><div className="panelTitle"><div><p>教师本人</p><h2>关联小程序教师端</h2></div></div>{accounts.filter((item) => item.role !== "teacher" || !item.userId).length === 0 ? <EmptyState title="暂无待关联微信账号" description="先用本人微信打开正式预览，小程序会显示账号编号。" /> : <div className="accountList">{accounts.filter((item) => item.role !== "teacher" || !item.userId).map((item) => <article key={item.id}><div><b>微信账号 #{item.id}</b><span>{item.displayName || "微信用户"} · 当前身份 {item.role}</span></div><em>{String(item.createdAt || "").slice(0, 16)}</em><button onClick={() => void linkTeacher(Number(item.id))}>关联为我的教师端</button></article>)}</div>}</section><section className="panel"><div className="panelTitle"><div><p>学生与家长</p><h2>生成7天有效的一次性邀请码</h2></div></div><div className="formGrid"><label>学生<select value={studentId} onChange={(event) => setStudentId(event.target.value)}><option value="">请选择</option>{students.map((student) => <option value={student.id} key={student.id}>{student.name} · {student.grade}</option>)}</select></label><label>身份<select value={role} onChange={(event) => setRole(event.target.value)}><option value="parent">家长</option><option value="student">学生</option></select></label></div><button className="primaryButton" disabled={!studentId} onClick={create}>生成邀请码</button>{invite && <div className="metricCard"><span>{role === "parent" ? "家长" : "学生"}邀请码</span><b>{invite.code}</b><small>有效期至 {String(invite.expiresAt).slice(0, 16)}；使用后进入待确认，不会立即开放学生数据。</small></div>}</section><section className="panel"><div className="panelTitle"><div><p>第二步</p><h2>教师确认学生/家长绑定</h2></div></div>{bindings.length === 0 ? <EmptyState title="暂无绑定申请" description="学生或家长输入邀请码后，申请会出现在这里。" /> : <div className="accountList">{bindings.map((item) => <article key={item.id}><div><b>{item.displayName || "微信用户"} → {item.studentName}</b><span>{item.role === "parent" ? "家长" : "学生"} · {item.status === "pending" ? "待确认" : item.status === "active" ? "已生效" : item.status === "disabled" ? "已停用" : "已拒绝"}</span></div><em>{String(item.createdAt || "").slice(0, 16)}</em>{item.status === "pending" && <><button onClick={() => decide(item.id, "confirm")}>确认</button><button onClick={() => decide(item.id, "reject")}>拒绝</button></>}{item.status === "active" && <button onClick={() => decide(item.id, "disable")}>停用</button>}</article>)}</div>}</section><section className="panel"><h2>一期明确范围</h2><p>整张试卷布置、多附件提交、家长代交、批改草稿、订正版本、增量同步和隐私遮罩后的优秀作业。不开发聊天、点赞、评论、排行、收费商城或自动群发。</p></section></AppShell>;
}
