"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { AppShell, EmptyState } from "../components/AppShell";

type Resource = Record<string, any> & { id: number };
const blank = { title: "", type: "备课素材", tags: "", url: "", content: "", visibility: "private" };

export default function ResourcesPage() {
  const [rows, setRows] = useState<Resource[]>([]), [q, setQ] = useState(""), [open, setOpen] = useState(false), [form, setForm] = useState(blank), [message, setMessage] = useState(""), [canWrite, setCanWrite] = useState(false);
  const load = useCallback(() => fetch(`/api/resources?q=${encodeURIComponent(q)}`).then((r) => r.json()).then((data) => { setRows(data.resources || []); setCanWrite(Boolean(data.canWrite)); }), [q]);
  useEffect(() => { void load(); }, [load]);
  const save = async () => { const response = await fetch("/api/resources", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (!response.ok) { setMessage("请填写资源名称"); return; } setOpen(false); setForm(blank); setMessage("资源已保存"); load(); };
  const remove = async (id: number) => { if (!confirm("确认删除这份资源？删除后不可恢复。")) return; await fetch(`/api/resources/${id}`, { method: "DELETE" }); load(); };

  return <AppShell title="资源中心" subtitle="让教学准备更从容一点：保存素材，也承接反思中沉淀的教学策略" actions={<button className="primaryButton" onClick={() => setOpen(true)}>＋ 添加资源</button>}>
    {message && <div className="saveToast" role="status">{message}</div>}
    <section className="resourceWelcome"><div><p>知师研室 · 备课灵感库 · 初高中政治教师工作台</p><h2>让一份好资源，真正回到课堂。</h2><span>这里公开分享政治教学资源与方法；班级、学生、课时和反馈始终保存在私人教师工作台。</span><div className="welcomeTags"><em>初中 / 高中</em><em>线上 / 线下</em><em>私密优先</em></div></div><div className="resourceShortcuts"><Link href="/workspace"><b>教师工作台 <em>登录后使用</em></b><span>管理课时、学生、题库和反馈</span></Link><Link href="/questions?import=1"><b>题库导入 <em>登录后使用</em></b><span>Word 上传、识别预览、逐题校对</span></Link><Link href="/papers"><b>专业组卷 <em>登录后使用</em></b><span>按知识点、题型、难度组合</span></Link><Link href="/reflections"><b>教学策略 <em>登录后使用</em></b><span>从真实教学反思沉淀</span></Link></div></section>
      <section className="workflowGuide" id="teaching-method"><div className="workflowHead"><div><p>莫老师的教学方法</p><h2>从一节真实课开始，逐步建立自己的系统</h2></div><span>不需要一次录完所有资料</span></div><div className="workflowSteps"><Link href="/classes"><b>01</b><strong>建立班级与学生</strong><span>先录学段、年级和必要的学习信息，联系方式默认不在列表展示。</span></Link><Link href="/lessons?new=1"><b>02</b><strong>记录一节真实课时</strong><span>写下目标、重难点、课堂活动和下次课计划，课后再补表现。</span></Link><Link href="/questions?import=1"><b>03</b><strong>导入并校对试题</strong><span>答案版 Word 先进入待校对区，核对题干、答案、解析和知识点后再入库。</span></Link><Link href="/reflections?new=1"><b>04</b><strong>复盘并沉淀策略</strong><span>把有效做法标记为可复用策略，下一次备课可以直接找到。</span></Link></div></section>
      <section className="connectionGuide"><div><p>外部资源连接</p><h2>云盘链接可以保存，权限边界要清楚</h2><span>可保存夸克网盘、WPS、学校教研平台等你有权访问的链接；打开时会在新标签页进入原网站。若要进入题库，请先下载自己有权使用的 Word 文件，再从“Word 导入”上传。</span></div><div className="connectionRules"><div><b>可以做</b><span>保存外部链接、打开原站、导入本地 .docx、人工校对后入库。</span></div><div><b>不会做</b><span>不会绕过登录、付费、下载券或验证码，也不会自动抓取未授权页面。</span></div><Link className="secondaryButton" href="/questions?import=1">查看导入步骤 →</Link></div></section>
      <section className="fieldGuide"><div><p>题库整理口径</p><h2>导入后会保留哪些教学字段？</h2></div><div className="fieldChips"><span>学段 / 年级</span><span>教材 / 单元</span><span>题型 / 难度</span><span>题干 / 选项</span><span>答案 / 解析</span><span>知识点</span><span>事实依据</span><span>答题逻辑</span><span>规范表述</span></div><small>自动识别只做初步整理；政治学科中的答案依据、教材观点和价值判断必须由教师最终确认。</small></section>
      <div className="toolbar"><input value={q} onChange={(e) => setQ(e.target.value)} onKeyDown={(e) => e.key === "Enter" && load()} placeholder="搜索资源名称、标签或内容" aria-label="搜索资源" /><button onClick={load}>搜索</button></div>
      <section className="resourceGrid">{rows.length === 0 ? <EmptyState title={canWrite ? "还没有个人资源" : "还没有公开资源"} description={canWrite ? "可以手动添加备课素材，也可以在教学反思中将有效做法沉淀为教学策略。这里不会填充虚构资源。" : "教师发布公开内容后会显示在这里；个人教学记录始终保持私有。"} action={canWrite ? <button className="secondaryButton" onClick={() => setOpen(true)}>添加第一份资源</button> : undefined} /> : rows.map((item) => <article className="resourceCard" key={item.id}><div><span>{item.type || "资源"}</span>{item.sourceRef?.startsWith("reflection:") && <em>来自教学反思</em>}</div><h3>{item.title}</h3><p>{item.content || "暂无内容说明"}</p><small>{item.tags || "未设置标签"}</small><div className="cardActions">{item.url && <a href={item.url} target="_blank" rel="noreferrer">打开链接</a>}{canWrite && <button onClick={async () => { if (!confirm("确认打印或导出这份资源？")) return; await fetch("/api/audit", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "print", entityType: "resource", entityId: item.id }) }); window.print(); }}>打印</button>}{canWrite && <button onClick={() => remove(item.id)}>删除</button>}</div></article>)}</section>
    {canWrite && open && <div className="modalBackdrop"><div className="lessonModal small" role="dialog" aria-modal="true" aria-labelledby="resource-title"><div className="modalTitle"><div><p>保存个人教学资产</p><h2 id="resource-title">添加资源</h2></div><button aria-label="关闭" onClick={() => setOpen(false)}>×</button></div><div className="formGrid"><label className="wide">资源名称<input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label>类型<select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}><option>备课素材</option><option>课堂活动</option><option>教学策略</option><option>规范话术</option><option>其他</option></select></label><label>可见范围<select value={form.visibility} onChange={(e) => setForm({ ...form, visibility: e.target.value })}><option value="private">仅教师与助教</option><option value="public">公开给学生、家长和访客</option></select></label><label className="wide">标签<input value={form.tags} onChange={(e) => setForm({ ...form, tags: e.target.value })} placeholder="逗号分隔" /></label><label className="wide">外部链接（可选）<input type="url" value={form.url} onChange={(e) => setForm({ ...form, url: e.target.value })} /></label><label className="wide">内容说明<textarea value={form.content} onChange={(e) => setForm({ ...form, content: e.target.value })} /></label></div><div className="privacyNote">公开资源会被匿名访客看到；包含学生信息的内容必须保持“仅教师与助教”。</div><div className="modalActions"><button onClick={() => setOpen(false)}>取消</button><button className="primaryButton" onClick={save}>保存资源</button></div></div></div>}
  </AppShell>;
}
