const api = require("../../utils/api"), recorder = wx.getRecorderManager();
Page({
  data: { assignmentId: 0, studentId: 0, text: "", files: [], busy: false, recording: false, operationId: "", error: "" },
  onLoad(query) { const assignmentId = Number(query.id), key = `submission-draft-${assignmentId}`, draft = wx.getStorageSync(key) || {}; this.draftKey = key; this.setData({ assignmentId, studentId: Number(query.studentId || draft.studentId || 0), text: draft.text || "", files: draft.files || [], operationId: draft.operationId || api.operationId("submission") }); recorder.onStop((result) => { this.setData({ recording: false, files: [...this.data.files, { tempFilePath: result.tempFilePath, name: "语音说明.mp3", status: "pending", progress: 0 }] }); this.persist(); }); },
  onUnload() { this.persist(); },
  persist() { wx.setStorageSync(this.draftKey, { studentId: this.data.studentId, text: this.data.text, files: this.data.files, operationId: this.data.operationId }); },
  input(event) { this.setData({ text: event.detail.value }); this.persist(); },
  choose() { wx.chooseMedia({ count: 9, mediaType: ["image", "video"], success: (result) => { this.setData({ files: [...this.data.files, ...result.tempFiles.map((file) => ({ tempFilePath: file.tempFilePath, name: file.tempFilePath.split("/").pop(), status: "pending", progress: 0 }))] }); this.persist(); } }); },
  chooseDocument() { wx.chooseMessageFile({ count: 9, type: "file", extension: ["pdf", "docx"], success: (result) => { this.setData({ files: [...this.data.files, ...result.tempFiles.map((file) => ({ tempFilePath: file.path, name: file.name, status: "pending", progress: 0 }))] }); this.persist(); } }); },
  toggleRecord() { if (this.data.recording) { recorder.stop(); return; } recorder.start({ format: "mp3", duration: 60000 }); this.setData({ recording: true }); },
  remove(event) { if (this.data.busy) return; const index = Number(event.currentTarget.dataset.index), files = this.data.files.filter((_, position) => position !== index); this.setData({ files }); this.persist(); },
  async uploadOne(index) { const files = [...this.data.files], file = files[index]; if (file.assetId) return file.assetId; files[index] = { ...file, status: "uploading", progress: 0 }; this.setData({ files }); try { const saved = await api.upload(file.tempFilePath, "submission", `${this.data.operationId}-file-${index}`, (progress) => { const next = [...this.data.files]; next[index] = { ...next[index], progress }; this.setData({ files: next }); }); const next = [...this.data.files]; next[index] = { ...next[index], assetId: saved.id, status: "uploaded", progress: 100 }; this.setData({ files: next }); this.persist(); return saved.id; } catch (error) { const next = [...this.data.files]; next[index] = { ...next[index], status: "failed", error: error.error || "上传失败" }; this.setData({ files: next }); this.persist(); throw error; } },
  async retry(event) { const index = Number(event.currentTarget.dataset.index); try { await this.uploadOne(index); } catch (error) { wx.showToast({ title: error.error || "重试失败", icon: "none" }); } },
  async submit() { if (this.data.busy) return; this.setData({ busy: true, error: "" }); try { const assetIds = []; for (let index = 0; index < this.data.files.length; index += 1) assetIds.push(await this.uploadOne(index)); await api.request("/api/mini/submissions", { method: "POST", timeout: 30000, data: { action: "submit", assignmentId: this.data.assignmentId, studentId: this.data.studentId || undefined, textContent: this.data.text, assetIds, operationId: this.data.operationId } }); wx.removeStorageSync(this.draftKey); wx.showToast({ title: "已提交" }); setTimeout(() => wx.navigateBack(), 800); } catch (error) { this.setData({ error: error.error || "提交失败；文字、已上传文件和操作编号已保留，可直接重试" }); this.persist(); } finally { this.setData({ busy: false }); } },
});
