"use client";

import { useCallback, useEffect, useState } from "react";
import { AppShell, EmptyState } from "../components/AppShell";

export default function FinancePage() {
  const [items, setItems] = useState<any[]>([]), [totals, setTotals] = useState<any>({}), [lessons, setLessons] = useState<any[]>([]), [lessonId, setLessonId] = useState(""), [statusFilter, setStatusFilter] = useState(""), [context, setContext] = useState<any>(null), [adjustment, setAdjustment] = useState("0"), [adjustmentReason, setAdjustmentReason] = useState(""), [payerType, setPayerType] = useState("institution"), [payerId, setPayerId] = useState(""), [preview, setPreview] = useState<any>(null), [message, setMessage] = useState(""), [month, setMonth] = useState(new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Shanghai", year: "numeric", month: "2-digit" }).format(new Date())), [monthly, setMonthly] = useState<any>(null);
  const load = useCallback(async () => { const query = new URLSearchParams({ lessonId, status: statusFilter }), [financeResponse, lessonResponse, monthlyResponse] = await Promise.all([fetch(`/api/finance?${query}`), fetch("/api/lessons?status=all"), fetch(`/api/finance/monthly?month=${month}`)]), [finance, lessonData, monthlyData] = await Promise.all([financeResponse.json(), lessonResponse.json(), monthlyResponse.json()]); setItems(finance.items || []); setTotals(finance.totals || {}); setLessons(lessonData.lessons || []); setMonthly(monthlyResponse.ok ? monthlyData : null); }, [lessonId, statusFilter, month]);
  useEffect(() => { const params = new URLSearchParams(location.search); setLessonId(params.get("lessonId") || ""); setStatusFilter(params.get("status") || ""); }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (!lessonId) { setContext(null); return; } const query = new URLSearchParams({ lessonId, payerType, payerId }); fetch(`/api/finance/context?${query}`).then((response) => response.json()).then(setContext); }, [lessonId, payerType, payerId]);
  const act = async (action: "preview" | "confirm") => { const response = await fetch("/api/finance", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, lessonId: Number(lessonId), payerType, payerId: Number(payerId) || null, adjustment: Number(adjustment), adjustmentReason }) }), data = await response.json(); if (!response.ok) { setMessage(data.exceptions?.length ? `${data.error}：${data.exceptions.map((item: any) => item.message).join("；")}` : data.error || "操作失败"); return; } if (action === "preview") setPreview(data); else { setMessage("结算规则、计算过程和金额快照已确认入账"); setPreview(null); void load(); } };
  return <AppShell title="课时与结算" subtitle="先核对规则来源和逐项计算，确认后才进入正式账目" actions={<><a className="secondaryButton" href="/api/finance/export?type=institution">导出机构明细</a><a className="primaryButton" href={`/api/finance/export?mode=monthly&month=${month}`}>导出{month}月WPS核对表</a></>}>
    {message && <div className="saveToast">{message}</div>}
    <div className="metricGrid"><article className="metricCard"><span>预计收入</span><b>¥{Number(totals.expected || 0).toFixed(2)}</b></article><article className="metricCard"><span>已收</span><b>¥{Number(totals.received || 0).toFixed(2)}</b></article><article className="metricCard"><span>待收与差额</span><b>¥{(Number(totals.expected || 0) - Number(totals.received || 0)).toFixed(2)}</b></article><article className="metricCard"><span>本月异常课时</span><b>{monthly?.summary?.exceptions || 0}</b></article></div>

    <section className="panel monthlyChecklist"><div className="panelTitle"><div><p>月度核对清单</p><h2>{month} 全部非取消课时</h2></div><input type="month" value={month} onChange={(event) => setMonth(event.target.value)} /></div>{monthly ? <><div className="summaryCounts"><span>课时 <b>{monthly.summary.lessons}</b></span><span>已完成 <b>{monthly.summary.completed}</b></span><span>未来未到期 <b>{monthly.summary.future}</b></span><span>异常 <b>{monthly.summary.exceptions}</b></span></div><div className="financeExceptionList">{monthly.items.filter((item: any) => item.exceptions.length).map((item: any) => <button key={item.lessonId} onClick={() => { setLessonId(String(item.lessonId)); setStatusFilter(item.financeStatus || ""); }}><b>{item.date} · {item.topic || item.courseName}</b><span>{item.exceptions.join("；")}</span></button>)}</div></> : <EmptyState title="暂时无法生成月度清单" description="请稍后重试。" />}</section>

    <section className="panel"><div className="panelTitle"><div><p>服务器解析有效规则</p><h2>生成课时结算预览</h2></div></div><div className="formGrid"><label>课时<select value={lessonId} onChange={(event) => { setLessonId(event.target.value); setPreview(null); }}><option value="">请选择</option>{lessons.map((lesson) => <option value={lesson.id} key={lesson.id}>{lesson.date} {lesson.startTime} {lesson.courseName}</option>)}</select></label><label>付款方类型<select value={payerType} onChange={(event) => { setPayerType(event.target.value); setPayerId(""); setPreview(null); }}><option value="institution">机构</option><option value="parent">家长/学生</option></select></label>{payerType === "institution" ? <label>机构<select value={payerId} onChange={(event) => { setPayerId(event.target.value); setPreview(null); }}><option value="">待选择</option>{(context?.institutions || []).map((institution: any) => <option value={institution.id} key={institution.id}>{institution.name}</option>)}</select></label> : <label>学生<select value={payerId} onChange={(event) => { setPayerId(event.target.value); setPreview(null); }}><option value="">待选择</option>{(context?.students || []).map((student: any) => <option value={student.id} key={student.id}>{student.name}</option>)}</select></label>}<label>手工调整<input type="number" value={adjustment} onChange={(event) => setAdjustment(event.target.value)} /></label>{Number(adjustment) !== 0 && <label className="wide">调整原因<textarea value={adjustmentReason} onChange={(event) => setAdjustmentReason(event.target.value)} placeholder="必须说明调整依据" /></label>}</div>
      {context?.source ? <div className="pricingSource"><b>计费规则 #{context.source.ruleId}</b><span>{context.source.subject} · 有效期 {context.source.effectiveFrom} 至 {context.source.effectiveTo}</span><span>底薪 ¥{context.source.baseFee} · 每生/单价 ¥{context.source.unitFee}</span></div> : lessonId && payerId ? <div className="noticeStrip"><b>缺少有效计费规则</b><span>可以预览异常，但不能确认入账。</span></div> : null}
      {context?.exceptions?.length ? <div className="financeWarnings">{context.exceptions.map((item: any, index: number) => <span key={`${item.type}-${index}`}>{item.message}</span>)}</div> : null}
      <div className="modalActions"><button disabled={!lessonId} onClick={() => act("preview")}>预览计算</button>{preview && <button className="primaryButton" disabled={!preview.context?.canConfirm} onClick={() => act("confirm")}>确认规则和金额并入账</button>}</div>{preview && <div className="calculationPreview"><b>{preview.formula}</b><ol>{preview.preview.items.map((item: any) => <li key={item.studentId}>学生#{item.studentId}：系数 {item.factor} × 单价 {item.unitFee} = ¥{item.amount}（{item.reason}）</li>)}</ol></div>}
    </section>

    <section className="panel tablePanel"><div className="panelTitle"><div><p>不可静默覆盖</p><h2>课时账目</h2></div><div className="cardActions"><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="">全部状态</option><option value="review">待核对</option><option value="pending">待收</option><option value="settled">已结算</option><option value="underpaid">少收</option><option value="overpaid">超收</option></select><button onClick={() => { setLessonId(""); setStatusFilter(""); }}>清空筛选</button></div></div>{items.length ? <div className="tableScroll"><table><thead><tr><th>日期</th><th>课程</th><th>规则来源</th><th>预计</th><th>实收</th><th>状态</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.date} {item.startTime}</td><td>{item.topic || item.courseName}<small>{item.location}</small></td><td>{item.pricingRuleId ? `规则#${item.pricingRuleId}` : "待补"}</td><td>¥{Number(item.expected_amount).toFixed(2)}</td><td>¥{Number(item.received_amount).toFixed(2)}</td><td>{item.status}</td></tr>)}</tbody></table></div> : <EmptyState title="暂无符合条件的结算记录" description="完成课时后先生成预览，确认后才进入账本。" />}</section>
  </AppShell>;
}
