"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { useParams } from "next/navigation";
import { AppShell,EmptyState } from "../../components/AppShell";
type Lesson=Record<string,string|number|null>;
export default function LessonDetail(){const {id}=useParams<{id:string}>(),[x,setX]=useState<Lesson|null>(null),[error,setError]=useState("");useEffect(()=>{fetch(`/api/lessons/${id}`).then(r=>r.json()).then(d=>d.lesson?setX(d.lesson):setError(d.error||"读取失败"))},[id]);if(error)return <AppShell title="课时详情"><EmptyState title="无法打开课时" description={error}/></AppShell>;if(!x)return <AppShell title="课时详情"><EmptyState title="正在读取课时" description="请稍候…"/></AppShell>;const block=(label:string,value:unknown)=><div className="timelineItem"><i></i><div><span>{label}</span><p>{String(value||"尚未记录")}</p></div></div>;return <AppShell title={String(x.topic||x.courseName)} subtitle={`${x.date} · ${x.grade} · ${x.status==="completed"?"已完成":"草稿"}`} actions={<><Link href={`/lessons?edit=${id}`} className="secondaryButton">编辑课时</Link><button className="primaryButton" onClick={()=>{if(confirm("确认打印或导出当前课时记录？打印预览中可选择“另存为 PDF”。"))window.print()}}>打印 / 导出 PDF</button></>}>
 <div className="lessonDetailGrid"><section className="panel lessonSummary"><div className="panelTitle"><div><p>课程信息</p><h2>{String(x.courseName)}</h2></div><span className={`statusBadge ${x.status}`}>{x.status==="completed"?"已完成":"草稿"}</span></div><dl><div><dt>时间</dt><dd>{String(x.date)}　{String(x.startTime||"待定")}–{String(x.endTime||"待定")}</dd></div><div><dt>授课</dt><dd>{x.mode==="online"?`线上 · ${String(x.onlineLink||"未填写链接")}`:`线下 · ${String(x.location||"未填写地点")}`}</dd></div><div><dt>教材</dt><dd>{String(x.textbookVersion||"未填写")} · {String(x.volume||"未填写")} · {String(x.unit||"未填写单元")}</dd></div><div><dt>课题</dt><dd>{String(x.topic||"未填写")}</dd></div></dl><div className="ratingSummary">{[["参与度",x.participation],["理解度",x.understanding],["完成度",x.completion],["纪律",x.discipline]].map(([k,v])=><div key={String(k)}><span>{k}</span><b>{v?`${v}/5`:"待评"}</b></div>)}</div></section>
 <section className="panel lessonTimeline"><div className="panelTitle"><div><p>完整记录</p><h2>教学时间线</h2></div></div>{block("课前 · 教学目标",x.teachingGoals)}{block("课前 · 重点与难点",`${x.keyPoints||"尚未记录"}\n${x.difficultPoints||""}`)}{block("课堂 · 实际内容",x.actualContent)}{block("课堂 · 使用资料与活动",`${x.materials||"尚未记录"}\n${x.activities||""}`)}{block("课后 · 作业",x.homework)}{block("课后 · 下次课计划",x.nextPlan)}</section>
 <section className="panel"><div className="panelTitle"><div><p>学生表现</p><h2>本节课学生记录</h2></div></div><EmptyState title="尚未记录学生表现" description="关联班级并添加出勤、参与度与需跟进项后，将显示在这里。" action={<Link className="secondaryButton" href="/students">查看学生档案</Link>}/></section>
 <section className="panel"><div className="panelTitle"><div><p>后续闭环</p><h2>反馈与反思</h2></div></div><div className="detailActions"><Link href={`/feedback?lesson=${id}`}>生成课程反馈草稿</Link><Link href={`/reflections?lesson=${id}`}>新建教学反思</Link><Link href="/questions">关联课堂题目</Link></div></section></div>
 </AppShell>}
