"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AppShell, EmptyState } from "../components/AppShell";

type Project = Record<string, any> & { id: number; name: string; category: string; grade: string; studentCount: number; recordedCount: number };
type Student = Record<string, any> & { studentId: number; name: string; score?: number | string };
const currentYear = () => { const now = new Date(), start = now.getMonth() >= 8 ? now.getFullYear() : now.getFullYear() - 1; return `${start}-${start + 1}`; };

export default function ExamProjectsPage() {
  const [academicYear, setAcademicYear] = useState(currentYear());
  const [projects, setProjects] = useState<Project[]>([]), [selected, setSelected] = useState<Project | null>(null), [students, setStudents] = useState<Student[]>([]);
  const [grade, setGrade] = useState(""), [category, setCategory] = useState(""), [message, setMessage] = useState(""), [busy, setBusy] = useState(false), [analytics, setAnalytics] = useState<Record<string, any> | null>(null);
  const load = useCallback(async () => { const response = await fetch(`/api/exam-projects?academicYear=${academicYear}`), data = await response.json(); setProjects(data.projects || []); }, [academicYear]);
  useEffect(() => { void load(); }, [load]);
  const generate = async () => { setBusy(true); const response = await fetch("/api/exam-projects", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ academicYear }) }), data = await response.json(); setBusy(false); setMessage(response.ok ? `已生成/补齐 ${data.projectCount} 个考试项目，重复执行不会重复。` : data.error || "生成失败"); if (response.ok) void load(); };
  const open = async (project: Project) => { setSelected(project); setAnalytics(null); const [results, stats] = await Promise.all([fetch(`/api/exam-projects/${project.id}/results`).then((r) => r.json()), fetch(`/api/exam-projects/${project.id}/analytics`).then((r) => r.json())]); setStudents(results.students || []); setAnalytics(stats); };
  const save = async () => { if (!selected) return; setBusy(true); const response = await fetch(`/api/exam-projects/${selected.id}/results`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ results: students.map((item) => ({ studentId: item.studentId, score: item.score ?? "", objectiveScore: item.objectiveScore ?? "", subjectiveScore: item.subjectiveScore ?? "", teacherNote: item.teacherNote || "" })) }) }), data = await response.json(); setBusy(false); setMessage(response.ok ? `已保存 ${data.updated} 名学生；空白仍为待录。` : data.error || "保存失败"); if (response.ok) { await open(selected); await load(); } };
  const grades = useMemo(() => [...new Set(projects.map((item) => item.grade))], [projects]), categories = useMemo(() => [...new Set(projects.map((item) => item.category))], [projects]);
  const visible = projects.filter((item) => (!grade || item.grade === grade) && (!category || item.category === category));
  return <AppShell title="考试项目" subtitle="按学年统一查看全体学生；未录成绩始终明确显示待录" actions={<button className="primaryButton" disabled={busy} onClick={() => void generate()}>生成本学年模板</button>}>
    {message && <div className="saveToast" role="status">{message}</div>}
    <div className="toolbar"><label>学年<input value={academicYear} onChange={(event) => setAcademicYear(event.target.value)} /></label><select value={grade} onChange={(event) => setGrade(event.target.value)}><option value="">全部年级</option>{grades.map((item) => <option key={item}>{item}</option>)}</select><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="">全部考试</option>{categories.map((item) => <option key={item}>{item}</option>)}</select></div>
    <section className="examProjectGrid">{visible.length ? visible.map((project) => <button key={project.id} className={selected?.id === project.id ? "examProjectCard active" : "examProjectCard"} onClick={() => void open(project)}><span>{project.grade} · {project.category}</span><b>{project.name}</b><em>{project.recordedCount || 0}/{project.studentCount || 0} 已录</em></button>) : <EmptyState title="本学年还没有考试项目" description="点击“生成本学年模板”，系统只为当前在读年级建立空白项目。" />}</section>
    {selected && <section className="panel examResults"><div className="sectionTitle"><div><p>{selected.grade} / {selected.category}</p><h2>{selected.name}</h2></div><button className="primaryButton" disabled={busy} onClick={() => void save()}>保存全体成绩</button></div><div className="scoreSummary"><article><b>{analytics?.summary?.recorded || 0}</b><span>已录人数</span></article><article><b>{analytics?.summary?.averageRate == null ? "数据不足" : `${analytics.summary.averageRate.toFixed(1)}%`}</b><span>平均得分率</span></article><article><b>{analytics?.summary?.volatility == null ? "数据不足" : analytics.summary.volatility.toFixed(1)}</b><span>成绩波动度</span></article></div><div className="tableWrap"><table><thead><tr><th>学生</th><th>学校</th><th>总分</th><th>客观题</th><th>主观题</th><th>状态</th></tr></thead><tbody>{students.map((student, index) => <tr key={student.studentId}><td>{student.name}</td><td>{student.school || "—"}</td><td><input type="number" min="0" max={selected.totalScore} value={student.score ?? ""} onChange={(event) => setStudents((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, score: event.target.value } : item))} /></td><td><input type="number" value={student.objectiveScore ?? ""} onChange={(event) => setStudents((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, objectiveScore: event.target.value } : item))} /></td><td><input type="number" value={student.subjectiveScore ?? ""} onChange={(event) => setStudents((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, subjectiveScore: event.target.value } : item))} /></td><td>{student.score === "" || student.score == null ? "待录" : "已录"}</td></tr>)}</tbody></table></div></section>}
  </AppShell>;
}
