import { eq } from "drizzle-orm";
import { getDb } from "../../../../db";
import { questions } from "../../../../db/schema";
import { audit, isDenied, requirePermission } from "../../../lib/access";
import { questionValues } from "../values";

export async function GET(_: Request, context: { params: Promise<{ id: string }> }) { const access = await requirePermission("questions:read"); if (isDenied(access)) return access; const { id } = await context.params; const [row] = await getDb().select().from(questions).where(eq(questions.id, Number(id))).limit(1); return row ? Response.json({ question: row }) : Response.json({ error: "题目不存在" }, { status: 404 }); }
export async function PUT(request: Request, context: { params: Promise<{ id: string }> }) { const access = await requirePermission("questions:write"); if (isDenied(access)) return access; const { id } = await context.params, body = await request.json() as Record<string, unknown>; const [question] = await getDb().update(questions).set({ ...questionValues(body), recordedBy: access.name, updatedAt: new Date().toISOString() }).where(eq(questions.id, Number(id))).returning(); await audit(access, "update", "question", id); return Response.json({ question }); }
export async function PATCH(request: Request, context: { params: Promise<{ id: string }> }) { const access = await requirePermission("questions:write"); if (isDenied(access)) return access; const { id } = await context.params, body = await request.json() as Record<string, unknown>, allowed = ["isFavorite", "isWrong", "isFrequent", "status"] as const, data: Record<string, unknown> = { updatedAt: new Date().toISOString() }; for (const key of allowed) if (key in body) data[key] = body[key]; const [question] = await getDb().update(questions).set(data).where(eq(questions.id, Number(id))).returning(); await audit(access, "update_flags", "question", id, { fields: Object.keys(body) }); return Response.json({ question }); }
export async function DELETE(_: Request, context: { params: Promise<{ id: string }> }) { const access = await requirePermission("questions:write"); if (isDenied(access)) return access; const { id } = await context.params; await getDb().delete(questions).where(eq(questions.id, Number(id))); await audit(access, "delete", "question", id); return Response.json({ ok: true }); }
