"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { AppShell, EmptyState } from "../components/AppShell";

type Row = Record<string, any>;
const queryValue = (key: string) => typeof window === "undefined" ? "" : new URLSearchParams(window.location.search).get(key) || "";

export default function AssessmentsPage() {
  const [rows, setRows] = useState<Row[]>([]), [classes, setClasses] = useState<Row[]>([]), [papers, setPapers] = useState<Row[]>([]), [open, setOpen] = useState(false), [message, setMessage] = useState(""), [classFilter, setClassFilter] = useState(() => queryValue("classId")), [status, setStatus] = useState("all"), [form, setForm] = useState({ title: "政治课堂测验", date: new Date().toISOString().slice(0, 10), classId: queryValue("classId"), paperId: "", totalScore: "100", type: "课堂测验", notes: "" });
  const load = useCallback(async () => { try { const params = new URLSearchParams({ classId: classFilter, status }), [a, c, p] = await Promise.all([fetch(`/api/assessments?${params}`), fetch("/api/classes?status=active"), fetch("/api/papers?status=all")]), ad = await a.json(), cd = await c.json(), pd = await p.json(); if (!a.ok) throw new Error(ad.error || "无法读取测验"); setRows(ad.assessments || []); setClasses(cd.classes || []); setPapers(pd.papers || []); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "无法读取测验"); } }, [classFilter, status]);
  useEffect(() => { void load(); }, [load]);
  const save = async () => { const response = await fetch("/api/assessments", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }), data = await response.json(); if (!response.ok) { setMessage(data.error || "新建测验失败"); return; } setOpen(false); setMessage("测验已创建，可以录入全班成绩"); load(); };
  return <AppShell title="测验与成绩" subtitle="班级测验、批量成绩和薄弱知识点" actions={<><Link prefetch={false} className="secondaryButton" href="/api/exports/assessments">导出成绩 CSV</Link><button className="primaryButton" onClick={() => setOpen(true)}>＋ 新建测验</button></>}>
    {message && <div className="saveToast" role="status">{message}</div>}
    <div className="toolbar"><select value={classFilter} onChange={(event) => setClassFilter(event.target.value)}><option value="">全部班级</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">全部状态</option><option value="draft">录入中</option><option value="completed">已完成</option></select></div>
    <section className="panel tablePanel">{rows.length === 0 ? <EmptyState title="还没有测验记录" description="创建测验后，可以按班级一次录入成绩并查看真实统计。" action={<button className="secondaryButton" onClick={() => setOpen(true)}>创建第一次测验</button>} /> : <div className="assessmentList">{rows.map((row) => <article key={row.id}><time>{row.date || "日期待补"}</time><div><span className={`statusBadge ${row.status}`}>{row.status === "completed" ? "已完成" : "录入中"}</span><h3><Link href={`/assessments/${row.id}`}>{row.title}</Link></h3><p>{row.className || "未关联班级"} · {row.type} · 总分 {row.totalScore}</p></div><div className="assessmentNumbers"><b>{row.resultCount || 0}</b><span>已录人数</span><b>{row.averageScore == null ? "—" : row.averageScore}</b><span>平均分</span></div><Link className="secondaryButton" href={`/assessments/${row.id}`}>录入 / 查看</Link></article>)}</div>}</section>
    {open && <div className="modalBackdrop"><div className="lessonModal small" role="dialog" aria-modal="true" aria-labelledby="assessment-title"><div className="modalTitle"><div><p>建立真实成绩记录</p><h2 id="assessment-title">新建测验</h2></div><button aria-label="关闭" onClick={() => setOpen(false)}>×</button></div><div className="formGrid"><label className="wide">测验名称<input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label>日期<input type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} /></label><label>班级<select value={form.classId} onChange={(event) => setForm({ ...form, classId: event.target.value })}><option value="">请选择班级</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>类型<select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}>{["课堂测验", "单元测验", "阶段考试", "模拟考试"].map((item) => <option key={item}>{item}</option>)}</select></label><label>总分<input type="number" min="1" max="1000" value={form.totalScore} onChange={(event) => setForm({ ...form, totalScore: event.target.value })} /></label><label className="wide">关联试卷（可选）<select value={form.paperId} onChange={(event) => setForm({ ...form, paperId: event.target.value })}><option value="">不关联试卷</option>{papers.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label className="wide">备注<textarea value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></label></div><div className="modalActions"><button onClick={() => setOpen(false)}>取消</button><button className="primaryButton" onClick={save}>创建并录入成绩</button></div></div></div>}
  </AppShell>;
}
