"use client";

import { useParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AppShell, EmptyState } from "../../components/AppShell";

type Result = Record<string, any> & { studentId: number; name: string };
export default function AssessmentDetail() {
  const { id } = useParams<{ id: string }>(), [assessment, setAssessment] = useState<Record<string, any> | null>(null), [results, setResults] = useState<Result[]>([]), [stats, setStats] = useState<Record<string, any>>({}), [message, setMessage] = useState(""), [dirty, setDirty] = useState(false), [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { const response = await fetch(`/api/assessments/${id}`), data = await response.json(); if (!response.ok) throw new Error(data.error || "无法读取测验"); setAssessment(data.assessment); setResults(data.results || []); setStats(data.stats || {}); setDirty(false); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "无法读取测验"); } }, [id]);
  useEffect(() => { void load(); }, [load]); useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (!dirty) return; event.preventDefault(); event.returnValue = ""; }; addEventListener("beforeunload", warn); return () => removeEventListener("beforeunload", warn); }, [dirty]);
  const set = (studentId: number, key: string, value: string) => { setResults((items) => items.map((item) => item.studentId === studentId ? { ...item, [key]: value } : item)); setDirty(true); };
  const save = async (status = "draft") => { setSaving(true); const response = await fetch(`/api/assessments/${id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ results, status }) }), data = await response.json(); setSaving(false); if (!response.ok) { setMessage(data.error || "保存成绩失败"); return; } setMessage(status === "completed" ? "成绩已确认完成" : "成绩草稿已保存"); load(); };
  const live = useMemo(() => { const scores = results.map((item) => Number(item.score)).filter((value) => Number.isFinite(value) && value >= 0); return scores.length ? { average: Math.round(scores.reduce((sum, value) => sum + value, 0) / scores.length * 10) / 10, highest: Math.max(...scores), lowest: Math.min(...scores), count: scores.length } : { average: null, highest: null, lowest: null, count: 0 }; }, [results]);
  if (!assessment) return <AppShell title="测验成绩"><EmptyState title={message ? "无法打开测验" : "正在读取测验"} description={message || "请稍候…"} action={message ? <button className="secondaryButton" onClick={load}>重新读取</button> : undefined} /></AppShell>;
  return <AppShell title={assessment.title} subtitle={`${assessment.className} · ${assessment.type} · 总分 ${assessment.totalScore}`} actions={<><a className="secondaryButton" href={`/api/exports/assessments?assessmentId=${id}`}>导出本次成绩</a><button className="primaryButton" disabled={saving} onClick={() => save("completed")}>{saving ? "正在保存…" : "确认全部成绩"}</button></>}>
    {message && <div className="saveToast" role="status">{message}</div>}
    {live.count > 0 && live.count < 3 && <div className="noticeStrip"><b>当前仅录入 {live.count} 名学生</b><span>样本不足，暂不展示班级排名或趋势判断；继续录入后再用于学情分析。</span></div>}
    <section className="assessmentSummary"><article><span>已录人数</span><b>{live.count}</b></article><article><span>平均分</span><b>{live.average ?? "—"}</b></article><article><span>最高分</span><b>{live.highest ?? "—"}</b></article><article><span>最低分</span><b>{live.lowest ?? "—"}</b></article><article><span>平均得分率</span><b>{live.average == null ? "—" : `${Math.round(live.average / Number(assessment.totalScore) * 1000) / 10}%`}</b></article></section>
    {stats.weakKnowledge?.length > 0 && <section className="panel weakSummary"><div className="panelTitle"><div><p>基于教师录入</p><h2>班级共性薄弱知识点</h2></div></div><div>{stats.weakKnowledge.map((item: any) => <span key={item.name}>{item.name} · {item.count}人</span>)}</div></section>}
    <section className="panel scoreEntry"><div className="panelTitle"><div><p>批量录入</p><h2>学生成绩</h2></div><div className="saveState" role="status">{saving?"正在保存…":dirty?"有未保存修改":"全部已保存"}</div><button className="secondaryButton" disabled={!dirty || saving} onClick={() => save("draft")}>保存草稿</button></div>{results.length === 0 ? <EmptyState title="班级暂无学生" description="请先将学生加入班级，再录入成绩。" /> : <div className="scoreTable"><header><b>学生</b><b>总分</b><b>客观题</b><b>主观题</b><b>薄弱知识点</b><b>教师备注</b></header>{results.map((row) => <article key={row.studentId}><div><b>{row.name}</b><span>{row.grade}</span></div>{["score", "objectiveScore", "subjectiveScore"].map((key) => <input key={key} aria-label={`${row.name}${key}`} type="number" min="0" max={assessment.totalScore} value={row[key] ?? ""} onChange={(event) => set(row.studentId, key, event.target.value)} />)}<input value={row.weakKnowledge || ""} onChange={(event) => set(row.studentId, "weakKnowledge", event.target.value)} placeholder="如：人民代表大会制度" /><input value={row.teacherNote || ""} onChange={(event) => set(row.studentId, "teacherNote", event.target.value)} placeholder="仅教师可见" /></article>)}</div>}</section>
  </AppShell>;
}
