import {env} from "cloudflare:workers";
import {isDenied,requirePermission} from "../../lib/access";
export async function GET(request:Request){const access=await requirePermission("analytics:read");if(isDenied(access))return access;const range=new URL(request.url).searchParams.get("range")||"week",days=range==="week"?7:range==="month"?30:180,start=new Date(Date.now()-days*86400000).toISOString().slice(0,10),db=env.DB,r=await db.batch([
 db.prepare("SELECT COUNT(*) AS total,SUM(CASE WHEN status='completed' THEN 1 ELSE 0 END) AS completed,SUM(CASE WHEN teaching_goals!='' AND key_points!='' THEN 1 ELSE 0 END) AS prepared FROM lessons WHERE date>=?").bind(start),
 db.prepare("SELECT COUNT(*) AS total,SUM(CASE WHEN f.status='confirmed' THEN 1 ELSE 0 END) AS confirmed,SUM(CASE WHEN f.status='confirmed' AND l.id IS NOT NULL AND julianday(f.confirmed_at)-julianday(l.date)<=2 THEN 1 ELSE 0 END) AS timely FROM feedback f LEFT JOIN lessons l ON l.id=f.lesson_id WHERE COALESCE(l.date,substr(f.created_at,1,10))>=?").bind(start),
 db.prepare("SELECT COUNT(*) AS total,SUM(CASE WHEN a.status='present' THEN 1 ELSE 0 END) AS done FROM attendance a JOIN lessons l ON l.id=a.lesson_id WHERE l.date>=?").bind(start),
 db.prepare("SELECT COUNT(*) AS total,SUM(CASE WHEN s.status='completed' THEN 1 ELSE 0 END) AS done FROM assignment_submissions s JOIN assignments a ON a.id=s.assignment_id JOIN lessons l ON l.id=a.lesson_id WHERE l.date>=?").bind(start),
 db.prepare("SELECT AVG(r.score) AS average,COUNT(*) AS total FROM assessment_results r JOIN assessments a ON a.id=r.assessment_id WHERE a.date>=?").bind(start),
 db.prepare("SELECT COUNT(*) AS total,SUM(CASE WHEN knowledge_points!='' THEN 1 ELSE 0 END) AS covered FROM questions WHERE status='active'"),
 db.prepare("SELECT difficulty,COUNT(*) AS count FROM questions WHERE status='active' GROUP BY difficulty ORDER BY difficulty"),
 db.prepare("SELECT COUNT(*) AS total,SUM(CASE WHEN action_completed=1 THEN 1 ELSE 0 END) AS completed,SUM(CASE WHEN is_strategy=1 THEN 1 ELSE 0 END) AS strategies FROM reflections WHERE date>=?").bind(start),
 db.prepare("SELECT l.date,AVG(r.participation) AS participation,AVG(r.understanding) AS understanding FROM student_lesson_records r JOIN lessons l ON l.id=r.lesson_id WHERE l.date>=? GROUP BY l.date ORDER BY l.date").bind(start),
 db.prepare("SELECT difficulties,COUNT(*) AS count FROM reflections WHERE date>=? AND difficulties!='' GROUP BY difficulties HAVING COUNT(*)>1 ORDER BY count DESC LIMIT 5").bind(start),
 db.prepare("SELECT l.date,COUNT(*) AS total,SUM(CASE WHEN s.status='completed' THEN 1 ELSE 0 END) AS completed FROM assignment_submissions s JOIN assignments a ON a.id=s.assignment_id JOIN lessons l ON l.id=a.lesson_id WHERE l.date>=? GROUP BY l.date ORDER BY l.date").bind(start),
 db.prepare("SELECT knowledge_mastery AS mastery,COUNT(*) AS count FROM assessment_results r JOIN assessments a ON a.id=r.assessment_id WHERE a.date>=? AND knowledge_mastery!='' GROUP BY knowledge_mastery ORDER BY count DESC LIMIT 8").bind(start),
 db.prepare("SELECT id,substr(stem,1,80) AS stem,use_count AS useCount FROM questions WHERE status='active' AND use_count>0 ORDER BY use_count DESC,updated_at DESC LIMIT 5"),
 ]);const row=(i:number)=>r[i].results[0] as Record<string,any>||{},rate=(i:number,a="done",b="total")=>Number(row(i)[b])?Math.round(Number(row(i)[a]||0)/Number(row(i)[b])*100):null;return Response.json({range,start,teaching:{lessons:Number(row(0).total||0),completedRate:rate(0,"completed"),prepRate:rate(0,"prepared"),feedbackRate:rate(1,"timely")},classroom:{attendanceRate:rate(2),homeworkRate:rate(3),assessmentAverage:row(4).total?Math.round(Number(row(4).average||0)*10)/10:null,assessmentCount:Number(row(4).total||0),knowledgeMastery:r[11].results},questionBank:{total:Number(row(5).total||0),coverageRate:rate(5,"covered"),difficulty:r[6].results,frequent:r[12].results},growth:{reflections:Number(row(7).total||0),actionRate:rate(7,"completed"),strategies:Number(row(7).strategies||0),repeatedProblems:r[9].results},studentTrend:r[8].results,homeworkTrend:r[10].results});}
