"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { AppShell, EmptyState } from "./components/AppShell";
import ResourcesPage from "./resources/page";
type D={weekLessons:number;draftLessons:number;confirmedFeedback:number;pendingFeedback:number;attendanceRate:number|null;homeworkRate:number|null;pendingHomework:number;riskCount:number;pendingReview:number;reviewIssues:{missingAnswer:number;missingAnalysis:number;missingClassification:number;lowConfidence:number};activeClasses:number;activeStudents:number;todayLessons:Array<Record<string,unknown>>;riskStudents:Array<Record<string,unknown>>;recentReflections:Array<Record<string,unknown>>;recentQuestions:Array<Record<string,unknown>>};
const empty:D={weekLessons:0,draftLessons:0,confirmedFeedback:0,pendingFeedback:0,attendanceRate:null,homeworkRate:null,pendingHomework:0,riskCount:0,pendingReview:0,reviewIssues:{missingAnswer:0,missingAnalysis:0,missingClassification:0,lowConfidence:0},activeClasses:0,activeStudents:0,todayLessons:[],riskStudents:[],recentReflections:[],recentQuestions:[]};
export function Dashboard(){const [d,setD]=useState<D>(empty),[loading,setLoading]=useState(true),[guideHidden,setGuideHidden]=useState(false);useEffect(()=>{setGuideHidden(localStorage.getItem("zhishi:onboarding-hidden")==="1");fetch("/api/dashboard").then(r=>r.ok?r.json():empty).then(setD).catch(()=>setD(empty)).finally(()=>setLoading(false))},[]);const metrics=[["本周课时",d.weekLessons,"按本周起始日至今天"],["进行中班级",d.activeClasses,"当前可用教学班级"],["学生档案",d.activeStudents,"当前可用学生档案"],["待复核题目",d.pendingReview,"Word 导入后需要人工确认"],["学生出勤率",d.attendanceRate==null?"—":`${d.attendanceRate}%`,d.attendanceRate==null?"数据不足":"按已记录出勤计算"],["作业完成率",d.homeworkRate==null?"—":`${d.homeworkRate}%`,d.homeworkRate==null?"数据不足":"按已提交作业计算"]],guide=[{label:"建立班级",done:d.activeClasses>0,href:"/classes"},{label:"录入学生",done:d.activeStudents>0,href:"/students?new=1"},{label:"安排第一节课",done:d.weekLessons>0,href:"/lessons?new=1"},{label:"处理待校对题目",done:d.pendingReview===0,href:"/questions?status=review"},{label:"创建第一份试卷",done:false,href:"/papers"}];return <AppShell title="工作台" subtitle="今天也从一节认真准备的课开始。" actions={<Link href="/lessons?new=1" className="primaryButton">＋ 新建课时</Link>}>
 {loading?<div className="noticeStrip"><b>正在读取真实教学数据…</b></div>:!guideHidden&&<section className="panel onboardingChecklist"><div className="panelTitle"><div><p>首次使用</p><h2>建立您的日常教学闭环</h2></div><button aria-label="关闭首次使用引导" onClick={()=>{localStorage.setItem("zhishi:onboarding-hidden","1");setGuideHidden(true)}}>暂时隐藏</button></div><div>{guide.map((item,index)=><Link className={item.done?"done":""} href={item.href} key={item.label}><b>{item.done?"✓":index+1}</b><span>{item.label}</span><em>{item.done?"已完成":"去完成"}</em></Link>)}</div></section>}
 <div className="metricGrid">{metrics.map(([label,value,note])=><article className="metricCard" key={String(label)}><span>{label}</span><b>{value}</b><small>{note}</small></article>)}</div>
 <div className="dashboardGrid"><section className="panel span2"><div className="panelTitle"><div><p>今日课程</p><h2>课程安排</h2></div><Link href="/lessons">查看全部</Link></div>{d.todayLessons.length===0?<EmptyState title="今天还没有课程" description="新建课时并选择今天的日期后，会在这里显示时间、班级、课题、地点和备课状态。" action={<Link className="secondaryButton" href="/lessons?new=1">新建今日课时</Link>}/>:<div className="todayList">{d.todayLessons.map(x=><article key={String(x.id)}><time>{String(x.startTime||"待定")}</time><div><b>{String(x.topic||x.courseName)}</b><span>{String(x.className||"未关联班级")} · {x.mode==="online"?"线上":String(x.location||"线下地点待定")}</span></div><span className={`statusBadge ${x.status}`}>{x.status==="completed"?"已完成":"备课中"}</span><Link href={`/lessons/${x.id}`}>开始记录</Link></article>)}</div>}</section>
 <section className="panel"><div className="panelTitle"><div><p>行动清单</p><h2>待办事项</h2></div></div><ul className="todoList"><li><span>待处理课时</span><b>{d.draftLessons}</b></li><li><span>待确认反馈</span><b>{d.pendingFeedback}</b></li><li><span>待批改作业</span><b>{d.pendingHomework}</b></li><li><span>待复核导入题目</span><b>{d.pendingReview}</b></li><li><span>待跟进学生</span><b>{d.riskCount}</b></li></ul></section>
 <section className="panel"><div className="panelTitle"><div><p>教师确认</p><h2>重点关注学生</h2></div></div>{d.riskStudents.length===0?<EmptyState title="暂无需关注项" description="风险标签必须由教师确认；系统不会自动给学生作评价性结论。"/>:<div className="riskList">{d.riskStudents.map(x=><Link href={`/students/${x.id}`} key={String(x.id)}><b>{String(x.name)}</b><span>{String(x.grade||"")} · {String(x.riskTags||"需关注")}</span></Link>)}</div>}</section>
 <section className="panel span2"><div className="panelTitle"><div><p>常用操作</p><h2>快捷入口</h2></div></div><div className="quickGrid"><Link href="/lessons?new=1"><b>＋</b><span>新建课时</span></Link><Link href="/students?new=1"><b>人</b><span>录入学生</span></Link><Link href="/questions?new=1"><b>题</b><span>添加题目</span></Link><Link href="/feedback?new=1"><b>信</b><span>新建反馈</span></Link><Link href="/reflections?new=1"><b>思</b><span>新建反思</span></Link></div></section>
 <section className="panel"><div className="panelTitle"><div><p>题库整理</p><h2>待校对进度</h2></div><Link href="/questions?status=review">进入批量校对</Link></div><div className="reviewProgress"><b>{d.pendingReview}</b><span>道题待处理</span></div><div className="cardActions"><Link href="/questions?status=review&issue=missing_answer">缺答案 {d.reviewIssues.missingAnswer}</Link><Link href="/questions?status=review&issue=missing_analysis">缺解析 {d.reviewIssues.missingAnalysis}</Link><Link href="/questions?status=review&issue=classification">分类不完整 {d.reviewIssues.missingClassification}</Link><Link href="/questions?status=review&issue=low_confidence">低置信度 {d.reviewIssues.lowConfidence}</Link></div></section>
 <section className="panel"><div className="panelTitle"><div><p>近期动态</p><h2>教学反思与题库</h2></div></div>{d.recentReflections.length===0&&d.recentQuestions.length===0?<EmptyState title="还没有动态" description="记录反思或导入题目后，这里会显示最近更新。"/>:<div className="activityFeed">{d.recentReflections.map(x=><Link href="/reflections" key={`r-${x.id}`}><span>反思</span><b>{String(x.topic||"教学复盘")}</b><p>{String(x.summary||"已保存私密反思")}</p></Link>)}{d.recentQuestions.map(x=><Link href="/questions" key={`q-${x.id}`}><span>题库</span><b>{x.status==="active"?"正式题目":"待校对题目"}</b><p>{String(x.stem||"")}</p></Link>)}</div>}</section></div></AppShell>}

export default function PublicHome() { return <ResourcesPage />; }
