"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { AppShell, EmptyState } from "./components/AppShell";
type D={weekLessons:number;draftLessons:number;confirmedFeedback:number;attendanceRate:number|null;homeworkRate:number|null;pendingHomework:number;riskCount:number;todayLessons:Array<Record<string,unknown>>;riskStudents:Array<Record<string,unknown>>};
const empty:D={weekLessons:0,draftLessons:0,confirmedFeedback:0,attendanceRate:null,homeworkRate:null,pendingHomework:0,riskCount:0,todayLessons:[],riskStudents:[]};
export default function Dashboard(){const [d,setD]=useState<D>(empty),[loading,setLoading]=useState(true);useEffect(()=>{fetch("/api/dashboard").then(r=>r.json()).then(setD).finally(()=>setLoading(false))},[]);const metrics=[["本周课时",d.weekLessons,"按本周起始日至今天"],["已完成反馈",d.confirmedFeedback,"本周已确认反馈"],["学生出勤率",d.attendanceRate==null?"—":`${d.attendanceRate}%`,d.attendanceRate==null?"数据不足":"按已记录出勤计算"],["作业完成率",d.homeworkRate==null?"—":`${d.homeworkRate}%`,d.homeworkRate==null?"数据不足":"按已提交作业计算"]];return <AppShell title="工作台" subtitle="今天也从一节认真准备的课开始。" actions={<Link href="/lessons?new=1" className="primaryButton">＋ 新建课时</Link>}>
 {loading?<div className="noticeStrip"><b>正在读取真实教学数据…</b></div>:d.weekLessons===0&&<div className="noticeStrip"><b>开始建立您的真实教学记录</b><span>目前没有本周课时数据。录入后，工作台会自动生成待办与统计。</span><Link href="/classes">先创建班级 →</Link></div>}
 <div className="metricGrid">{metrics.map(([label,value,note])=><article className="metricCard" key={String(label)}><span>{label}</span><b>{value}</b><small>{note}</small></article>)}</div>
 <div className="dashboardGrid"><section className="panel span2"><div className="panelTitle"><div><p>今日课程</p><h2>课程安排</h2></div><Link href="/lessons">查看全部</Link></div>{d.todayLessons.length===0?<EmptyState title="今天还没有课程" description="新建课时并选择今天的日期后，会在这里显示时间、班级、课题、地点和备课状态。" action={<Link className="secondaryButton" href="/lessons?new=1">新建今日课时</Link>}/>:<div className="todayList">{d.todayLessons.map(x=><article key={String(x.id)}><time>{String(x.startTime||"待定")}</time><div><b>{String(x.topic||x.courseName)}</b><span>{String(x.className||"未关联班级")} · {x.mode==="online"?"线上":String(x.location||"线下地点待定")}</span></div><span className={`statusBadge ${x.status}`}>{x.status==="completed"?"已完成":"备课中"}</span><Link href={`/lessons/${x.id}`}>开始记录</Link></article>)}</div>}</section>
 <section className="panel"><div className="panelTitle"><div><p>行动清单</p><h2>待办事项</h2></div></div><ul className="todoList"><li><span>待补课时记录</span><b>{d.draftLessons}</b></li><li><span>待发送反馈</span><b>0</b></li><li><span>待批改作业</span><b>{d.pendingHomework}</b></li><li><span>待跟进学生</span><b>{d.riskCount}</b></li></ul></section>
 <section className="panel"><div className="panelTitle"><div><p>教师确认</p><h2>重点关注学生</h2></div></div>{d.riskStudents.length===0?<EmptyState title="暂无需关注项" description="风险标签必须由教师确认；系统不会自动给学生作评价性结论。"/>:<div className="riskList">{d.riskStudents.map(x=><Link href={`/students/${x.id}`} key={String(x.id)}><b>{String(x.name)}</b><span>{String(x.grade||"")} · {String(x.riskTags||"需关注")}</span></Link>)}</div>}</section>
 <section className="panel span2"><div className="panelTitle"><div><p>常用操作</p><h2>快捷入口</h2></div></div><div className="quickGrid"><Link href="/lessons?new=1"><b>＋</b><span>新建课时</span></Link><Link href="/students?new=1"><b>人</b><span>录入学生</span></Link><Link href="/questions?new=1"><b>题</b><span>添加题目</span></Link><Link href="/feedback?new=1"><b>信</b><span>新建反馈</span></Link><Link href="/reflections?new=1"><b>思</b><span>新建反思</span></Link></div></section>
 <section className="panel"><div className="panelTitle"><div><p>近期动态</p><h2>教学反思与题库</h2></div></div><EmptyState title="还没有动态" description="记录反思或导入题目后，这里会显示最近更新。"/></section></div></AppShell>}
