import { and, eq } from "drizzle-orm";
import { getDb } from "../../../../../db";
import { lessonQuestions, questions } from "../../../../../db/schema";
import { audit, isDenied, requireLessonAccess, requirePermission } from "../../../../lib/access";

const idFrom = async (context: { params: Promise<{ id: string }> }) => Number((await context.params).id);

export async function GET(_: Request, context: { params: Promise<{ id: string }> }) { const access = await requirePermission("lessons:read"); if (isDenied(access)) return access; const id = await idFrom(context), denied = await requireLessonAccess(access, id); if (denied) return denied; const rows = await getDb().select({ id: questions.id, stem: questions.stem, questionType: questions.questionType, difficulty: questions.difficulty, score: questions.score, purpose: lessonQuestions.purpose }).from(lessonQuestions).innerJoin(questions, eq(questions.id, lessonQuestions.questionId)).where(eq(lessonQuestions.lessonId, id)); return Response.json({ questions: rows }); }
export async function POST(request: Request, context: { params: Promise<{ id: string }> }) { const access = await requirePermission("lessons:write"); if (isDenied(access)) return access; const id = await idFrom(context), denied = await requireLessonAccess(access, id); if (denied) return denied; const payload = await request.json() as { questionId: number; purpose?: string }, questionId = Number(payload.questionId), question = await getDb().select({ id: questions.id, status: questions.status }).from(questions).where(eq(questions.id, questionId)).limit(1); if (!question[0] || question[0].status !== "active") return Response.json({ error: "只能关联正式题库中的题目" }, { status: 400 }); await getDb().insert(lessonQuestions).values({ lessonId: id, questionId, purpose: payload.purpose || "课堂练习" }).onConflictDoNothing(); await audit(access, "link", "lesson_question", `${id}:${questionId}`); return Response.json({ ok: true }); }
export async function DELETE(request: Request, context: { params: Promise<{ id: string }> }) { const access = await requirePermission("lessons:write"); if (isDenied(access)) return access; const id = await idFrom(context), denied = await requireLessonAccess(access, id); if (denied) return denied; const payload = await request.json() as { questionId: number }; await getDb().delete(lessonQuestions).where(and(eq(lessonQuestions.lessonId, id), eq(lessonQuestions.questionId, Number(payload.questionId)))); await audit(access, "unlink", "lesson_question", `${id}:${payload.questionId}`); return Response.json({ ok: true }); }
