"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AppShell, EmptyState } from "../components/AppShell";

type Lesson=Record<string, string|number|null> & {id:number;date:string;courseName:string;stage:string;grade:string;status:string};
type ClassRow={id:number;name:string};
const blank=()=>({classId:"",date:new Date().toISOString().slice(0,10),startTime:"",endTime:"",courseName:"思想政治辅导",stage:"高中",grade:"高一",mode:"offline",location:"",onlineLink:"",textbookVersion:"统编版",volume:"必修三",unit:"",topic:"",teachingGoals:"",keyPoints:"",difficultPoints:"",actualContent:"",materials:"",activities:"",homework:"",nextPlan:"",participation:"",understanding:"",completion:"",discipline:"",status:"draft"});
const fields=["date","startTime","endTime","courseName","stage","grade","mode","location","onlineLink","textbookVersion","volume","unit","topic","teachingGoals","keyPoints","difficultPoints","actualContent","materials","activities","homework","nextPlan","participation","understanding","completion","discipline","status","classId"];

export default function LessonsPage(){
 const [items,setItems]=useState<Lesson[]>([]),[classes,setClasses]=useState<ClassRow[]>([]),[form,setForm]=useState<Record<string,string>>(blank()),[open,setOpen]=useState(false),[editing,setEditing]=useState<number|null>(null),[q,setQ]=useState(""),[status,setStatus]=useState("all"),[stage,setStage]=useState("all"),[error,setError]=useState("");
 const load=async()=>{try{const [lr,cr]=await Promise.all([fetch(`/api/lessons?q=${encodeURIComponent(q)}`),fetch("/api/classes")]);const ld=await lr.json(),cd=await cr.json();setItems(ld.lessons||[]);setClasses(cd.classes||[])}catch{setError("暂时无法读取课时，请稍后重试")}};
 const edit=(row?:Lesson)=>{setEditing(row?.id||null);const next:Record<string,string>=blank();if(row)for(const k of fields)next[k]=row[k]==null?"":String(row[k]);setForm(next);setOpen(true)};
 useEffect(()=>{load()},[]);
 useEffect(()=>{const s=new URLSearchParams(location.search),editId=s.get("edit"),classId=s.get("class");if(editId)fetch(`/api/lessons/${editId}`).then(r=>r.json()).then(d=>d.lesson&&edit(d.lesson));else if(s.get("new")==="1"){const next=blank();if(classId)next.classId=classId;setForm(next);setOpen(true)}},[]);
 const shown=useMemo(()=>items.filter(x=>(status==="all"||x.status===status)&&(stage==="all"||x.stage===stage)),[items,status,stage]);
 const save=async(nextStatus:string)=>{setError("");const url=editing?`/api/lessons/${editing}`:"/api/lessons",method=editing?"PUT":"POST";const r=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,status:nextStatus})});if(!r.ok){setError((await r.json()).error||"保存失败");return}setOpen(false);setEditing(null);setForm(blank());load()};
 const remove=async(id:number)=>{if(!confirm("确认删除这条课时记录？删除后不可恢复。"))return;await fetch(`/api/lessons/${id}`,{method:"DELETE"});load()};
 const duplicate=(row:Lesson)=>{const copy={...row,id:0,date:new Date().toISOString().slice(0,10),status:"draft"} as Lesson;edit(copy)};
 const set=(key:string,value:string)=>setForm({...form,[key]:value});
 return <AppShell title="课时记录" subtitle="课程—课时—学生表现—反馈闭环" actions={<button className="primaryButton" onClick={()=>edit()}>＋ 新建课时</button>}>
  <div className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="搜索课程或课题"/><button onClick={load}>搜索</button><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">全部状态</option><option value="draft">草稿</option><option value="completed">已完成</option></select><select value={stage} onChange={e=>setStage(e.target.value)}><option value="all">全部学段</option><option>初中</option><option>高中</option></select></div>
  {error&&<p className="formError">{error}</p>}
  <section className="panel tablePanel">{shown.length===0?<EmptyState title="没有符合条件的课时" description="调整筛选条件，或创建一节真实课程。" action={<button className="secondaryButton" onClick={()=>edit()}>新建第一节课</button>}/>:<div className="recordList">{shown.map(x=><article key={x.id}><div className="dateBlock"><b>{x.date.slice(8)}</b><span>{x.date.slice(0,7)}</span></div><div className="recordInfo"><span className={`statusBadge ${x.status}`}>{x.status==="completed"?"已完成":"草稿"}</span><h3><Link href={`/lessons/${x.id}`}>{x.courseName} · {String(x.topic||"未填写课题")}</Link></h3><p>{String(x.startTime||"待定")}–{String(x.endTime||"待定")}　{x.grade}　{x.mode==="online"?"线上":String(x.location||"线下")}</p></div><div className="rowActions"><Link href={`/lessons/${x.id}`}>详情</Link><button onClick={()=>duplicate(x)}>复制</button><button onClick={()=>edit(x)}>编辑</button><button onClick={()=>remove(x.id)}>删除</button></div></article>)}</div>}</section>
  {open&&<div className="modalBackdrop"><div className="lessonModal"><div className="modalTitle"><div><p>{editing?"编辑课时":"新建课时"}</p><h2>记录一节政治课</h2></div><button aria-label="关闭" onClick={()=>setOpen(false)}>×</button></div><div className="formGrid">
   <label>日期<input type="date" value={form.date} onChange={e=>set("date",e.target.value)}/></label><label>所属班级<select value={form.classId} onChange={e=>set("classId",e.target.value)}><option value="">暂不关联班级</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
   <label>开始时间<input type="time" value={form.startTime} onChange={e=>set("startTime",e.target.value)}/></label><label>结束时间<input type="time" value={form.endTime} onChange={e=>set("endTime",e.target.value)}/></label><label>课程名称<input value={form.courseName} onChange={e=>set("courseName",e.target.value)}/></label><label>授课方式<select value={form.mode} onChange={e=>set("mode",e.target.value)}><option value="offline">线下</option><option value="online">线上</option></select></label>
   <label>学段<select value={form.stage} onChange={e=>set("stage",e.target.value)}><option>初中</option><option>高中</option></select></label><label>年级<select value={form.grade} onChange={e=>set("grade",e.target.value)}><option>七年级</option><option>八年级</option><option>九年级</option><option>高一</option><option>高二</option><option>高三</option></select></label>
   <label>教材版本<input value={form.textbookVersion} onChange={e=>set("textbookVersion",e.target.value)}/></label><label>册别/模块<input value={form.volume} onChange={e=>set("volume",e.target.value)}/></label><label>单元<input value={form.unit} onChange={e=>set("unit",e.target.value)}/></label><label>课题<input value={form.topic} onChange={e=>set("topic",e.target.value)}/></label>
   <label>线下地点<input value={form.location} onChange={e=>set("location",e.target.value)}/></label><label>线上链接<input value={form.onlineLink} onChange={e=>set("onlineLink",e.target.value)}/></label>
   <label className="wide">教学目标<textarea value={form.teachingGoals} onChange={e=>set("teachingGoals",e.target.value)}/></label><label>教学重点<textarea value={form.keyPoints} onChange={e=>set("keyPoints",e.target.value)}/></label><label>教学难点<textarea value={form.difficultPoints} onChange={e=>set("difficultPoints",e.target.value)}/></label>
   <label className="wide">实际教学内容<textarea value={form.actualContent} onChange={e=>set("actualContent",e.target.value)}/></label><label>使用资料<textarea value={form.materials} onChange={e=>set("materials",e.target.value)}/></label><label>课堂活动<textarea value={form.activities} onChange={e=>set("activities",e.target.value)}/></label><label>布置作业<textarea value={form.homework} onChange={e=>set("homework",e.target.value)}/></label><label>下次课计划<textarea value={form.nextPlan} onChange={e=>set("nextPlan",e.target.value)}/></label>
   <div className="wide ratingGrid">{[["participation","参与度"],["understanding","理解度"],["completion","完成度"],["discipline","课堂纪律"]].map(([k,l])=><label key={k}>{l}<select value={form[k]} onChange={e=>set(k,e.target.value)}><option value="">待评</option>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label>)}</div>
  </div><div className="modalActions"><button onClick={()=>save("draft")}>保存草稿</button><button className="primaryButton" onClick={()=>save("completed")}>完成课时</button></div></div></div>}
 </AppShell>;
}
