import { sql } from "drizzle-orm";
import { integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const timestamps = { createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) };

export const users = sqliteTable("users", { id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull(), email: text("email").unique(), status: text("status").notNull().default("active"), ...timestamps });
export const roles = sqliteTable("roles", { id: integer("id").primaryKey({ autoIncrement: true }), code: text("code").notNull().unique(), name: text("name").notNull() });
export const userRoles = sqliteTable("user_roles", { id: integer("id").primaryKey({ autoIncrement: true }), userId: integer("user_id").notNull().references(() => users.id), roleId: integer("role_id").notNull().references(() => roles.id) }, (t) => [uniqueIndex("user_role_unique").on(t.userId, t.roleId)]);

export const classes = sqliteTable("classes", { id: integer("id").primaryKey({ autoIncrement: true }), ownerId: integer("owner_id").references(() => users.id), name: text("name").notNull(), stage: text("stage").notNull(), grade: text("grade").notNull(), courseType: text("course_type"), startDate: text("start_date"), schedule: text("schedule"), notes: text("notes"), status: text("status").notNull().default("active"), archivedAt: text("archived_at"), ...timestamps });
export const students = sqliteTable("students", { id: integer("id").primaryKey({ autoIncrement: true }), userId: integer("user_id").references(() => users.id), guardianUserId: integer("guardian_user_id").references(() => users.id), name: text("name").notNull(), nickname: text("nickname"), grade: text("grade"), school: text("school"), textbookVersion: text("textbook_version"), subjectChoice: text("subject_choice"), examGoal: text("exam_goal"), guardianContact: text("guardian_contact"), foundationLevel: text("foundation_level"), strengths: text("strengths"), weakKnowledge: text("weak_knowledge"), learningHabits: text("learning_habits"), stageGoal: text("stage_goal"), riskTags: text("risk_tags"), riskConfirmed: integer("risk_confirmed", { mode: "boolean" }).notNull().default(false), status: text("status").notNull().default("active"), archivedAt: text("archived_at"), notes: text("notes"), ...timestamps });
export const enrollments = sqliteTable("enrollments", { id: integer("id").primaryKey({ autoIncrement: true }), classId: integer("class_id").notNull().references(() => classes.id), studentId: integer("student_id").notNull().references(() => students.id), joinedAt: text("joined_at").default(sql`CURRENT_TIMESTAMP`), status: text("status").notNull().default("active") }, (t) => [uniqueIndex("enrollment_unique").on(t.classId, t.studentId)]);
export const staffClassAccess = sqliteTable("staff_class_access", { id: integer("id").primaryKey({ autoIncrement: true }), userId: integer("user_id").notNull().references(() => users.id), classId: integer("class_id").notNull().references(() => classes.id), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, (t) => [uniqueIndex("staff_class_access_unique").on(t.userId, t.classId)]);

export const courses = sqliteTable("courses", { id: integer("id").primaryKey({ autoIncrement: true }), classId: integer("class_id").references(() => classes.id), name: text("name").notNull(), stage: text("stage"), grade: text("grade"), textbookVersion: text("textbook_version"), volume: text("volume"), ...timestamps });
export const lessons = sqliteTable("lessons", { id: integer("id").primaryKey({ autoIncrement: true }), courseId: integer("course_id").references(() => courses.id), classId: integer("class_id").references(() => classes.id), date: text("date").notNull(), startTime: text("start_time"), endTime: text("end_time"), mode: text("mode").notNull().default("offline"), location: text("location"), onlineLink: text("online_link"), courseName: text("course_name").notNull(), stage: text("stage").notNull(), grade: text("grade").notNull(), textbookVersion: text("textbook_version"), volume: text("volume"), unit: text("unit"), topic: text("topic"), teachingGoals: text("teaching_goals"), keyPoints: text("key_points"), difficultPoints: text("difficult_points"), actualContent: text("actual_content"), materials: text("materials"), activities: text("activities"), homework: text("homework"), nextPlan: text("next_plan"), participation: integer("participation"), understanding: integer("understanding"), completion: integer("completion"), discipline: integer("discipline"), fee: real("fee"), feeStatus: text("fee_status").notNull().default("untracked"), cancellationReason: text("cancellation_reason"), status: text("status").notNull().default("draft"), ...timestamps });
export const attendance = sqliteTable("attendance", { id: integer("id").primaryKey({ autoIncrement: true }), lessonId: integer("lesson_id").notNull().references(() => lessons.id), studentId: integer("student_id").notNull().references(() => students.id), status: text("status").notNull(), notes: text("notes") }, (t) => [uniqueIndex("attendance_lesson_student_unique").on(t.lessonId,t.studentId)]);
export const studentLessonRecords = sqliteTable("student_lesson_records", { id: integer("id").primaryKey({ autoIncrement: true }), lessonId: integer("lesson_id").notNull().references(() => lessons.id), studentId: integer("student_id").notNull().references(() => students.id), participation: integer("participation"), understanding: integer("understanding"), completion: integer("completion"), teacherNote: text("teacher_note"), riskTags: text("risk_tags"), riskConfirmed: integer("risk_confirmed", { mode: "boolean" }).notNull().default(false), ...timestamps }, (t) => [uniqueIndex("student_lesson_unique").on(t.lessonId,t.studentId)]);

export const assignments = sqliteTable("assignments", { id: integer("id").primaryKey({ autoIncrement: true }), lessonId: integer("lesson_id").references(() => lessons.id), title: text("title").notNull(), requirements: text("requirements"), dueAt: text("due_at"), ...timestamps });
export const assignmentSubmissions = sqliteTable("assignment_submissions", { id: integer("id").primaryKey({ autoIncrement: true }), assignmentId: integer("assignment_id").notNull().references(() => assignments.id), studentId: integer("student_id").notNull().references(() => students.id), status: text("status").notNull().default("pending"), score: real("score"), teacherNote: text("teacher_note"), submittedAt: text("submitted_at"), ...timestamps });

export const questionSets = sqliteTable("question_sets", { id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull(), sourceFile: text("source_file"), sourceFingerprint: text("source_fingerprint"), sourceDocument: text("source_document"), importReport: text("import_report"), parseStage: text("parse_stage").notNull().default("review"), failureReason: text("failure_reason"), reviewProgress: integer("review_progress").notNull().default(0), duplicateReport: text("duplicate_report"), status: text("status").notNull().default("review"), ...timestamps });
export const questions = sqliteTable("questions", { id: integer("id").primaryKey({ autoIncrement: true }), questionSetId: integer("question_set_id").references(() => questionSets.id), parentId: integer("parent_id"), questionGroup: text("question_group"), subQuestions: text("sub_questions"), scoringPoints: text("scoring_points"), attachments: text("attachments"), tables: text("tables"), parseConfidence: real("parse_confidence"), reviewStatus: text("review_status").notNull().default("pending"), sourceDocumentId: integer("source_document_id"), stem: text("stem").notNull(), material: text("material"), options: text("options"), answer: text("answer"), answerPoints: text("answer_points"), analysis: text("analysis"), factBasis: text("fact_basis"), textbookView: text("textbook_view"), valueJudgment: text("value_judgment"), answerLogic: text("answer_logic"), standardExpression: text("standard_expression"), questionType: text("question_type").notNull(), difficulty: integer("difficulty"), score: real("score"), stage: text("stage"), grade: text("grade"), textbookVersion: text("textbook_version"), volume: text("volume"), unit: text("unit"), topic: text("topic"), knowledgePoints: text("knowledge_points"), secondaryKnowledge: text("secondary_knowledge"), coreCompetencies: text("core_competencies"), abilityLevel: text("ability_level"), source: text("source"), sourceFile: text("source_file"), year: integer("year"), region: text("region"), examType: text("exam_type"), scenario: text("scenario"), fingerprint: text("fingerprint"), reviewed: integer("reviewed", { mode: "boolean" }).notNull().default(false), isOriginal: integer("is_original", { mode: "boolean" }).notNull().default(false), isFavorite: integer("is_favorite", { mode: "boolean" }).notNull().default(false), isWrong: integer("is_wrong", { mode: "boolean" }).notNull().default(false), isFrequent: integer("is_frequent", { mode: "boolean" }).notNull().default(false), tags: text("tags"), recordedBy: text("recorded_by"), useCount: integer("use_count").notNull().default(0), status: text("status").notNull().default("review"), notes: text("notes"), ...timestamps });
export const wrongQuestions = sqliteTable("wrong_questions", { id: integer("id").primaryKey({ autoIncrement: true }), studentId: integer("student_id").notNull().references(() => students.id), questionId: integer("question_id").notNull().references(() => questions.id), lessonId: integer("lesson_id").references(() => lessons.id), incorrectAnswer: text("incorrect_answer"), reason: text("reason"), status: text("status").notNull().default("active"), occurredAt: text("occurred_at").notNull().default(sql`CURRENT_TIMESTAMP`), masteredAt: text("mastered_at"), ...timestamps }, (t) => [uniqueIndex("wrong_question_student_question_lesson_unique").on(t.studentId, t.questionId, t.lessonId), uniqueIndex("wrong_question_student_status_index").on(t.studentId, t.status)]);
export const papers = sqliteTable("papers", { id: integer("id").primaryKey({ autoIncrement: true }), title: text("title").notNull(), type: text("type").notNull(), stage: text("stage"), grade: text("grade"), textbookVersion: text("textbook_version"), durationMinutes: integer("duration_minutes"), instructions: text("instructions"), totalScore: real("total_score"), status: text("status").notNull().default("draft"), ...timestamps });
export const paperQuestions = sqliteTable("paper_questions", { id: integer("id").primaryKey({ autoIncrement: true }), paperId: integer("paper_id").notNull().references(() => papers.id), questionId: integer("question_id").notNull().references(() => questions.id), position: integer("position").notNull(), score: real("score"), groupTitle: text("group_title"), answerSpace: integer("answer_space").notNull().default(2) });
export const exportJobs = sqliteTable("export_jobs", { id: text("id").primaryKey(), paperId: integer("paper_id").notNull().references(() => papers.id), format: text("format").notNull(), mode: text("mode").notNull(), status: text("status").notNull().default("queued"), resultKey: text("result_key"), error: text("error"), createdBy: integer("created_by").references(() => users.id), ...timestamps });
export const lessonQuestions = sqliteTable("lesson_questions", { id: integer("id").primaryKey({ autoIncrement: true }), lessonId: integer("lesson_id").notNull().references(() => lessons.id), questionId: integer("question_id").notNull().references(() => questions.id), purpose: text("purpose").notNull().default("课堂练习"), position: integer("position").notNull().default(0) }, (t) => [uniqueIndex("lesson_question_unique").on(t.lessonId,t.questionId)]);

export const assessments = sqliteTable("assessments", { id: integer("id").primaryKey({ autoIncrement: true }), classId: integer("class_id").references(() => classes.id), paperId: integer("paper_id").references(() => papers.id), title: text("title").notNull(), date: text("date"), totalScore: real("total_score").notNull().default(100), type: text("type").notNull().default("课堂测验"), status: text("status").notNull().default("draft"), notes: text("notes"), ...timestamps });
export const assessmentResults = sqliteTable("assessment_results", { id: integer("id").primaryKey({ autoIncrement: true }), assessmentId: integer("assessment_id").notNull().references(() => assessments.id), studentId: integer("student_id").notNull().references(() => students.id), score: real("score"), objectiveScore: real("objective_score"), subjectiveScore: real("subjective_score"), knowledgeMastery: text("knowledge_mastery"), weakKnowledge: text("weak_knowledge"), teacherNote: text("teacher_note"), ...timestamps }, (t) => [uniqueIndex("assessment_student_unique").on(t.assessmentId, t.studentId)]);
export const studentMasteryAdjustments = sqliteTable("student_mastery_adjustments", { id: integer("id").primaryKey({ autoIncrement: true }), studentId: integer("student_id").notNull().references(() => students.id), calculatedScore: real("calculated_score"), overrideScore: real("override_score").notNull(), reason: text("reason").notNull(), createdBy: text("created_by").notNull(), ...timestamps });
export const feedback = sqliteTable("feedback", { id: integer("id").primaryKey({ autoIncrement: true }), lessonId: integer("lesson_id").references(() => lessons.id), studentId: integer("student_id").references(() => students.id), classId: integer("class_id").references(() => classes.id), type: text("type").notNull(), tone: text("tone"), content: text("content").notNull(), learningContent: text("learning_content"), highlights: text("highlights"), consolidate: text("consolidate"), homeworkRequirements: text("homework_requirements"), parentAdvice: text("parent_advice"), nextFocus: text("next_focus"), periodStart: text("period_start"), periodEnd: text("period_end"), periodSummary: text("period_summary"), progress: text("progress"), problems: text("problems"), goals: text("goals"), suggestions: text("suggestions"), status: text("status").notNull().default("draft"), confirmedAt: text("confirmed_at"), sentAt: text("sent_at"), ...timestamps });
export const reflections = sqliteTable("reflections", { id: integer("id").primaryKey({ autoIncrement: true }), lessonId: integer("lesson_id").references(() => lessons.id), date: text("date").notNull(), tags: text("tags"), problemType: text("problem_type"), expectedVsActual: text("expected_vs_actual"), effectivePractices: text("effective_practices"), difficulties: text("difficulties"), studentEvidence: text("student_evidence"), nextAction: text("next_action"), actionCompleted: integer("action_completed", { mode: "boolean" }).notNull().default(false), reusableMaterial: text("reusable_material"), isStrategy: integer("is_strategy", { mode: "boolean" }).notNull().default(false), isPrivate: integer("is_private", { mode: "boolean" }).notNull().default(true), ...timestamps });
export const resources = sqliteTable("resources", { id: integer("id").primaryKey({ autoIncrement: true }), ownerId: integer("owner_id").references(() => users.id), title: text("title").notNull(), type: text("type"), url: text("url"), tags: text("tags"), content: text("content"), sourceRef: text("source_ref"), visibility: text("visibility").notNull().default("private"), ...timestamps });
export const auditLogs = sqliteTable("audit_logs", { id: integer("id").primaryKey({ autoIncrement: true }), userId: integer("user_id").references(() => users.id), action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: text("entity_id"), detail: text("detail"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const demoRecords = sqliteTable("demo_records", { id: integer("id").primaryKey({ autoIncrement: true }), runId: text("run_id").notNull(), entityType: text("entity_type").notNull(), entityId: integer("entity_id").notNull(), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const teacherAdminCredentials = sqliteTable("teacher_admin_credentials", { id: integer("id").primaryKey(), passwordSalt: text("password_salt").notNull(), passwordHash: text("password_hash").notNull(), iterations: integer("iterations").notNull().default(210000), sessionVersion: integer("session_version").notNull().default(1), updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const teacherLoginAttempts = sqliteTable("teacher_login_attempts", { key: text("key").primaryKey(), failures: integer("failures").notNull().default(0), blockedUntil: integer("blocked_until"), updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
