import { sql } from "drizzle-orm";
import { integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const timestamps = { createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) };

export const users = sqliteTable("users", { id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull(), email: text("email").unique(), status: text("status").notNull().default("active"), ...timestamps });
export const roles = sqliteTable("roles", { id: integer("id").primaryKey({ autoIncrement: true }), code: text("code").notNull().unique(), name: text("name").notNull() });
export const userRoles = sqliteTable("user_roles", { id: integer("id").primaryKey({ autoIncrement: true }), userId: integer("user_id").notNull().references(() => users.id), roleId: integer("role_id").notNull().references(() => roles.id) }, (t) => [uniqueIndex("user_role_unique").on(t.userId, t.roleId)]);

export const classes = sqliteTable("classes", { id: integer("id").primaryKey({ autoIncrement: true }), ownerId: integer("owner_id").references(() => users.id), name: text("name").notNull(), stage: text("stage").notNull(), grade: text("grade").notNull(), courseType: text("course_type"), startDate: text("start_date"), schedule: text("schedule"), notes: text("notes"), status: text("status").notNull().default("active"), archivedAt: text("archived_at"), ...timestamps });
export const students = sqliteTable("students", { id: integer("id").primaryKey({ autoIncrement: true }), userId: integer("user_id").references(() => users.id), guardianUserId: integer("guardian_user_id").references(() => users.id), name: text("name").notNull(), nickname: text("nickname"), grade: text("grade"), school: text("school"), textbookVersion: text("textbook_version"), subjectChoice: text("subject_choice"), examGoal: text("exam_goal"), guardianContact: text("guardian_contact"), foundationLevel: text("foundation_level"), strengths: text("strengths"), weakKnowledge: text("weak_knowledge"), learningHabits: text("learning_habits"), stageGoal: text("stage_goal"), riskTags: text("risk_tags"), riskConfirmed: integer("risk_confirmed", { mode: "boolean" }).notNull().default(false), status: text("status").notNull().default("active"), archivedAt: text("archived_at"), notes: text("notes"), ...timestamps });
export const enrollments = sqliteTable("enrollments", { id: integer("id").primaryKey({ autoIncrement: true }), classId: integer("class_id").notNull().references(() => classes.id), studentId: integer("student_id").notNull().references(() => students.id), joinedAt: text("joined_at").default(sql`CURRENT_TIMESTAMP`), status: text("status").notNull().default("active") }, (t) => [uniqueIndex("enrollment_unique").on(t.classId, t.studentId)]);
export const staffClassAccess = sqliteTable("staff_class_access", { id: integer("id").primaryKey({ autoIncrement: true }), userId: integer("user_id").notNull().references(() => users.id), classId: integer("class_id").notNull().references(() => classes.id), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, (t) => [uniqueIndex("staff_class_access_unique").on(t.userId, t.classId)]);

export const courses = sqliteTable("courses", { id: integer("id").primaryKey({ autoIncrement: true }), classId: integer("class_id").references(() => classes.id), name: text("name").notNull(), stage: text("stage"), grade: text("grade"), textbookVersion: text("textbook_version"), volume: text("volume"), ...timestamps });
export const lessons = sqliteTable("lessons", { id: integer("id").primaryKey({ autoIncrement: true }), courseId: integer("course_id").references(() => courses.id), classId: integer("class_id").references(() => classes.id), date: text("date").notNull(), startTime: text("start_time"), endTime: text("end_time"), mode: text("mode").notNull().default("offline"), location: text("location"), onlineLink: text("online_link"), courseName: text("course_name").notNull(), stage: text("stage").notNull(), grade: text("grade").notNull(), textbookVersion: text("textbook_version"), volume: text("volume"), unit: text("unit"), topic: text("topic"), knowledgePoints: text("knowledge_points"), teachingGoals: text("teaching_goals"), keyPoints: text("key_points"), difficultPoints: text("difficult_points"), actualContent: text("actual_content"), materials: text("materials"), activities: text("activities"), homework: text("homework"), nextPlan: text("next_plan"), participation: integer("participation"), understanding: integer("understanding"), completion: integer("completion"), discipline: integer("discipline"), fee: real("fee"), feeStatus: text("fee_status").notNull().default("untracked"), cancellationReason: text("cancellation_reason"), status: text("status").notNull().default("draft"), ...timestamps });
export const attendance = sqliteTable("attendance", { id: integer("id").primaryKey({ autoIncrement: true }), lessonId: integer("lesson_id").notNull().references(() => lessons.id), studentId: integer("student_id").notNull().references(() => students.id), status: text("status").notNull(), notes: text("notes") }, (t) => [uniqueIndex("attendance_lesson_student_unique").on(t.lessonId,t.studentId)]);
export const studentLessonRecords = sqliteTable("student_lesson_records", { id: integer("id").primaryKey({ autoIncrement: true }), lessonId: integer("lesson_id").notNull().references(() => lessons.id), studentId: integer("student_id").notNull().references(() => students.id), participation: integer("participation"), understanding: integer("understanding"), completion: integer("completion"), teacherNote: text("teacher_note"), riskTags: text("risk_tags"), riskConfirmed: integer("risk_confirmed", { mode: "boolean" }).notNull().default(false), ...timestamps }, (t) => [uniqueIndex("student_lesson_unique").on(t.lessonId,t.studentId)]);

export const assignments = sqliteTable("assignments", { id: integer("id").primaryKey({ autoIncrement: true }), lessonId: integer("lesson_id").references(() => lessons.id), paperId: integer("paper_id"), classId: integer("class_id").references(() => classes.id), title: text("title").notNull(), requirements: text("requirements"), dueAt: text("due_at"), reminderRule: text("reminder_rule"), status: text("status").notNull().default("draft"), ...timestamps });
export const assignmentSubmissions = sqliteTable("assignment_submissions", { id: integer("id").primaryKey({ autoIncrement: true }), assignmentId: integer("assignment_id").notNull().references(() => assignments.id), studentId: integer("student_id").notNull().references(() => students.id), status: text("status").notNull().default("pending"), score: real("score"), reviewTags: text("review_tags"), teacherNote: text("teacher_note"), submittedAt: text("submitted_at"), ...timestamps });

export const questionSets = sqliteTable("question_sets", { id: integer("id").primaryKey({ autoIncrement: true }), paperId: integer("paper_id"), name: text("name").notNull(), sourceFile: text("source_file"), sourceFingerprint: text("source_fingerprint"), sourceDocument: text("source_document"), importReport: text("import_report"), parseStage: text("parse_stage").notNull().default("review"), failureReason: text("failure_reason"), reviewProgress: integer("review_progress").notNull().default(0), duplicateReport: text("duplicate_report"), status: text("status").notNull().default("review"), ...timestamps });
export const questions = sqliteTable("questions", { id: integer("id").primaryKey({ autoIncrement: true }), questionSetId: integer("question_set_id").references(() => questionSets.id), parentId: integer("parent_id"), questionGroup: text("question_group"), subQuestions: text("sub_questions"), scoringPoints: text("scoring_points"), attachments: text("attachments"), tables: text("tables"), parseConfidence: real("parse_confidence"), reviewStatus: text("review_status").notNull().default("pending"), sourceDocumentId: integer("source_document_id"), stem: text("stem").notNull(), material: text("material"), options: text("options"), answer: text("answer"), answerPoints: text("answer_points"), analysis: text("analysis"), factBasis: text("fact_basis"), textbookView: text("textbook_view"), valueJudgment: text("value_judgment"), answerLogic: text("answer_logic"), standardExpression: text("standard_expression"), questionType: text("question_type").notNull(), difficulty: integer("difficulty"), score: real("score"), stage: text("stage"), grade: text("grade"), textbookVersion: text("textbook_version"), volume: text("volume"), unit: text("unit"), topic: text("topic"), knowledgePoints: text("knowledge_points"), secondaryKnowledge: text("secondary_knowledge"), coreCompetencies: text("core_competencies"), abilityLevel: text("ability_level"), source: text("source"), sourceFile: text("source_file"), year: integer("year"), region: text("region"), examType: text("exam_type"), scenario: text("scenario"), fingerprint: text("fingerprint"), reviewed: integer("reviewed", { mode: "boolean" }).notNull().default(false), isOriginal: integer("is_original", { mode: "boolean" }).notNull().default(false), isFavorite: integer("is_favorite", { mode: "boolean" }).notNull().default(false), isWrong: integer("is_wrong", { mode: "boolean" }).notNull().default(false), isFrequent: integer("is_frequent", { mode: "boolean" }).notNull().default(false), tags: text("tags"), recordedBy: text("recorded_by"), useCount: integer("use_count").notNull().default(0), status: text("status").notNull().default("review"), notes: text("notes"), ...timestamps });
export const savedQuestionViews = sqliteTable("saved_question_views", { id: integer("id").primaryKey({ autoIncrement: true }), ownerId: integer("owner_id").notNull().references(() => users.id), name: text("name").notNull(), filtersJson: text("filters_json").notNull(), ...timestamps }, (t) => [uniqueIndex("saved_question_view_owner_name_unique").on(t.ownerId, t.name)]);
export const wrongQuestions = sqliteTable("wrong_questions", { id: integer("id").primaryKey({ autoIncrement: true }), studentId: integer("student_id").notNull().references(() => students.id), questionId: integer("question_id").notNull().references(() => questions.id), lessonId: integer("lesson_id").references(() => lessons.id), incorrectAnswer: text("incorrect_answer"), reason: text("reason"), status: text("status").notNull().default("active"), occurredAt: text("occurred_at").notNull().default(sql`CURRENT_TIMESTAMP`), masteredAt: text("mastered_at"), ...timestamps }, (t) => [uniqueIndex("wrong_question_student_question_lesson_unique").on(t.studentId, t.questionId, t.lessonId), uniqueIndex("wrong_question_student_status_index").on(t.studentId, t.status)]);
export const papers = sqliteTable("papers", { id: integer("id").primaryKey({ autoIncrement: true }), title: text("title").notNull(), type: text("type").notNull(), stage: text("stage"), grade: text("grade"), textbookVersion: text("textbook_version"), durationMinutes: integer("duration_minutes"), instructions: text("instructions"), totalScore: real("total_score"), year: integer("year"), academicYear: text("academic_year"), examCategory: text("exam_category"), semester: text("semester"), province: text("province"), city: text("city"), district: text("district"), examDate: text("exam_date"), region: text("region"), school: text("school"), source: text("source"), tags: text("tags"), useStatus: text("use_status").notNull().default("unused"), parseStatus: text("parse_status").notNull().default("not_started"), status: text("status").notNull().default("draft"), ...timestamps });
export const paperQuestions = sqliteTable("paper_questions", { id: integer("id").primaryKey({ autoIncrement: true }), paperId: integer("paper_id").notNull().references(() => papers.id), questionId: integer("question_id").notNull().references(() => questions.id), position: integer("position").notNull(), score: real("score"), groupTitle: text("group_title"), answerSpace: integer("answer_space").notNull().default(2) });
export const paperFiles = sqliteTable("paper_files", { id: integer("id").primaryKey({ autoIncrement: true }), paperId: integer("paper_id").notNull().references(() => papers.id), versionType: text("version_type").notNull().default("student"), originalName: text("original_name").notNull(), storageKey: text("storage_key").notNull(), mimeType: text("mime_type").notNull(), size: integer("size").notNull(), fingerprint: text("fingerprint").notNull(), pageCount: integer("page_count"), parseStatus: text("parse_status").notNull().default("queued"), parseMessage: text("parse_message"), uploadedBy: integer("uploaded_by").references(() => users.id), ...timestamps });
export const exportJobs = sqliteTable("export_jobs", { id: text("id").primaryKey(), paperId: integer("paper_id").notNull().references(() => papers.id), format: text("format").notNull(), mode: text("mode").notNull(), status: text("status").notNull().default("queued"), resultKey: text("result_key"), error: text("error"), createdBy: integer("created_by").references(() => users.id), ...timestamps });
export const lessonQuestions = sqliteTable("lesson_questions", { id: integer("id").primaryKey({ autoIncrement: true }), lessonId: integer("lesson_id").notNull().references(() => lessons.id), questionId: integer("question_id").notNull().references(() => questions.id), purpose: text("purpose").notNull().default("课堂练习"), position: integer("position").notNull().default(0) }, (t) => [uniqueIndex("lesson_question_unique").on(t.lessonId,t.questionId)]);

export const academicYears = sqliteTable("academic_years", { id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull().unique(), startDate: text("start_date").notNull(), endDate: text("end_date").notNull(), status: text("status").notNull().default("active"), ...timestamps });
export const examProjects = sqliteTable("exam_projects", { id: integer("id").primaryKey({ autoIncrement: true }), academicYear: text("academic_year").notNull(), name: text("name").notNull(), category: text("category").notNull(), stage: text("stage").notNull(), grade: text("grade").notNull(), examDate: text("exam_date"), totalScore: real("total_score").notNull().default(100), paperId: integer("paper_id").references(() => papers.id), status: text("status").notNull().default("draft"), notes: text("notes"), ...timestamps }, (t) => [uniqueIndex("exam_project_identity_unique").on(t.academicYear,t.category,t.stage,t.grade)]);
export const assessments = sqliteTable("assessments", { id: integer("id").primaryKey({ autoIncrement: true }), classId: integer("class_id").references(() => classes.id), paperId: integer("paper_id").references(() => papers.id), examProjectId: integer("exam_project_id").references(() => examProjects.id), title: text("title").notNull(), date: text("date"), totalScore: real("total_score").notNull().default(100), type: text("type").notNull().default("课堂测验"), status: text("status").notNull().default("draft"), notes: text("notes"), ...timestamps });
export const assessmentResults = sqliteTable("assessment_results", { id: integer("id").primaryKey({ autoIncrement: true }), assessmentId: integer("assessment_id").notNull().references(() => assessments.id), studentId: integer("student_id").notNull().references(() => students.id), score: real("score"), objectiveScore: real("objective_score"), subjectiveScore: real("subjective_score"), knowledgeMastery: text("knowledge_mastery"), weakKnowledge: text("weak_knowledge"), teacherNote: text("teacher_note"), ...timestamps }, (t) => [uniqueIndex("assessment_student_unique").on(t.assessmentId, t.studentId)]);
export const examProjectStudents = sqliteTable("exam_project_students", { id: integer("id").primaryKey({ autoIncrement: true }), projectId: integer("project_id").notNull().references(() => examProjects.id), studentId: integer("student_id").notNull().references(() => students.id), assessmentResultId: integer("assessment_result_id").references(() => assessmentResults.id), status: text("status").notNull().default("pending"), ...timestamps }, (t) => [uniqueIndex("exam_project_student_unique").on(t.projectId,t.studentId)]);
export const gradePromotionRuns = sqliteTable("grade_promotion_runs", { id: integer("id").primaryKey({ autoIncrement: true }), academicYear: text("academic_year").notNull().unique(), status: text("status").notNull().default("preview"), confirmedBy: integer("confirmed_by").references(() => users.id), confirmedAt: text("confirmed_at"), ...timestamps });
export const gradePromotionItems = sqliteTable("grade_promotion_items", { id: integer("id").primaryKey({ autoIncrement: true }), runId: integer("run_id").notNull().references(() => gradePromotionRuns.id), studentId: integer("student_id").notNull().references(() => students.id), fromGrade: text("from_grade").notNull(), toGrade: text("to_grade"), action: text("action").notNull().default("promote"), status: text("status").notNull().default("pending"), reason: text("reason"), ...timestamps }, (t) => [uniqueIndex("grade_promotion_student_unique").on(t.runId,t.studentId)]);
export const studentMasteryAdjustments = sqliteTable("student_mastery_adjustments", { id: integer("id").primaryKey({ autoIncrement: true }), studentId: integer("student_id").notNull().references(() => students.id), calculatedScore: real("calculated_score"), overrideScore: real("override_score").notNull(), reason: text("reason").notNull(), createdBy: text("created_by").notNull(), ...timestamps });
export const feedback = sqliteTable("feedback", { id: integer("id").primaryKey({ autoIncrement: true }), lessonId: integer("lesson_id").references(() => lessons.id), studentId: integer("student_id").references(() => students.id), classId: integer("class_id").references(() => classes.id), type: text("type").notNull(), audience: text("audience").notNull().default("private"), lengthMode: text("length_mode").notNull().default("short"), tone: text("tone"), customInput: text("custom_input"), previousHomework: text("previous_homework"), classPerformance: text("class_performance"), weakPoints: text("weak_points"), dueAt: text("due_at"), content: text("content").notNull(), shortContent: text("short_content"), standardContent: text("standard_content"), learningContent: text("learning_content"), highlights: text("highlights"), consolidate: text("consolidate"), homeworkRequirements: text("homework_requirements"), parentAdvice: text("parent_advice"), nextFocus: text("next_focus"), periodStart: text("period_start"), periodEnd: text("period_end"), periodSummary: text("period_summary"), progress: text("progress"), problems: text("problems"), goals: text("goals"), suggestions: text("suggestions"), status: text("status").notNull().default("draft"), copiedAt: text("copied_at"), confirmedAt: text("confirmed_at"), sentAt: text("sent_at"), ...timestamps });
export const feedbackTemplates = sqliteTable("feedback_templates", { id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull(), audience: text("audience").notNull().default("private"), tone: text("tone").notNull().default("温和鼓励"), opening: text("opening"), closing: text("closing"), styleRules: text("style_rules"), exampleText: text("example_text"), isDefault: integer("is_default", { mode: "boolean" }).notNull().default(false), status: text("status").notNull().default("active"), ...timestamps });
export const feedbackEvidence = sqliteTable("feedback_evidence", { id: integer("id").primaryKey({ autoIncrement: true }), feedbackId: integer("feedback_id").notNull().references(() => feedback.id), sourceType: text("source_type").notNull(), sourceId: integer("source_id"), label: text("label").notNull(), excerpt: text("excerpt"), sourceDate: text("source_date"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const lessonWorkflowState = sqliteTable("lesson_workflow_state", { lessonId: integer("lesson_id").primaryKey().references(() => lessons.id), revision: integer("revision").notNull().default(0), draftPayload: text("draft_payload").notNull().default("{}"), homeworkPaperId: integer("homework_paper_id").references(() => papers.id), homeworkAssignmentId: integer("homework_assignment_id").references(() => assignments.id), updatedBy: integer("updated_by").references(() => users.id), updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const lessonCompletionRuns = sqliteTable("lesson_completion_runs", { id: text("id").primaryKey(), lessonId: integer("lesson_id").notNull().references(() => lessons.id), actorId: integer("actor_id").notNull().references(() => users.id), beforeSnapshot: text("before_snapshot").notNull(), artifactSnapshot: text("artifact_snapshot").notNull(), status: text("status").notNull().default("active"), completedAt: text("completed_at").notNull().default(sql`CURRENT_TIMESTAMP`), undoneAt: text("undone_at") });
export const workflowTemplates = sqliteTable("workflow_templates", { id: integer("id").primaryKey({ autoIncrement: true }), ownerId: integer("owner_id").notNull().references(() => users.id), type: text("type").notNull(), name: text("name").notNull(), payloadJson: text("payload_json").notNull().default("{}"), isDefault: integer("is_default", { mode: "boolean" }).notNull().default(false), status: text("status").notNull().default("active"), ...timestamps }, (t) => [uniqueIndex("workflow_template_owner_type_name_unique").on(t.ownerId, t.type, t.name)]);
export const reflections = sqliteTable("reflections", { id: integer("id").primaryKey({ autoIncrement: true }), lessonId: integer("lesson_id").references(() => lessons.id), date: text("date").notNull(), tags: text("tags"), problemType: text("problem_type"), expectedVsActual: text("expected_vs_actual"), effectivePractices: text("effective_practices"), difficulties: text("difficulties"), studentEvidence: text("student_evidence"), nextAction: text("next_action"), actionCompleted: integer("action_completed", { mode: "boolean" }).notNull().default(false), reusableMaterial: text("reusable_material"), isStrategy: integer("is_strategy", { mode: "boolean" }).notNull().default(false), isPrivate: integer("is_private", { mode: "boolean" }).notNull().default(true), ...timestamps });
export const resources = sqliteTable("resources", { id: integer("id").primaryKey({ autoIncrement: true }), ownerId: integer("owner_id").references(() => users.id), title: text("title").notNull(), type: text("type"), url: text("url"), tags: text("tags"), content: text("content"), sourceRef: text("source_ref"), visibility: text("visibility").notNull().default("private"), ...timestamps });
export const auditLogs = sqliteTable("audit_logs", { id: integer("id").primaryKey({ autoIncrement: true }), userId: integer("user_id").references(() => users.id), action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: text("entity_id"), detail: text("detail"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const demoRecords = sqliteTable("demo_records", { id: integer("id").primaryKey({ autoIncrement: true }), runId: text("run_id").notNull(), entityType: text("entity_type").notNull(), entityId: integer("entity_id").notNull(), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const teacherAdminCredentials = sqliteTable("teacher_admin_credentials", { id: integer("id").primaryKey(), passwordSalt: text("password_salt").notNull(), passwordHash: text("password_hash").notNull(), iterations: integer("iterations").notNull().default(210000), sessionVersion: integer("session_version").notNull().default(1), updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const teacherLoginAttempts = sqliteTable("teacher_login_attempts", { key: text("key").primaryKey(), failures: integer("failures").notNull().default(0), blockedUntil: integer("blocked_until"), updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) });

// 课表、计费与结算。金额快照写入课时账目，避免后续修改计价规则篡改历史。
export const institutions = sqliteTable("institutions", { id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull(), settlementCycle: text("settlement_cycle").notNull().default("monthly"), status: text("status").notNull().default("active"), notes: text("notes"), ...timestamps });
export const pricingRules = sqliteTable("pricing_rules", { id: integer("id").primaryKey({ autoIncrement: true }), institutionId: integer("institution_id").references(() => institutions.id), studentId: integer("student_id").references(() => students.id), payerType: text("payer_type").notNull(), baseFee: real("base_fee").notNull().default(0), perStudentFee: real("per_student_fee").notNull().default(0), unitPrice: real("unit_price").notNull().default(0), effectiveFrom: text("effective_from"), effectiveTo: text("effective_to"), status: text("status").notNull().default("active"), ...timestamps });
export const scheduleImports = sqliteTable("schedule_imports", { id: integer("id").primaryKey({ autoIncrement: true }), sourceName: text("source_name").notNull(), fingerprint: text("fingerprint").notNull(), mapping: text("mapping"), report: text("report"), status: text("status").notNull().default("preview"), createdBy: integer("created_by").references(() => users.id), ...timestamps });
export const scheduleImportRows = sqliteTable("schedule_import_rows", { id: integer("id").primaryKey({ autoIncrement: true }), importId: integer("import_id").notNull().references(() => scheduleImports.id), rowNumber: integer("row_number").notNull(), rawData: text("raw_data").notNull(), normalizedData: text("normalized_data"), action: text("action").notNull().default("pending"), issue: text("issue"), lessonId: integer("lesson_id").references(() => lessons.id), ...timestamps });
export const lessonFinance = sqliteTable("lesson_finance", { id: integer("id").primaryKey({ autoIncrement: true }), lessonId: integer("lesson_id").notNull().unique().references(() => lessons.id), payerType: text("payer_type").notNull(), payerId: integer("payer_id"), baseFee: real("base_fee").notNull().default(0), adjustment: real("adjustment").notNull().default(0), expectedAmount: real("expected_amount").notNull().default(0), receivedAmount: real("received_amount").notNull().default(0), status: text("status").notNull().default("review"), confirmedAt: text("confirmed_at"), confirmedBy: integer("confirmed_by").references(() => users.id), pricingRuleId: integer("pricing_rule_id").references(() => pricingRules.id), calculationSnapshot: text("calculation_snapshot"), note: text("note"), ...timestamps });
export const lessonBillingItems = sqliteTable("lesson_billing_items", { id: integer("id").primaryKey({ autoIncrement: true }), lessonFinanceId: integer("lesson_finance_id").notNull().references(() => lessonFinance.id), studentId: integer("student_id").notNull().references(() => students.id), attendanceStatus: text("attendance_status").notNull().default("present"), billingFactor: real("billing_factor").notNull().default(1), unitFee: real("unit_fee").notNull().default(0), amount: real("amount").notNull().default(0), reason: text("reason"), ...timestamps }, (t) => [uniqueIndex("lesson_billing_student_unique").on(t.lessonFinanceId, t.studentId)]);
export const settlements = sqliteTable("settlements", { id: integer("id").primaryKey({ autoIncrement: true }), payerType: text("payer_type").notNull(), payerId: integer("payer_id"), periodStart: text("period_start").notNull(), periodEnd: text("period_end").notNull(), expectedAmount: real("expected_amount").notNull().default(0), receivedAmount: real("received_amount").notNull().default(0), status: text("status").notNull().default("pending"), confirmedAt: text("confirmed_at"), note: text("note"), ...timestamps });
export const settlementItems = sqliteTable("settlement_items", { id: integer("id").primaryKey({ autoIncrement: true }), settlementId: integer("settlement_id").notNull().references(() => settlements.id), lessonFinanceId: integer("lesson_finance_id").notNull().references(() => lessonFinance.id), expectedAmount: real("expected_amount").notNull(), receivedAmount: real("received_amount").notNull().default(0) }, (t) => [uniqueIndex("settlement_finance_unique").on(t.settlementId, t.lessonFinanceId)]);
export const lessonPackages = sqliteTable("lesson_packages", { id: integer("id").primaryKey({ autoIncrement: true }), studentId: integer("student_id").notNull().references(() => students.id), name: text("name").notNull(), unitPrice: real("unit_price").notNull().default(0), purchasedHours: real("purchased_hours").notNull().default(0), balanceHours: real("balance_hours").notNull().default(0), status: text("status").notNull().default("active"), ...timestamps });
export const packageLedger = sqliteTable("package_ledger", { id: integer("id").primaryKey({ autoIncrement: true }), packageId: integer("package_id").notNull().references(() => lessonPackages.id), lessonId: integer("lesson_id").references(() => lessons.id), type: text("type").notNull(), hoursDelta: real("hours_delta").notNull().default(0), amountDelta: real("amount_delta").notNull().default(0), reason: text("reason").notNull(), createdBy: integer("created_by").references(() => users.id), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const calendarSubscriptions = sqliteTable("calendar_subscriptions", { id: integer("id").primaryKey({ autoIncrement: true }), tokenHash: text("token_hash").notNull().unique(), label: text("label").notNull().default("Apple 日历"), reminderMinutes: integer("reminder_minutes").notNull().default(30), revokedAt: text("revoked_at"), ...timestamps });

// 私有文件、识别和题目级学情证据。
export const fileAssets = sqliteTable("file_assets", { id: integer("id").primaryKey({ autoIncrement: true }), ownerType: text("owner_type").notNull(), ownerId: integer("owner_id"), storageKey: text("storage_key").notNull().unique(), originalName: text("original_name").notNull(), mimeType: text("mime_type").notNull(), size: integer("size").notNull(), fingerprint: text("fingerprint"), purpose: text("purpose").notNull(), status: text("status").notNull().default("active"), createdBy: integer("created_by").references(() => users.id), ...timestamps });
export const feedbackImports = sqliteTable("feedback_imports", { id: integer("id").primaryKey({ autoIncrement: true }), sourceAssetId: integer("source_asset_id").references(() => fileAssets.id), sourceText: text("source_text"), ocrText: text("ocr_text"), parsedPayload: text("parsed_payload").notNull().default("{}"), confidence: real("confidence").notNull().default(0), status: text("status").notNull().default("draft"), matchedLessonId: integer("matched_lesson_id").references(() => lessons.id), confirmedLessonId: integer("confirmed_lesson_id").references(() => lessons.id), createdBy: integer("created_by").references(() => users.id), confirmedAt: text("confirmed_at"), ...timestamps });
export const recognitionJobs = sqliteTable("recognition_jobs", { id: integer("id").primaryKey({ autoIncrement: true }), assessmentId: integer("assessment_id").references(() => assessments.id), studentId: integer("student_id").references(() => students.id), sourceAssetId: integer("source_asset_id").notNull().references(() => fileAssets.id), answerAssetId: integer("answer_asset_id").references(() => fileAssets.id), provider: text("provider").notNull().default("manual"), stage: text("stage").notNull().default("uploaded"), progress: integer("progress").notNull().default(0), error: text("error"), confirmedAt: text("confirmed_at"), ...timestamps });
export const recognitionItems = sqliteTable("recognition_items", { id: integer("id").primaryKey({ autoIncrement: true }), jobId: integer("job_id").notNull().references(() => recognitionJobs.id), questionId: integer("question_id").references(() => questions.id), questionNumber: text("question_number").notNull(), studentAnswer: text("student_answer"), standardAnswer: text("standard_answer"), recognizedScore: real("recognized_score"), teacherScore: real("teacher_score"), maxScore: real("max_score"), confidence: real("confidence"), candidates: text("candidates"), cropAssetId: integer("crop_asset_id").references(() => fileAssets.id), knowledgePoints: text("knowledge_points"), errorType: text("error_type"), reviewStatus: text("review_status").notNull().default("pending"), ...timestamps });
export const assessmentQuestionResults = sqliteTable("assessment_question_results", { id: integer("id").primaryKey({ autoIncrement: true }), assessmentResultId: integer("assessment_result_id").notNull().references(() => assessmentResults.id), questionId: integer("question_id").references(() => questions.id), questionNumber: text("question_number").notNull(), answer: text("answer"), score: real("score"), maxScore: real("max_score"), knowledgePoints: text("knowledge_points"), errorType: text("error_type"), source: text("source").notNull().default("manual"), confirmedAt: text("confirmed_at").notNull(), ...timestamps }, (t) => [uniqueIndex("assessment_result_question_unique").on(t.assessmentResultId, t.questionNumber)]);
export const textbookNodes = sqliteTable("textbook_nodes", { id: integer("id").primaryKey({ autoIncrement: true }), parentId: integer("parent_id"), stage: text("stage").notNull(), grade: text("grade"), textbookVersion: text("textbook_version"), level: text("level").notNull(), name: text("name").notNull(), path: text("path").notNull(), sort: integer("sort").notNull().default(0), ...timestamps });
export const knowledgeEvidence = sqliteTable("knowledge_evidence", { id: integer("id").primaryKey({ autoIncrement: true }), studentId: integer("student_id").notNull().references(() => students.id), textbookNodeId: integer("textbook_node_id").references(() => textbookNodes.id), knowledgeName: text("knowledge_name").notNull(), level: text("level").notNull(), sourceType: text("source_type").notNull(), sourceId: integer("source_id"), evidence: text("evidence").notNull(), isManual: integer("is_manual", { mode: "boolean" }).notNull().default(false), createdBy: integer("created_by").references(() => users.id), ...timestamps });

// 微信小程序一期共享数据。正式微信身份只在配置 AppID 后启用。
export const wechatAccounts = sqliteTable("wechat_accounts", { id: integer("id").primaryKey({ autoIncrement: true }), userId: integer("user_id").references(() => users.id), studentId: integer("student_id").references(() => students.id), openId: text("open_id").unique(), role: text("role").notNull(), displayName: text("display_name"), status: text("status").notNull().default("pending"), ...timestamps });
export const miniSessions = sqliteTable("mini_sessions", { id: text("id").primaryKey(), accountId: integer("account_id").notNull().references(() => wechatAccounts.id), tokenHash: text("token_hash").notNull().unique(), expiresAt: text("expires_at").notNull(), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const miniInvites = sqliteTable("mini_invites", { id: integer("id").primaryKey({ autoIncrement: true }), codeHash: text("code_hash").notNull().unique(), role: text("role").notNull(), studentId: integer("student_id").references(() => students.id), expiresAt: text("expires_at").notNull(), usedAt: text("used_at"), createdBy: integer("created_by").references(() => users.id), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const parentStudentLinks = sqliteTable("parent_student_links", { id: integer("id").primaryKey({ autoIncrement: true }), parentAccountId: integer("parent_account_id").notNull().references(() => wechatAccounts.id), studentId: integer("student_id").notNull().references(() => students.id), status: text("status").notNull().default("pending"), confirmedBy: integer("confirmed_by").references(() => users.id), ...timestamps }, (t) => [uniqueIndex("parent_student_link_unique").on(t.parentAccountId, t.studentId)]);
export const assignmentAssets = sqliteTable("assignment_assets", { id: integer("id").primaryKey({ autoIncrement: true }), assignmentId: integer("assignment_id").notNull().references(() => assignments.id), assetId: integer("asset_id").notNull().references(() => fileAssets.id), position: integer("position").notNull().default(0) });
export const submissionVersions = sqliteTable("submission_versions", { id: integer("id").primaryKey({ autoIncrement: true }), submissionId: integer("submission_id").notNull().references(() => assignmentSubmissions.id), version: integer("version").notNull(), textContent: text("text_content"), status: text("status").notNull().default("submitted"), submittedByRole: text("submitted_by_role").notNull(), submittedAt: text("submitted_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, (t) => [uniqueIndex("submission_version_unique").on(t.submissionId, t.version)]);
export const submissionAssets = sqliteTable("submission_assets", { id: integer("id").primaryKey({ autoIncrement: true }), submissionVersionId: integer("submission_version_id").notNull().references(() => submissionVersions.id), assetId: integer("asset_id").notNull().references(() => fileAssets.id), position: integer("position").notNull().default(0), precheckStatus: text("precheck_status").notNull().default("pending"), precheckNotes: text("precheck_notes") });
export const reviewAnnotations = sqliteTable("review_annotations", { id: integer("id").primaryKey({ autoIncrement: true }), submissionVersionId: integer("submission_version_id").notNull().references(() => submissionVersions.id), assetId: integer("asset_id").references(() => fileAssets.id), type: text("type").notNull(), payload: text("payload").notNull(), status: text("status").notNull().default("draft"), createdBy: integer("created_by").references(() => users.id), ...timestamps });
export const excellentSubmissions = sqliteTable("excellent_submissions", { id: integer("id").primaryKey({ autoIncrement: true }), submissionVersionId: integer("submission_version_id").notNull().unique().references(() => submissionVersions.id), maskedAssetId: integer("masked_asset_id").references(() => fileAssets.id), maskingStatus: text("masking_status").notNull().default("pending"), publishedAt: text("published_at"), publishedBy: integer("published_by").references(() => users.id), ...timestamps });

// 网站与小程序共用的绑定、接收范围、幂等、同步与失败恢复数据。
export const miniBindings = sqliteTable("mini_bindings", { id: integer("id").primaryKey({ autoIncrement: true }), accountId: integer("account_id").notNull().references(() => wechatAccounts.id), studentId: integer("student_id").notNull().references(() => students.id), role: text("role").notNull(), inviteId: integer("invite_id").references(() => miniInvites.id), status: text("status").notNull().default("pending"), confirmedBy: integer("confirmed_by").references(() => users.id), confirmedAt: text("confirmed_at"), disabledAt: text("disabled_at"), ...timestamps }, (t) => [uniqueIndex("mini_binding_account_student_role_unique").on(t.accountId, t.studentId, t.role)]);
export const assignmentTargets = sqliteTable("assignment_targets", { id: integer("id").primaryKey({ autoIncrement: true }), assignmentId: integer("assignment_id").notNull().references(() => assignments.id), targetType: text("target_type").notNull(), targetId: integer("target_id").notNull(), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, (t) => [uniqueIndex("assignment_target_unique").on(t.assignmentId, t.targetType, t.targetId)]);
export const assignmentSettings = sqliteTable("assignment_settings", { assignmentId: integer("assignment_id").primaryKey().references(() => assignments.id), allowParentSubmit: integer("allow_parent_submit", { mode: "boolean" }).notNull().default(true), requireRevision: integer("require_revision", { mode: "boolean" }).notNull().default(true), publishedAt: text("published_at"), closedAt: text("closed_at"), ...timestamps });
export const idempotencyOperations = sqliteTable("idempotency_operations", { id: integer("id").primaryKey({ autoIncrement: true }), actorType: text("actor_type").notNull(), actorId: integer("actor_id").notNull(), action: text("action").notNull(), operationId: text("operation_id").notNull(), status: text("status").notNull().default("started"), resultJson: text("result_json"), expiresAt: text("expires_at"), ...timestamps }, (t) => [uniqueIndex("idempotency_actor_action_operation_unique").on(t.actorType, t.actorId, t.action, t.operationId)]);
export const syncEvents = sqliteTable("sync_events", { id: integer("id").primaryKey({ autoIncrement: true }), eventType: text("event_type").notNull(), entityType: text("entity_type").notNull(), entityId: text("entity_id").notNull(), audienceRole: text("audience_role"), studentId: integer("student_id").references(() => students.id), accountId: integer("account_id").references(() => wechatAccounts.id), payload: text("payload"), isDeleted: integer("is_deleted", { mode: "boolean" }).notNull().default(false), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const fileLeases = sqliteTable("file_leases", { assetId: integer("asset_id").primaryKey().references(() => fileAssets.id), operationId: text("operation_id"), state: text("state").notNull().default("temporary"), linkedEntityType: text("linked_entity_type"), linkedEntityId: text("linked_entity_id"), expiresAt: text("expires_at"), ...timestamps });
export const submissionReviews = sqliteTable("submission_reviews", { id: integer("id").primaryKey({ autoIncrement: true }), submissionId: integer("submission_id").notNull().references(() => assignmentSubmissions.id), submissionVersionId: integer("submission_version_id").references(() => submissionVersions.id), status: text("status").notNull().default("draft"), outcome: text("outcome"), score: real("score"), reviewTags: text("review_tags"), teacherNote: text("teacher_note"), revisionRequirements: text("revision_requirements"), operationId: text("operation_id"), reviewedBy: integer("reviewed_by").references(() => users.id), confirmedAt: text("confirmed_at"), ...timestamps });
export const reviewAssets = sqliteTable("review_assets", { id: integer("id").primaryKey({ autoIncrement: true }), reviewId: integer("review_id").notNull().references(() => submissionReviews.id), assetId: integer("asset_id").notNull().references(() => fileAssets.id), type: text("type").notNull(), position: integer("position").notNull().default(0), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const reminderTasks = sqliteTable("reminder_tasks", { id: integer("id").primaryKey({ autoIncrement: true }), eventType: text("event_type").notNull(), entityType: text("entity_type").notNull(), entityId: text("entity_id").notNull(), accountId: integer("account_id"), studentId: integer("student_id"), operationId: text("operation_id").notNull().unique(), status: text("status").notNull().default("pending"), failureReason: text("failure_reason"), scheduledAt: text("scheduled_at"), sentAt: text("sent_at"), ...timestamps });

export const aiSettings = sqliteTable("ai_settings", { userId: integer("user_id").primaryKey().references(() => users.id), enabled: integer("enabled", { mode: "boolean" }).notNull().default(false), includeStudentName: integer("include_student_name", { mode: "boolean" }).notNull().default(true), privacyAckAt: text("privacy_ack_at"), dailyLimit: integer("daily_limit").notNull().default(50), emergencyDisabled: integer("emergency_disabled", { mode: "boolean" }).notNull().default(false), fastModel: text("fast_model").notNull().default("deepseek-v4-flash"), deepModel: text("deep_model").notNull().default("deepseek-v4-pro"), ...timestamps });
export const aiRuns = sqliteTable("ai_runs", { id: integer("id").primaryKey({ autoIncrement: true }), userId: integer("user_id").notNull().references(() => users.id), feature: text("feature").notNull(), entityType: text("entity_type"), entityId: text("entity_id"), model: text("model").notNull(), promptVersion: text("prompt_version").notNull(), inputFingerprint: text("input_fingerprint").notNull(), status: text("status").notNull().default("running"), promptTokens: integer("prompt_tokens").notNull().default(0), cacheHitTokens: integer("cache_hit_tokens").notNull().default(0), cacheMissTokens: integer("cache_miss_tokens").notNull().default(0), completionTokens: integer("completion_tokens").notNull().default(0), totalTokens: integer("total_tokens").notNull().default(0), estimatedCostUsd: real("estimated_cost_usd").notNull().default(0), errorCode: text("error_code"), ...timestamps });
export const aiFeedbackLearningEvents = sqliteTable("ai_feedback_learning_events", { id: integer("id").primaryKey({ autoIncrement: true }), userId: integer("user_id").notNull().references(() => users.id), feedbackId: integer("feedback_id").notNull().references(() => feedback.id), audience: text("audience"), tone: text("tone"), stage: text("stage"), grade: text("grade"), contentTemplate: text("content_template").notNull(), editSummaryJson: text("edit_summary_json").notNull().default("{}"), contentFingerprint: text("content_fingerprint").notNull(), active: integer("active", { mode: "boolean" }).notNull().default(true), ...timestamps }, (t) => [uniqueIndex("ai_learning_user_fingerprint_unique").on(t.userId, t.contentFingerprint)]);
export const aiQuestionReviews = sqliteTable("ai_question_reviews", { id: integer("id").primaryKey({ autoIncrement: true }), runId: integer("run_id").notNull().references(() => aiRuns.id), questionId: integer("question_id").notNull().references(() => questions.id), sourceUpdatedAt: text("source_updated_at").notNull(), safeSuggestionsJson: text("safe_suggestions_json").notNull().default("{}"), sensitiveSuggestionsJson: text("sensitive_suggestions_json").notNull().default("{}"), confidenceJson: text("confidence_json").notNull().default("{}"), reasonsJson: text("reasons_json").notNull().default("{}"), status: text("status").notNull().default("pending"), appliedFieldsJson: text("applied_fields_json").notNull().default("[]"), ...timestamps }, (t) => [uniqueIndex("ai_question_review_source_unique").on(t.questionId, t.sourceUpdatedAt)]);
