import { sql } from "drizzle-orm";
import { integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const timestamps = { createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) };

export const users = sqliteTable("users", { id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull(), email: text("email"), ...timestamps });
export const roles = sqliteTable("roles", { id: integer("id").primaryKey({ autoIncrement: true }), code: text("code").notNull().unique(), name: text("name").notNull() });
export const userRoles = sqliteTable("user_roles", { id: integer("id").primaryKey({ autoIncrement: true }), userId: integer("user_id").notNull().references(() => users.id), roleId: integer("role_id").notNull().references(() => roles.id) }, (t) => [uniqueIndex("user_role_unique").on(t.userId, t.roleId)]);

export const classes = sqliteTable("classes", { id: integer("id").primaryKey({ autoIncrement: true }), ownerId: integer("owner_id").references(() => users.id), name: text("name").notNull(), stage: text("stage").notNull(), grade: text("grade").notNull(), courseType: text("course_type"), startDate: text("start_date"), schedule: text("schedule"), notes: text("notes"), ...timestamps });
export const students = sqliteTable("students", { id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull(), nickname: text("nickname"), grade: text("grade"), guardianContact: text("guardian_contact"), foundationLevel: text("foundation_level"), strengths: text("strengths"), weakKnowledge: text("weak_knowledge"), learningHabits: text("learning_habits"), stageGoal: text("stage_goal"), riskTags: text("risk_tags"), riskConfirmed: integer("risk_confirmed", { mode: "boolean" }).notNull().default(false), notes: text("notes"), ...timestamps });
export const enrollments = sqliteTable("enrollments", { id: integer("id").primaryKey({ autoIncrement: true }), classId: integer("class_id").notNull().references(() => classes.id), studentId: integer("student_id").notNull().references(() => students.id), joinedAt: text("joined_at").default(sql`CURRENT_TIMESTAMP`), status: text("status").notNull().default("active") }, (t) => [uniqueIndex("enrollment_unique").on(t.classId, t.studentId)]);

export const courses = sqliteTable("courses", { id: integer("id").primaryKey({ autoIncrement: true }), classId: integer("class_id").references(() => classes.id), name: text("name").notNull(), stage: text("stage"), grade: text("grade"), textbookVersion: text("textbook_version"), volume: text("volume"), ...timestamps });
export const lessons = sqliteTable("lessons", { id: integer("id").primaryKey({ autoIncrement: true }), courseId: integer("course_id").references(() => courses.id), classId: integer("class_id").references(() => classes.id), date: text("date").notNull(), startTime: text("start_time"), endTime: text("end_time"), mode: text("mode").notNull().default("offline"), location: text("location"), onlineLink: text("online_link"), courseName: text("course_name").notNull(), stage: text("stage").notNull(), grade: text("grade").notNull(), textbookVersion: text("textbook_version"), volume: text("volume"), unit: text("unit"), topic: text("topic"), teachingGoals: text("teaching_goals"), keyPoints: text("key_points"), difficultPoints: text("difficult_points"), actualContent: text("actual_content"), materials: text("materials"), activities: text("activities"), homework: text("homework"), nextPlan: text("next_plan"), participation: integer("participation"), understanding: integer("understanding"), completion: integer("completion"), discipline: integer("discipline"), status: text("status").notNull().default("draft"), ...timestamps });
export const attendance = sqliteTable("attendance", { id: integer("id").primaryKey({ autoIncrement: true }), lessonId: integer("lesson_id").notNull().references(() => lessons.id), studentId: integer("student_id").notNull().references(() => students.id), status: text("status").notNull(), notes: text("notes") });
export const studentLessonRecords = sqliteTable("student_lesson_records", { id: integer("id").primaryKey({ autoIncrement: true }), lessonId: integer("lesson_id").notNull().references(() => lessons.id), studentId: integer("student_id").notNull().references(() => students.id), participation: integer("participation"), understanding: integer("understanding"), completion: integer("completion"), teacherNote: text("teacher_note"), riskTags: text("risk_tags"), riskConfirmed: integer("risk_confirmed", { mode: "boolean" }).notNull().default(false), ...timestamps });

export const assignments = sqliteTable("assignments", { id: integer("id").primaryKey({ autoIncrement: true }), lessonId: integer("lesson_id").references(() => lessons.id), title: text("title").notNull(), requirements: text("requirements"), dueAt: text("due_at"), ...timestamps });
export const assignmentSubmissions = sqliteTable("assignment_submissions", { id: integer("id").primaryKey({ autoIncrement: true }), assignmentId: integer("assignment_id").notNull().references(() => assignments.id), studentId: integer("student_id").notNull().references(() => students.id), status: text("status").notNull().default("pending"), score: real("score"), teacherNote: text("teacher_note"), submittedAt: text("submitted_at"), ...timestamps });

export const questionSets = sqliteTable("question_sets", { id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull(), sourceFile: text("source_file"), status: text("status").notNull().default("review"), ...timestamps });
export const questions = sqliteTable("questions", { id: integer("id").primaryKey({ autoIncrement: true }), questionSetId: integer("question_set_id").references(() => questionSets.id), stem: text("stem").notNull(), material: text("material"), options: text("options"), answer: text("answer"), analysis: text("analysis"), factBasis: text("fact_basis"), textbookView: text("textbook_view"), valueJudgment: text("value_judgment"), answerLogic: text("answer_logic"), standardExpression: text("standard_expression"), questionType: text("question_type").notNull(), difficulty: integer("difficulty"), score: real("score"), stage: text("stage"), grade: text("grade"), textbookVersion: text("textbook_version"), volume: text("volume"), unit: text("unit"), topic: text("topic"), knowledgePoints: text("knowledge_points"), coreCompetencies: text("core_competencies"), source: text("source"), year: integer("year"), region: text("region"), scenario: text("scenario"), isOriginal: integer("is_original", { mode: "boolean" }).notNull().default(false), status: text("status").notNull().default("review"), notes: text("notes"), ...timestamps });
export const papers = sqliteTable("papers", { id: integer("id").primaryKey({ autoIncrement: true }), title: text("title").notNull(), type: text("type").notNull(), totalScore: real("total_score"), status: text("status").notNull().default("draft"), ...timestamps });
export const paperQuestions = sqliteTable("paper_questions", { id: integer("id").primaryKey({ autoIncrement: true }), paperId: integer("paper_id").notNull().references(() => papers.id), questionId: integer("question_id").notNull().references(() => questions.id), position: integer("position").notNull(), score: real("score") });

export const assessments = sqliteTable("assessments", { id: integer("id").primaryKey({ autoIncrement: true }), classId: integer("class_id").references(() => classes.id), paperId: integer("paper_id").references(() => papers.id), title: text("title").notNull(), date: text("date"), ...timestamps });
export const assessmentResults = sqliteTable("assessment_results", { id: integer("id").primaryKey({ autoIncrement: true }), assessmentId: integer("assessment_id").notNull().references(() => assessments.id), studentId: integer("student_id").notNull().references(() => students.id), score: real("score"), knowledgeMastery: text("knowledge_mastery"), ...timestamps });
export const feedback = sqliteTable("feedback", { id: integer("id").primaryKey({ autoIncrement: true }), lessonId: integer("lesson_id").references(() => lessons.id), studentId: integer("student_id").references(() => students.id), classId: integer("class_id").references(() => classes.id), type: text("type").notNull(), tone: text("tone"), content: text("content").notNull(), status: text("status").notNull().default("draft"), confirmedAt: text("confirmed_at"), ...timestamps });
export const reflections = sqliteTable("reflections", { id: integer("id").primaryKey({ autoIncrement: true }), lessonId: integer("lesson_id").references(() => lessons.id), date: text("date").notNull(), tags: text("tags"), expectedVsActual: text("expected_vs_actual"), effectivePractices: text("effective_practices"), difficulties: text("difficulties"), studentEvidence: text("student_evidence"), nextAction: text("next_action"), reusableMaterial: text("reusable_material"), isStrategy: integer("is_strategy", { mode: "boolean" }).notNull().default(false), isPrivate: integer("is_private", { mode: "boolean" }).notNull().default(true), ...timestamps });
export const resources = sqliteTable("resources", { id: integer("id").primaryKey({ autoIncrement: true }), ownerId: integer("owner_id").references(() => users.id), title: text("title").notNull(), type: text("type"), url: text("url"), tags: text("tags"), ...timestamps });
export const auditLogs = sqliteTable("audit_logs", { id: integer("id").primaryKey({ autoIncrement: true }), userId: integer("user_id").references(() => users.id), action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: text("entity_id"), detail: text("detail"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
