"use client";

/* eslint-disable @next/next/no-html-link-for-pages -- API links intentionally trigger CSV/JSON downloads. */

import { useEffect, useState } from "react";
import { AppShell, EmptyState } from "../components/AppShell";
import { aiBoolean } from "../lib/ai/settings";

const blank = { name: "", email: "", role: "assistant", studentId: "" };
const actionLabels: Record<string, string> = { create: "创建", update: "修改", delete: "删除", archive: "归档", update_status: "更新状态", adjust_mastery: "修正掌握度", import: "导入", export: "导出", link: "关联", unlink: "取消关联", confirm: "确认", promote: "沉淀", assign_role: "分配角色", assign_class_scope: "分配班级", disable: "停用", enable: "启用", delete_all: "清空数据", update_flags: "更新标记", seed_demo: "创建演示数据", clear_demo: "清除演示数据", copy: "复制", change_password: "修改管理员密码", generate: "AI 生成", generate_failed: "AI 生成失败", adopt_ai_draft: "采用 AI 草稿", apply_ai_suggestion: "采用 AI 建议", reject: "忽略 AI 建议" };

export default function SettingsPage() {
  const [data, setData] = useState<any>(null), [form, setForm] = useState(blank), [message, setMessage] = useState(""), [deleteOpen, setDeleteOpen] = useState(false), [confirmation, setConfirmation] = useState(""), [assistantId, setAssistantId] = useState(""), [classIds, setClassIds] = useState<number[]>([]), [demoRuns, setDemoRuns] = useState<any[]>([]), [demoOpen, setDemoOpen] = useState(false), [demoConfirmation, setDemoConfirmation] = useState(""), [passwordForm, setPasswordForm] = useState({ currentPassword: "", newPassword: "", confirmPassword: "" }), [showPasswords, setShowPasswords] = useState(false), [changingPassword, setChangingPassword] = useState(false);
  const [ai, setAi] = useState<any>(null), [aiBusy, setAiBusy] = useState(false), [privacyAcknowledged, setPrivacyAcknowledged] = useState(false);
  const loadAi = async () => { const response = await fetch("/api/settings/ai", { cache: "no-store" }); if (response.ok) setAi(await response.json()); };
  const load = async () => { const [settingsResponse, demoResponse] = await Promise.all([fetch("/api/settings", { cache: "no-store" }), fetch("/api/settings/demo", { cache: "no-store" })]), settings = await settingsResponse.json(), demo = await demoResponse.json(); if (!settingsResponse.ok) { setData(null); return; } setData(settings); if (demoResponse.ok) setDemoRuns(demo.runs || []); };
  useEffect(() => { load(); loadAi(); }, []);
  const saveUser = async () => { const response = await fetch("/api/settings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "upsertUser", ...form }) }), result = await response.json(); if (!response.ok) { setMessage(result.error || "保存失败"); return; } setForm(blank); setMessage("账号与权限已保存"); load(); };
  const disable = async (userId: number) => { if (!confirm("确认停用这个账号？该账号将无法继续进入工作区。")) return; const response = await fetch("/api/settings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "disableUser", userId }) }); const result = await response.json(); setMessage(result.error || "账号已停用"); load(); };
  const exportData = async () => { if (!confirm("确认导出全部教学数据？导出文件包含学生姓名、评价与可能的监护人联系方式，请妥善保管。")) return; const response = await fetch("/api/settings/export"); if (!response.ok) { setMessage("导出失败或当前角色无权限"); return; } const blob = await response.blob(), url = URL.createObjectURL(blob), anchor = document.createElement("a"); anchor.href = url; anchor.download = `知师研室数据备份-${new Date().toISOString().slice(0, 10)}.json`; anchor.click(); URL.revokeObjectURL(url); setMessage("数据已导出，并记录在操作日志中"); load(); };
  const deleteData = async () => { const response = await fetch("/api/settings/data", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ confirmation }) }), result = await response.json(); if (!response.ok) { setMessage(result.error || "未执行删除"); return; } setDeleteOpen(false); setConfirmation(""); setMessage("全部教学数据已删除，账号与操作日志保留"); load(); };
  const chooseAssistant = (id: string) => { setAssistantId(id); setClassIds((data?.staffClassAccess || []).filter((item: any) => String(item.userId) === id).map((item: any) => Number(item.classId))); };
  const toggleClass = (id: number) => setClassIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const saveClassAccess = async () => { if (!assistantId) { setMessage("请先选择助教账号"); return; } const response = await fetch("/api/settings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "setClassAccess", userId: Number(assistantId), classIds }) }), result = await response.json(); setMessage(response.ok ? "助教班级授权已保存" : result.error || "保存授权失败"); if (response.ok) load(); };
  const seedDemo = async () => { if (!confirm("确认创建一套清晰标记的演示数据？它不会替代真实记录，并可在此页一键清除。")) return; const response = await fetch("/api/settings/demo", { method: "POST" }), result = await response.json(); setMessage(response.ok ? `演示数据已创建：${result.summary.classes} 个班级、${result.summary.students} 名学生、${result.summary.questions} 道题目` : result.error || "创建演示数据失败"); if (response.ok) load(); };
  const clearDemo = async () => { const response = await fetch("/api/settings/demo", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ confirmation: demoConfirmation }) }), result = await response.json(); if (!response.ok) { setMessage(result.error || "清除演示数据失败"); return; } setDemoOpen(false); setDemoConfirmation(""); setMessage("演示数据已清除，真实教学数据不受影响"); load(); };
  const changePassword = async () => { if (changingPassword) return; if (passwordForm.newPassword !== passwordForm.confirmPassword) { setMessage("两次输入的新密码不一致"); return; } setChangingPassword(true); const response = await fetch("/api/auth/change-password", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(passwordForm) }), result = await response.json(); setChangingPassword(false); if (!response.ok) { setMessage(result.error || "密码修改失败"); return; } setPasswordForm({ currentPassword: "", newPassword: "", confirmPassword: "" }); setMessage(result.message || "密码已更新"); load(); };
  const saveAi = async (patch: Record<string, unknown>) => { setAiBusy(true); const current = ai?.settings || {}, response = await fetch("/api/settings/ai", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enabled: aiBoolean(current.enabled), includeStudentName: aiBoolean(current.includeStudentName, true), dailyLimit: Number(current.dailyLimit || 50), emergencyDisabled: aiBoolean(current.emergencyDisabled), privacyAcknowledged, ...patch }) }), result = await response.json(); setAiBusy(false); if (!response.ok) { setMessage(result.error || "AI 设置保存失败"); return; } setAi(result); setPrivacyAcknowledged(false); setMessage("DeepSeek 辅助设置已保存"); };
  const clearAiLearning = async () => { if (!confirm("确认清空已匿名化的反馈写作学习样本？此操作不会删除反馈原文。")) return; setAiBusy(true); const response = await fetch("/api/settings/ai", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "clearLearning" }) }), result = await response.json(); setAiBusy(false); if (response.ok) { setAi(result); setMessage("AI 写作学习样本已清空"); } else setMessage(result.error || "清空失败"); };
  const setLearningActive = async (id: number, active: boolean) => { setAiBusy(true); const response = await fetch("/api/settings/ai", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "setLearningActive", id, active }) }), result = await response.json(); setAiBusy(false); if (response.ok) { setAi(result); setMessage(active ? "该学习记录已重新启用" : "该学习记录已停用，后续生成不再引用"); } else setMessage(result.error || "学习记录更新失败"); };

  if (!data) return <AppShell title="设置"><EmptyState title="正在读取安全设置" description="请稍候…" /></AppShell>;
  return <AppShell title="设置" subtitle="角色权限、操作日志、数据导出与删除">
    {message && <div className="saveToast" role="status">{message}</div>}
    <section className="securityBanner"><div><b>当前身份：教师管理员</b><span>管理员账号 {data.current?.accountLabel} · {data.current?.roleName}</span></div><p>公开访客只能浏览已标记为公开的资源；个人教学数据必须登录并通过角色权限检查。</p></section>
    <div className="settingsColumns"><section className="panel"><div className="panelTitle"><div><p>最小权限</p><h2>成员账号与角色</h2></div></div><div className="roleLegend"><p><b>教师</b>全权限、导出与删除</p><p><b>助教</b>仅限获授权班级的课时、学生、作业、题目与反馈；不能导出或查看联系方式</p><p><b>学生</b>仅本人作业、已确认反馈和指定资料</p><p><b>家长</b>仅孩子的已确认反馈、作业和阶段报告</p></div><div className="settingsForm"><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="成员姓名" aria-label="成员姓名" /><input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="成员联系邮箱" aria-label="成员联系邮箱" /><select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value, studentId: "" })} aria-label="角色"><option value="assistant">助教</option><option value="teacher">教师</option><option value="student">学生</option><option value="parent">家长</option></select>{["student", "parent"].includes(form.role) && <select value={form.studentId} onChange={(e) => setForm({ ...form, studentId: e.target.value })} aria-label="关联学生"><option value="">选择关联学生</option>{data.students.map((student: any) => <option value={student.id} key={student.id}>{student.name} · {student.grade}</option>)}</select>}<button className="primaryButton" onClick={saveUser}>保存成员权限</button></div><div className="accountList">{data.users.filter((user: any) => user.email !== "teacher-admin@local.invalid").map((user: any) => <article key={user.id}><div><b>{user.name}</b><span>{user.email}</span></div><em>{user.roleNames || "未分配"}</em><small>{user.status === "active" ? "启用" : "已停用"}</small>{user.id !== data.current.id && user.status === "active" && <button onClick={() => disable(user.id)}>停用</button>}</article>)}</div><div className="assistantScope"><b>助教班级授权</b><p>未分配班级的助教不能读取任何班级、学生或课时数据。</p><select value={assistantId} onChange={(event) => chooseAssistant(event.target.value)}><option value="">选择助教</option>{data.users.filter((user: any) => String(user.roles || "").split(",").includes("assistant") && user.status === "active").map((user: any) => <option key={user.id} value={user.id}>{user.name} · {user.email}</option>)}</select>{assistantId && <div className="scopeChecklist">{data.classes.map((item: any) => <label key={item.id}><input type="checkbox" checked={classIds.includes(Number(item.id))} onChange={() => toggleClass(Number(item.id))} />{item.name} · {item.stage}{item.grade}</label>)}</div>}<button className="secondaryButton" disabled={!assistantId} onClick={saveClassAccess}>保存班级授权</button></div></section>
      <section className="panel"><div className="panelTitle"><div><p>登录安全</p><h2>修改教师管理员密码</h2></div></div><p className="helperText">新密码至少 12 位，并同时包含字母和数字。修改后，其他设备上的旧会话会立即失效。</p><div className="settingsForm"><input type={showPasswords ? "text" : "password"} value={passwordForm.currentPassword} onChange={(event) => setPasswordForm({ ...passwordForm, currentPassword: event.target.value })} placeholder="当前密码" aria-label="当前密码" autoComplete="current-password" /><input type={showPasswords ? "text" : "password"} value={passwordForm.newPassword} onChange={(event) => setPasswordForm({ ...passwordForm, newPassword: event.target.value })} placeholder="新密码" aria-label="新密码" autoComplete="new-password" /><input type={showPasswords ? "text" : "password"} value={passwordForm.confirmPassword} onChange={(event) => setPasswordForm({ ...passwordForm, confirmPassword: event.target.value })} placeholder="再次输入新密码" aria-label="再次输入新密码" autoComplete="new-password" /><label className="checkLabel"><input type="checkbox" checked={showPasswords} onChange={(event) => setShowPasswords(event.target.checked)} />显示密码</label><button className="primaryButton" disabled={changingPassword || !passwordForm.currentPassword || !passwordForm.newPassword || !passwordForm.confirmPassword} onClick={changePassword}>{changingPassword ? "正在修改…" : "修改密码"}</button></div></section>
      <section className="panel aiSettingsPanel">
        <div className="panelTitle"><div><p>教师专属 · 服务端调用</p><h2>DeepSeek 辅助</h2></div><span className={`aiStatus ${ai?.serverConfigured ? "ready" : "off"}`}>{ai?.serverConfigured ? "服务器已配置" : "等待安全配置"}</span></div>
        {!ai ? <p>正在读取 AI 设置…</p> : <>
          <p className="helperText">只生成草稿和审核建议，不自动发布、不改变题目正式状态。密钥只保存在 Sites 生产 Secret，本页不会显示或回传密钥。当前仅教师管理员可使用。</p>
          <div className="aiUsageGrid"><article><b>{Number(ai.usage?.calls || 0)}</b><span>本月调用</span></article><article><b>{Number(ai.usage?.tokens || 0).toLocaleString()}</b><span>本月 Token</span></article><article><b>${Number(ai.usage?.estimatedCostUsd || 0).toFixed(4)}</b><span>费用估算</span></article><article><b>{Number(ai.learning?.activeCount || 0)}</b><span>启用的匿名学习样本</span></article></div>
          <div className="roleLegend"><p><b>快速模型</b>{ai.settings?.fastModel || "deepseek-v4-flash"} · 反馈关闭思考、批量题库开启思考</p><p><b>深度模型</b>{ai.settings?.deepModel || "deepseek-v4-pro"} · 仅教师手动单题复核</p><p><b>今日用量</b>{Number(ai.usageDetail?.today?.calls || 0)} 次 / {Number(ai.settings?.dailyLimit || 50)} 次，{Number(ai.usageDetail?.today?.tokens || 0).toLocaleString()} Token</p></div>
          <div className="settingsForm"><label className="checkLabel"><input type="checkbox" checked={aiBoolean(ai.settings?.enabled)} onChange={(event) => setAi({ ...ai, settings: { ...ai.settings, enabled: event.target.checked } })} />启用 AI 辅助总开关</label><label className="checkLabel"><input type="checkbox" checked={aiBoolean(ai.settings?.includeStudentName, true)} onChange={(event) => setAi({ ...ai, settings: { ...ai.settings, includeStudentName: event.target.checked } })} />反馈草稿可传学生姓名（关闭后替换为“【学生】”）</label><label>每日调用上限<input type="number" min="1" max="200" value={Number(ai.settings?.dailyLimit || 50)} onChange={(event) => setAi({ ...ai, settings: { ...ai.settings, dailyLimit: Number(event.target.value) } })} /></label>{!ai.settings?.privacyAckAt && <label className="checkLabel privacyConfirm"><input type="checkbox" checked={privacyAcknowledged} onChange={(event) => setPrivacyAcknowledged(event.target.checked)} />我已知晓：课堂记录和题目内容会发送给 DeepSeek；每次生成会列出发送字段，联系方式、微信标识、附件与登录数据永不发送，最终内容由教师核对。</label>}<button className="primaryButton" disabled={aiBusy || (!ai.settings?.privacyAckAt && !privacyAcknowledged)} onClick={() => saveAi({})}>{aiBusy ? "保存中…" : "保存 AI 设置"}</button>{aiBoolean(ai.settings?.emergencyDisabled) ? <button disabled={aiBusy} onClick={() => saveAi({ emergencyDisabled: false })}>解除紧急停用（总开关仍需另行确认）</button> : <button className="dangerButton" disabled={aiBusy} onClick={() => saveAi({ enabled: false, emergencyDisabled: true })}>紧急停用</button>}<button disabled={aiBusy || !Number(ai.learning?.count || 0)} onClick={clearAiLearning}>清空全部个性化写作样本</button></div>
          <div className="assistantScope"><b>个性化学习记录</b><p>只在保存反馈时记录脱敏后的版本差异；停用后，后续生成不再引用该条。</p>{ai.learningRecords?.length ? <div className="accountList">{ai.learningRecords.map((item: any) => <article key={item.id}><div><b>{item.stage || "学段不限"} · {item.grade || "年级不限"}</b><span>{item.audience || "对象不限"} · {item.tone || "语气不限"} · {String(item.createdAt || "").slice(0, 10)}</span></div><small>{aiBoolean(item.active) ? "启用" : "已停用"}</small><button disabled={aiBusy} onClick={() => setLearningActive(Number(item.id), !aiBoolean(item.active))}>{aiBoolean(item.active) ? "停用" : "启用"}</button></article>)}</div> : <p className="emptyInline">尚无已保存的个性化学习记录。</p>}</div>
          <div className="assistantScope"><b>最近错误记录</b><p>失败只记录错误码和简短原因，不保存完整请求或密钥。</p>{ai.usageDetail?.recentFailures?.length ? <div className="auditTable">{ai.usageDetail.recentFailures.map((item: any) => <article key={item.id}><time>{String(item.createdAt || "").slice(0, 16)}</time><b>{item.feature === "feedback_draft" ? "反馈草稿" : "题库审核"}</b><span>{item.errorCode || "AI_ERROR"}</span><em>{item.errorMessage || "服务调用失败"}</em></article>)}</div> : <p className="emptyInline">暂无 AI 调用错误。</p>}</div>
        </>}
      </section>
      <section className="panel"><div className="panelTitle"><div><p>数据主权</p><h2>备份与删除</h2></div></div><div className="dataActions"><article><b>导出全部数据</b><p>生成 JSON 备份，包含教学记录及敏感学生数据。</p><button className="secondaryButton" onClick={exportData}>二次确认后导出</button></article><article><b>导出常用表格</b><p>CSV 使用中文兼容编码，可用 WPS 或 Excel 打开。</p><div className="cardActions"><a href="/api/exports/lessons">课时</a><a href="/api/exports/students">学生</a><a href="/api/exports/assessments">成绩</a><a href="/api/exports/assignments">作业</a></div></article><article className="demoZone"><b>创建演示工作区</b><p>{demoRuns.length ? `已有 ${demoRuns.length} 组演示数据，可先清除后再重建。` : "生成带“【演示】”标记的班级、学生、课时、题库、试卷、反馈与反思，用于熟悉完整流程。"}</p><button className="secondaryButton" disabled={Boolean(demoRuns.length)} onClick={seedDemo}>创建演示数据</button>{Boolean(demoRuns.length) && <button onClick={() => setDemoOpen(true)}>清除演示数据</button>}</article><article className="dangerZone"><b>删除全部教学数据</b><p>删除班级、学生、课时、题库、反馈、反思和资源；账号与操作日志保留。</p><button onClick={() => setDeleteOpen(true)}>进入危险操作</button></article></div></section></div>
    <section className="panel auditPanel"><div className="panelTitle"><div><p>谁在何时做了什么</p><h2>操作日志</h2></div></div>{data.logs.length === 0 ? <EmptyState title="还没有操作日志" description="创建、修改、删除、导出与权限变更会记录在这里。" /> : <div className="auditTable">{data.logs.map((log: any) => <article key={log.id}><time>{String(log.createdAt).slice(0, 16)}</time><b>{log.userName || "系统"}</b><span>{actionLabels[log.action] || log.action}</span><em>{log.entityType}{log.entityId ? ` #${log.entityId}` : ""}</em></article>)}</div>}</section>
    {deleteOpen && <div className="modalBackdrop"><div className="lessonModal small dangerDialog" role="dialog" aria-modal="true" aria-labelledby="delete-title"><div className="modalTitle"><div><p>不可恢复</p><h2 id="delete-title">删除全部教学数据</h2></div><button aria-label="关闭" onClick={() => setDeleteOpen(false)}>×</button></div><p>建议先导出备份。请输入“删除全部教学数据”确认：</p><input autoFocus value={confirmation} onChange={(e) => setConfirmation(e.target.value)} /><div className="modalActions"><button onClick={() => setDeleteOpen(false)}>取消</button><button disabled={confirmation !== "删除全部教学数据"} className="dangerButton" onClick={deleteData}>永久删除</button></div></div></div>}
    {demoOpen && <div className="modalBackdrop"><div className="lessonModal small dangerDialog" role="dialog" aria-modal="true" aria-labelledby="demo-title"><div className="modalTitle"><div><p>只清除带演示标记的记录</p><h2 id="demo-title">清除演示数据</h2></div><button aria-label="关闭" onClick={() => setDemoOpen(false)}>×</button></div><p>真实教学记录不会受影响。请输入“清除演示数据”确认：</p><input autoFocus value={demoConfirmation} onChange={(e) => setDemoConfirmation(e.target.value)} /><div className="modalActions"><button onClick={() => setDemoOpen(false)}>取消</button><button disabled={demoConfirmation !== "清除演示数据"} className="dangerButton" onClick={clearDemo}>清除演示数据</button></div></div></div>}
  </AppShell>;
}
