"use client";

import { useEffect, useState } from "react";
import { AppShell, EmptyState } from "../components/AppShell";

const blank = { name: "", email: "", role: "assistant", studentId: "" };
const roleLabels: Record<string, string> = { teacher: "教师", assistant: "助教", student: "学生", parent: "家长" };
const actionLabels: Record<string, string> = { create: "创建", update: "修改", delete: "删除", import: "导入", export: "导出", link: "关联", unlink: "取消关联", confirm: "确认", promote: "沉淀", assign_role: "分配角色", disable: "停用", delete_all: "清空数据", update_flags: "更新标记" };

export default function SettingsPage() {
  const [data, setData] = useState<any>(null), [form, setForm] = useState(blank), [message, setMessage] = useState(""), [deleteOpen, setDeleteOpen] = useState(false), [confirmation, setConfirmation] = useState("");
  const load = () => fetch("/api/settings").then((r) => r.json()).then(setData);
  useEffect(() => { load(); }, []);
  const saveUser = async () => { const response = await fetch("/api/settings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "upsertUser", ...form }) }), result = await response.json(); if (!response.ok) { setMessage(result.error || "保存失败"); return; } setForm(blank); setMessage("账号与权限已保存"); load(); };
  const disable = async (userId: number) => { if (!confirm("确认停用这个账号？该账号将无法继续进入工作区。")) return; const response = await fetch("/api/settings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "disableUser", userId }) }); const result = await response.json(); setMessage(result.error || "账号已停用"); load(); };
  const exportData = async () => { if (!confirm("确认导出全部教学数据？导出文件包含学生姓名、评价与可能的监护人联系方式，请妥善保管。")) return; const response = await fetch("/api/settings/export"); if (!response.ok) { setMessage("导出失败或当前角色无权限"); return; } const blob = await response.blob(), url = URL.createObjectURL(blob), anchor = document.createElement("a"); anchor.href = url; anchor.download = `知师研室数据备份-${new Date().toISOString().slice(0, 10)}.json`; anchor.click(); URL.revokeObjectURL(url); setMessage("数据已导出，并记录在操作日志中"); load(); };
  const deleteData = async () => { const response = await fetch("/api/settings/data", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ confirmation }) }), result = await response.json(); if (!response.ok) { setMessage(result.error || "未执行删除"); return; } setDeleteOpen(false); setConfirmation(""); setMessage("全部教学数据已删除，账号与操作日志保留"); load(); };

  if (!data) return <AppShell title="设置"><EmptyState title="正在读取安全设置" description="请稍候…" /></AppShell>;
  return <AppShell title="设置" subtitle="角色权限、操作日志、数据导出与删除">
    {message && <div className="saveToast" role="status">{message}</div>}
    <section className="securityBanner"><div><b>当前账号：{data.current?.name}</b><span>{data.current?.email} · {data.current?.roleName}</span></div><p>公开访客只能浏览已标记为公开的资源；个人教学数据必须登录并通过角色权限检查。</p></section>
    <div className="settingsColumns"><section className="panel"><div className="panelTitle"><div><p>最小权限</p><h2>账号与角色</h2></div></div><div className="roleLegend"><p><b>教师</b>全权限、导出与删除</p><p><b>助教</b>课时、作业、题目与反馈协作；不能导出或查看联系方式</p><p><b>学生</b>仅本人作业、已确认反馈和指定资料</p><p><b>家长</b>仅孩子的已确认反馈、作业和阶段报告</p></div><div className="settingsForm"><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="姓名" aria-label="姓名" /><input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="ChatGPT 登录邮箱" aria-label="登录邮箱" /><select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value, studentId: "" })} aria-label="角色"><option value="assistant">助教</option><option value="teacher">教师</option><option value="student">学生</option><option value="parent">家长</option></select>{["student", "parent"].includes(form.role) && <select value={form.studentId} onChange={(e) => setForm({ ...form, studentId: e.target.value })} aria-label="关联学生"><option value="">选择关联学生</option>{data.students.map((student: any) => <option value={student.id} key={student.id}>{student.name} · {student.grade}</option>)}</select>}<button className="primaryButton" onClick={saveUser}>保存账号权限</button></div><div className="accountList">{data.users.map((user: any) => <article key={user.id}><div><b>{user.name}</b><span>{user.email}</span></div><em>{user.roleNames || "未分配"}</em><small>{user.status === "active" ? "启用" : "已停用"}</small>{user.id !== data.current.id && user.status === "active" && <button onClick={() => disable(user.id)}>停用</button>}</article>)}</div></section>
      <section className="panel"><div className="panelTitle"><div><p>数据主权</p><h2>备份与删除</h2></div></div><div className="dataActions"><article><b>导出全部数据</b><p>生成 JSON 备份，包含教学记录及敏感学生数据。</p><button className="secondaryButton" onClick={exportData}>二次确认后导出</button></article><article className="dangerZone"><b>删除全部教学数据</b><p>删除班级、学生、课时、题库、反馈、反思和资源；账号与操作日志保留。</p><button onClick={() => setDeleteOpen(true)}>进入危险操作</button></article></div></section></div>
    <section className="panel auditPanel"><div className="panelTitle"><div><p>谁在何时做了什么</p><h2>操作日志</h2></div></div>{data.logs.length === 0 ? <EmptyState title="还没有操作日志" description="创建、修改、删除、导出与权限变更会记录在这里。" /> : <div className="auditTable">{data.logs.map((log: any) => <article key={log.id}><time>{String(log.createdAt).slice(0, 16)}</time><b>{log.userName || "系统"}</b><span>{actionLabels[log.action] || log.action}</span><em>{log.entityType}{log.entityId ? ` #${log.entityId}` : ""}</em></article>)}</div>}</section>
    {deleteOpen && <div className="modalBackdrop"><div className="lessonModal small dangerDialog" role="dialog" aria-modal="true" aria-labelledby="delete-title"><div className="modalTitle"><div><p>不可恢复</p><h2 id="delete-title">删除全部教学数据</h2></div><button aria-label="关闭" onClick={() => setDeleteOpen(false)}>×</button></div><p>建议先导出备份。请输入“删除全部教学数据”确认：</p><input autoFocus value={confirmation} onChange={(e) => setConfirmation(e.target.value)} /><div className="modalActions"><button onClick={() => setDeleteOpen(false)}>取消</button><button disabled={confirmation !== "删除全部教学数据"} className="dangerButton" onClick={deleteData}>永久删除</button></div></div></div>}
  </AppShell>;
}
