"use client";

import Link from "@/app/components/HardNavigationLink";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AppShell, EmptyState } from "../components/AppShell";

type Question = Record<string, any> & { id: number; stem: string; score?: number; questionType: string; difficulty: number; useCount?: number; knowledgePoints?: string };
type Paper = Record<string, any> & { id: number; title: string; type: string; questionCount: number; calculatedScore: number };

export default function PapersPage() {
  const [bank, setBank] = useState<Question[]>([]), [selected, setSelected] = useState<Question[]>([]), [papers, setPapers] = useState<Paper[]>([]), [title, setTitle] = useState(""), [paperType, setPaperType] = useState("练习"), [stage, setStage] = useState("高中"), [grade, setGrade] = useState("高一"), [textbookVersion, setTextbookVersion] = useState(""), [volume, setVolume] = useState(""), [unit, setUnit] = useState(""), [topic, setTopic] = useState(""), [knowledge, setKnowledge] = useState(""), [questionType, setQuestionType] = useState(""), [difficulty, setDifficulty] = useState(""), [count, setCount] = useState(10), [targetScore, setTargetScore] = useState(100), [durationMinutes, setDurationMinutes] = useState(""), [instructions, setInstructions] = useState(""), [excludeRecent, setExcludeRecent] = useState(false), [message, setMessage] = useState(""), [draftId, setDraftId] = useState<number | null>(null), [dirty, setDirty] = useState(false), [saving, setSaving] = useState(false), [paperSearch, setPaperSearch] = useState(""), [paperStatus, setPaperStatus] = useState("");
  const [defaultGroupTitle, setDefaultGroupTitle] = useState(""), [defaultAnswerSpace, setDefaultAnswerSpace] = useState(2);
  const [wholeFile, setWholeFile] = useState<File | null>(null), [wholeTitle, setWholeTitle] = useState(""), [wholeVersion, setWholeVersion] = useState("student"), [uploading, setUploading] = useState(false);
  const [academicYear, setAcademicYear] = useState(""), [examCategory, setExamCategory] = useState(""), [semester, setSemester] = useState(""), [province, setProvince] = useState("天津"), [city, setCity] = useState("天津"), [district, setDistrict] = useState(""), [school, setSchool] = useState(""), [examDate, setExamDate] = useState("");
  const [hydratedDraft, setHydratedDraft] = useState(false);
  const load = useCallback(async () => { try { const query = new URLSearchParams({ status: "active", stage, grade, textbookVersion, volume, unit, topic, knowledge, type: questionType, difficulty }), [questionsResponse, papersResponse] = await Promise.all([fetch(`/api/questions?${query}`), fetch("/api/papers")]), questionsData = await questionsResponse.json(), papersData = await papersResponse.json(); if (!questionsResponse.ok) throw new Error(questionsData.error || "题库读取失败"); if (!papersResponse.ok) throw new Error(papersData.error || "试卷列表读取失败"); setBank(questionsData.questions || []); setPapers(papersData.papers || []); return questionsData.questions || []; } catch (reason) { setMessage(reason instanceof Error ? reason.message : "读取题库失败"); return []; } }, [stage, grade, textbookVersion, volume, unit, topic, knowledge, questionType, difficulty]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { void (async () => { try { const local = JSON.parse(localStorage.getItem("zhishi:paper-workbench") || "null"); if (local) { setSelected(Array.isArray(local.selected) ? local.selected : []); setTitle(String(local.title || "")); setPaperType(String(local.paperType || "练习")); setStage(String(local.stage || "高中")); setGrade(String(local.grade || "高一")); setTextbookVersion(String(local.textbookVersion || "")); setVolume(String(local.volume || "")); setUnit(String(local.unit || "")); setTopic(String(local.topic || "")); setDurationMinutes(String(local.durationMinutes || "")); setInstructions(String(local.instructions || "")); setDraftId(Number(local.draftId || 0) || null); } const cart = JSON.parse(localStorage.getItem("zhishi:paper-cart") || "[]") as number[]; if (cart.length) { const response = await fetch(`/api/questions?status=active&ids=${[...new Set(cart)].slice(0, 100).join(",")}`), data = await response.json(); if (response.ok) setSelected((items) => [...items, ...(data.questions || []).filter((question: Question) => !items.some((item) => item.id === question.id)).map((question: Question) => ({ ...question, groupTitle: "", answerSpace: 2 }))]); } } catch { localStorage.removeItem("zhishi:paper-workbench"); } finally { setHydratedDraft(true); } })(); }, []);
  useEffect(() => { if (!hydratedDraft) return; localStorage.setItem("zhishi:paper-workbench", JSON.stringify({ selected, title, paperType, stage, grade, textbookVersion, volume, unit, topic, durationMinutes, instructions, draftId })); }, [hydratedDraft, selected, title, paperType, stage, grade, textbookVersion, volume, unit, topic, durationMinutes, instructions, draftId]);
  useEffect(() => { if (!draftId) return; localStorage.removeItem("zhishi:paper-cart"); }, [draftId]);
  const total = useMemo(() => selected.reduce((sum, item) => sum + Number(item.score || 0), 0), [selected]);
  const stats = useMemo(() => ({ types: Object.entries(selected.reduce<Record<string, number>>((all, item) => { all[item.questionType || "未分类"] = (all[item.questionType || "未分类"] || 0) + 1; return all; }, {})).map(([type, amount]) => `${type} ${amount}题`).join(" · "), levels: Object.entries(selected.reduce<Record<string, number>>((all, item) => { const level = String(item.difficulty || "—"); all[level] = (all[level] || 0) + 1; return all; }, {})).map(([level, amount]) => `${level}级 ${amount}题`).join(" · ") }), [selected]);
  const add = (item: Question) => { if (!selected.some((current) => current.id === item.id)) setSelected([...selected, { ...item, groupTitle: "", answerSpace: 2 }]); };
  const recommend = async () => { const candidates = (await load()).filter((item: Question) => !excludeRecent || Number(item.useCount || 0) === 0), picked: Question[] = [], pickedTypes = new Set<string>(); let score = 0; for (const item of [...candidates].sort((a, b) => Number(a.useCount || 0) - Number(b.useCount || 0))) { if (picked.length >= count || score >= targetScore) break; if (!pickedTypes.has(item.questionType) || picked.length >= Math.min(3, count)) { picked.push(item); pickedTypes.add(item.questionType); score += Number(item.score || 0); } }
    for (const item of candidates) { if (picked.length >= count || score >= targetScore) break; if (!picked.some((current) => current.id === item.id)) { picked.push(item); score += Number(item.score || 0); } }
    setSelected(picked); setDirty(true); setMessage(picked.length < count || score < targetScore ? `当前条件仅找到 ${picked.length} 题、${score} 分；还差 ${Math.max(0, count - picked.length)} 题、${Math.max(0, targetScore - score)} 分。建议放宽年级、知识点、题型或难度条件。` : `已推荐 ${picked.length} 题，共 ${score} 分；可以继续手动调整题目、顺序和分值`); };
  const move = (index: number, direction: number) => { const next = [...selected], target = index + direction; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; setSelected(next); };
  const save = useCallback(async (silent = false) => { if (!selected.length || saving) return; setSaving(true); const response = await fetch(draftId ? `/api/papers/${draftId}` : "/api/papers", { method: draftId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: title || `${paperType}草稿`, type: paperType, stage, grade, textbookVersion, durationMinutes, instructions, questions: selected.map((item) => ({ id: item.id, score: item.score || 0, groupTitle: item.groupTitle || "", answerSpace: item.answerSpace || 2 })) }) }), payload = await response.json(); setSaving(false); if (!response.ok) { setMessage(payload.error || "保存试卷失败"); return; } if (!draftId) setDraftId(Number(payload.paper?.id)); setDirty(false); if (!silent) setMessage("试卷草稿已保存；之后的题目、顺序和分值调整会自动保存"); void load(); }, [selected, saving, draftId, title, paperType, stage, grade, textbookVersion, durationMinutes, instructions, load]);
  useEffect(() => { if (!draftId || !dirty || !selected.length) return; const timer = window.setTimeout(() => { void save(true); }, 900); return () => window.clearTimeout(timer); }, [draftId, dirty, selected, title, paperType, stage, grade, textbookVersion, durationMinutes, instructions, save]);
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (!dirty) return; event.preventDefault(); event.returnValue = ""; }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [dirty]);
  const mutateSelected = (next: Question[]) => { setSelected(next); setDirty(true); };
  const applyPaperLayout = () => { mutateSelected(selected.map((item) => ({ ...item, groupTitle: defaultGroupTitle || item.groupTitle || "", answerSpace: defaultAnswerSpace }))); setMessage(`已为 ${selected.length} 道题应用大题标题与答题行数`); };
  const filterPapers = async () => { const query = new URLSearchParams({ q: paperSearch, status: paperStatus, academicYear, examCategory, stage, grade, province, city, district, school }), response = await fetch(`/api/papers?${query}`), payload = await response.json(); setPapers(response.ok ? payload.papers || [] : []); if (!response.ok) setMessage(payload.error || "试卷列表读取失败"); };
  const removePaper = async (id: number) => { if (!confirm("确认删除这份试卷草稿？删除后不可恢复。")) return; const response = await fetch(`/api/papers/${id}`, { method: "DELETE" }), payload = await response.json(); setMessage(response.ok ? "试卷草稿已删除" : payload.error || "删除失败"); if (response.ok) load(); };
  const uploadWholePaper = async () => { if (!wholeFile) { setMessage("请先选择完整试卷文件"); return; } setUploading(true); const body = new FormData(); for (const [key, value] of Object.entries({ title: wholeTitle, versionType: wholeVersion, stage, grade, textbookVersion, academicYear, examCategory, semester, province, city, district, school, examDate })) body.set(key, value); body.set("file", wholeFile); const response = await fetch("/api/papers/upload", { method: "POST", body }), payload = await response.json(); setUploading(false); if (!response.ok) { setMessage(payload.error || "整张试卷上传失败"); return; } setWholeFile(null); setWholeTitle(""); setMessage("整张试卷档案与原文件已保存；后台拆题不会覆盖原卷"); void filterPapers(); };
  return <AppShell title="组卷工作台" subtitle="按知识点、题型、难度、题量与总分推荐，再由教师手动确认" actions={<Link href="/questions" className="secondaryButton">返回题库</Link>}>
    {message && <div className="saveToast" role="status">{message}</div>}
    <section className="panel paperArchiveMeta"><div className="panelTitle"><div><p>整卷归档</p><h2>考试属性与地区</h2></div><span>先保存试卷档案，再拆题审核</span></div><div className="formGrid"><label>学年<input value={academicYear} onChange={(event) => setAcademicYear(event.target.value)} placeholder="2025-2026" /></label><label>考试类别<select value={examCategory} onChange={(event) => setExamCategory(event.target.value)}><option value="">待确认</option>{["第一次月考","期中考试","第二次月考","期末考试","真题","一模","二模","三模","中考","高考"].map((item) => <option key={item}>{item}</option>)}</select></label><label>学期<select value={semester} onChange={(event) => setSemester(event.target.value)}><option value="">待确认</option><option>上学期</option><option>下学期</option></select></label><label>考试日期<input type="date" value={examDate} onChange={(event) => setExamDate(event.target.value)} /></label><label>省级地区<input value={province} onChange={(event) => setProvince(event.target.value)} /></label><label>城市<input value={city} onChange={(event) => setCity(event.target.value)} /></label><label>区县<select value={district} onChange={(event) => setDistrict(event.target.value)}><option value="">全部/待确认</option>{(province === "天津" ? ["和平区","河西区","南开区","河东区","河北区","红桥区","滨海新区","东丽区","西青区","津南区","北辰区","武清区","宝坻区","宁河区","静海区","蓟州区"] : []).map((item) => <option key={item}>{item}</option>)}</select></label><label>学校<input value={school} onChange={(event) => setSchool(event.target.value)} /></label></div><button className="secondaryButton" onClick={() => void filterPapers()}>按以上条件筛选试卷库</button></section>
    <section className="panel wholePaperUpload"><div className="panelTitle"><div><p>原卷优先</p><h2>上传整张试卷</h2></div><span>DOCX · PDF · JPG · PNG · WebP</span></div><p className="helperText">上传成功后原文件立即可预览和打印；拆题与后台识别不会覆盖原卷。</p><div className="toolbar"><input value={wholeTitle} onChange={(event) => setWholeTitle(event.target.value)} placeholder="试卷标题（可留空使用文件名）" /><select value={wholeVersion} onChange={(event) => setWholeVersion(event.target.value)}><option value="student">学生版</option><option value="teacher">教师版</option><option value="answer">答案版</option><option value="analysis">解析版</option></select><label className="uploadButton">{wholeFile ? wholeFile.name : "选择完整试卷"}<input type="file" accept=".docx,.pdf,image/jpeg,image/png,image/webp" onChange={(event) => setWholeFile(event.target.files?.[0] || null)} /></label><button className="primaryButton" disabled={uploading} onClick={uploadWholePaper}>{uploading ? "正在安全保存…" : "上传并保存原卷"}</button></div></section>
    <div className="toolbar paperScopeFilters"><input value={textbookVersion} onChange={(event) => setTextbookVersion(event.target.value)} placeholder="教材版本" /><input value={volume} onChange={(event) => setVolume(event.target.value)} placeholder="册别/模块" /><input value={unit} onChange={(event) => setUnit(event.target.value)} placeholder="单元" /><input value={topic} onChange={(event) => setTopic(event.target.value)} placeholder="课/框" /><span>这些范围同时用于候选题和自动推荐。</span></div>
    <div className="paperBuilder"><section className="panel filterPanel"><div className="panelTitle"><div><p>第一步</p><h2>设置组卷条件</h2></div></div><label>学段<select value={stage} onChange={(event) => setStage(event.target.value)}><option>初中</option><option>高中</option></select></label><label>年级<select value={grade} onChange={(event) => setGrade(event.target.value)}>{(stage === "高中" ? ["高一", "高二", "高三"] : ["七年级", "八年级", "九年级"]).map((item) => <option key={item}>{item}</option>)}</select></label><label>知识点<input value={knowledge} onChange={(event) => setKnowledge(event.target.value)} placeholder="如：全过程人民民主" /></label><label>题型<select value={questionType} onChange={(event) => setQuestionType(event.target.value)}><option value="">全部题型</option><option>单选题</option><option>多选题</option><option>材料题</option><option>辨析题</option><option>开放性试题</option></select></label><label>难度<select value={difficulty} onChange={(event) => setDifficulty(event.target.value)}><option value="">混合难度</option>{[1, 2, 3, 4, 5].map((item) => <option key={item} value={String(item)}>{item}级</option>)}</select></label><label>题量上限<input type="number" min="1" max="100" value={count} onChange={(event) => setCount(Number(event.target.value))} /></label><label>目标总分<input type="number" min="1" value={targetScore} onChange={(event) => setTargetScore(Number(event.target.value))} /></label><label className="checkLabel"><input type="checkbox" checked={excludeRecent} onChange={(event) => setExcludeRecent(event.target.checked)} />优先不选近期已用题</label><button className="primaryButton" onClick={recommend}>自动推荐题目</button></section>
      <section className="panel candidatePanel"><div className="panelTitle"><div><p>第二步</p><h2>候选题目</h2></div><b>{bank.length}</b></div>{bank.length === 0 ? <EmptyState title="没有符合条件的题目" description="请放宽筛选条件，或先向正式题库添加题目。" /> : <div className="candidateList">{bank.slice(0, 100).map((item) => <article key={item.id}><div><span>{item.questionType} · 难度{item.difficulty} · 已用{item.useCount || 0}次</span><p>{item.stem}</p></div><button aria-label={`加入题目：${item.stem.slice(0, 20)}`} onClick={() => { add(item); setDirty(true); }}>＋</button></article>)}</div>}</section>
      <section className="panel selectedPanel"><div className="panelTitle"><div><p>第三步</p><h2>试卷草稿</h2></div><b>{selected.length} 题 · {total} 分</b></div>{selected.length === 0 ? <EmptyState title="尚未选题" description="使用自动推荐，或从候选题目中手动添加。" /> : <><div className="paperStats"><span>{stats.types || "题型待分布"}</span><span>{stats.levels || "难度待分布"}</span><span>{draftId ? saving ? "正在自动保存…" : dirty ? "等待自动保存" : "已自动保存" : "首次需手动保存"}</span></div><div className="selectedList">{selected.map((item, index) => <article key={item.id}><b>{index + 1}</b><p>{item.stem}</p><input aria-label={`第 ${index + 1} 题分值`} type="number" value={item.score || 0} onChange={(event) => { const next = [...selected]; next[index] = { ...item, score: Number(event.target.value) }; mutateSelected(next); }} /><button onClick={() => { move(index, -1); setDirty(true); }}>↑</button><button onClick={() => { move(index, 1); setDirty(true); }}>↓</button><button onClick={() => mutateSelected(selected.filter((current) => current.id !== item.id))}>×</button></article>)}</div></>}<div className="paperSave"><input value={title} onChange={(event) => { setTitle(event.target.value); setDirty(true); }} placeholder="试卷名称" /><select value={paperType} onChange={(event) => { setPaperType(event.target.value); setDirty(true); }}><option>练习</option><option>周测</option><option>阶段测</option><option>讲义题组</option></select><input type="number" min="1" value={durationMinutes} onChange={(event) => { setDurationMinutes(event.target.value); setDirty(true); }} placeholder="限时（分钟）" /><textarea value={instructions} onChange={(event) => { setInstructions(event.target.value); setDirty(true); }} placeholder="考试说明（可选）" /><button className="primaryButton" disabled={!selected.length || saving} onClick={() => void save(false)}>{saving ? "正在保存…" : draftId ? "立即保存" : "保存试卷草稿"}</button></div></section></div>
    <section className="panel savedPapers"><div className="panelTitle"><div><p>已保存</p><h2>试卷列表</h2></div></div><div className="toolbar"><input value={paperSearch} onChange={(event) => setPaperSearch(event.target.value)} placeholder="搜索试卷名称" aria-label="搜索试卷名称" /><select value={paperStatus} onChange={(event) => setPaperStatus(event.target.value)} aria-label="试卷状态"><option value="">全部状态</option><option value="draft">草稿</option><option value="completed">已完成</option><option value="used">已使用</option><option value="archived">已归档</option></select><button onClick={filterPapers}>筛选</button></div>{papers.length === 0 ? <EmptyState title="还没有符合条件的试卷" description="可上传整张原卷，或完成选题并保存组卷草稿。" /> : <div className="paperList">{papers.map((paper) => <article key={paper.id}><Link href={`/papers/${paper.id}`}><b>{paper.title}</b><span>{paper.fileCount ? `${paper.fileCount}个原卷版本` : `${paper.questionCount}题 · ${paper.calculatedScore}分`}{paper.duration_minutes ? ` · ${paper.duration_minutes}分钟` : ""}</span></Link><em>{paper.use_status === "assigned" ? "已布置" : { draft: "草稿", completed: "已完成", used: "已使用", archived: "已归档" }[paper.status as string] || paper.status}</em><button onClick={() => removePaper(paper.id)}>删除</button></article>)}</div>}</section>
    {selected.length > 0 && <section className="panel paperLayoutTools"><div className="panelTitle"><div><p>排版设置</p><h2>大题标题与答题空间</h2></div></div><div className="toolbar"><input value={defaultGroupTitle} onChange={(event) => setDefaultGroupTitle(event.target.value)} placeholder="如：一、选择题（可留空）" /><label>答题行数<input type="number" min="1" max="12" value={defaultAnswerSpace} onChange={(event) => setDefaultAnswerSpace(Math.max(1, Math.min(12, Number(event.target.value))))} /></label><button onClick={applyPaperLayout}>应用到当前全部题目</button></div><p className="helperText">Word 与 PDF 导出会保留大题标题和答题空间设置。</p></section>}
  </AppShell>;
}
