"use client";
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
type Message = { role: "user" | "assistant"; content: string; runId?: string; model?: string };
export function AssistantWorkspace() {
  const preset = useSearchParams().get("preset"), started = useRef(false), running = useRef(false);
  const [messages, setMessages] = useState<Message[]>([{ role: "assistant", content: "我可以读取当前工作室的统计证据，帮你分析、检索或起草。涉及课表调整、题库修改、作业发布和反馈发送时，我只会创建待确认项。" }]), [input, setInput] = useState(""), [loading, setLoading] = useState(false), [error, setError] = useState("");
  const runPrompt = useCallback(async (prompt: string, operationId = crypto.randomUUID()) => { if (!prompt || running.current) return; running.current = true; setMessages((current) => [...current, { role: "user", content: prompt }]); setLoading(true); setError(""); try { const response = await fetch("/api/v2/assistant/runs", { method: "POST", headers: { "Content-Type": "application/json", "X-Operation-Id": operationId }, body: JSON.stringify({ prompt, context: { page: "assistant" } }) }), data = await response.json() as { response?: { message?: string; actions?: Array<{ title?: string; summary?: string }> }; model?: string; runId?: string; error?: string }; if (!response.ok) throw new Error(data.error || "智能助手暂时不可用"); const suggestions = data.response?.actions?.length ? `\n\n已创建待确认建议：\n${data.response.actions.map((item) => `• ${item.title || item.summary}`).join("\n")}` : ""; setMessages((current) => [...current, { role: "assistant", content: `${data.response?.message || "分析已完成。"}${suggestions}`, runId: data.runId, model: data.model }]); } catch (reason) { setError(reason instanceof Error ? reason.message : "请求失败"); } finally { running.current = false; setLoading(false); } }, []);
  useEffect(() => { if (preset !== "daily" || started.current) return; started.current = true; const prompt = "按今天、三天内、本周三个层级生成教学驾驶舱，并逐条引用课时、作业、薄弱知识、任务或财务证据；信息不足时明确标注。"; void runPrompt(prompt, `assistant-daily-${new Date().toISOString().slice(0, 10)}`); }, [preset, runPrompt]);
  async function submit(event: FormEvent) { event.preventDefault(); const prompt = input.trim(); if (!prompt || loading) return; setInput(""); await runPrompt(prompt); }
  const prompts = ["按今天、三天内、本周三个层级生成教学驾驶舱，并逐条引用证据", "根据待批作业、测评和薄弱知识，生成分层作业草案与教师核对项", "找出近期薄弱知识与正式题库之间的覆盖缺口，并给出检索或组卷建议", "检查逾期课时、失败任务、待确认和财务异常，按风险排序", "基于真实证据起草家长沟通提纲，信息不足处明确标注"];
  return <><div className="v2-assistant-layout"><section className="v2-card v2-chat"><header className="v2-card-head"><div><h2>工作室智能助手</h2><p>多模型质量路由 · 身份字段默认匿名化 · 正式动作需确认</p></div><span className="v2-status completed">已受控接入</span></header><div className="v2-chat-messages">{messages.map((message, index) => <div key={index} className={`v2-message ${message.role}`}>{message.content}{message.model && <small style={{ display: "block", opacity: .6, marginTop: 7 }}>模型：{message.model} · 运行：{message.runId?.slice(0, 8)}</small>}</div>)}{loading && <div className="v2-message">正在读取证据并选择合适的模型…</div>}</div>{error && <div className="v2-alert v2-error">{error}</div>}<form className="v2-chat-form" onSubmit={submit}><textarea value={input} onChange={(event) => setInput(event.target.value)} placeholder="描述教学目标、问题或希望准备的草稿…"/><button className="v2-primary" disabled={loading}>发送</button></form></section>
    <aside className="v2-card"><header className="v2-card-head"><div><h2>可以直接这样问</h2><p>助手会自动补充真实工作室证据</p></div></header><div className="v2-action-list">{prompts.map((prompt, index) => <button key={prompt} onClick={() => setInput(prompt)} style={{ border: 0, background: "transparent", textAlign: "left" }}><i>{index + 1}</i><span><b>{prompt}</b><small>点击填入输入框</small></span><em>＋</em></button>)}</div><div className="v2-alert" style={{ marginTop: 15 }}>不会自动发送给学生或家长，也不会绕过权限直接修改正式数据。</div></aside></div></>;
}
