"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { AppShell, EmptyState } from "../components/AppShell";

type ClassRow = { id: number; name: string; stage: string; grade: string; courseType?: string; startDate?: string; schedule?: string; notes?: string; status?: string; studentCount?: number; lessonCount?: number; riskCount?: number };
const blank = () => ({ name: "", stage: "高中", grade: "高一", courseType: "小班课", startDate: "", schedule: "", notes: "", status: "active" });

export default function ClassesPage() {
  const [rows, setRows] = useState<ClassRow[]>([]), [filter, setFilter] = useState("active"), [open, setOpen] = useState(false), [editing, setEditing] = useState<number | null>(null), [form, setForm] = useState(blank()), [message, setMessage] = useState("");
  const load = useCallback(async () => { try { const response = await fetch(`/api/classes?status=${filter}`), data = await response.json(); if (!response.ok) throw new Error(data.error || "读取班级失败"); setRows(data.classes || []); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "读取班级失败"); } }, [filter]);
  useEffect(() => { void load(); }, [load]);
  const edit = (row?: ClassRow) => { setEditing(row?.id || null); setForm(row ? { name: row.name, stage: row.stage, grade: row.grade, courseType: row.courseType || "", startDate: row.startDate || "", schedule: row.schedule || "", notes: row.notes || "", status: row.status || "active" } : blank()); setOpen(true); };
  const save = async () => { const response = await fetch(editing ? `/api/classes/${editing}` : "/api/classes", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }), data = await response.json(); if (!response.ok) { setMessage(data.error || "保存班级失败"); return; } setOpen(false); setEditing(null); setMessage(form.status === "archived" ? "班级已归档" : "班级已保存"); load(); };
  const archive = async (row: ClassRow) => { if (!confirm(`确认${row.status === "archived" ? "恢复" : "归档"}“${row.name}”？归档不会删除历史课时和学生记录。`)) return; setEditing(row.id); setForm({ name: row.name, stage: row.stage, grade: row.grade, courseType: row.courseType || "", startDate: row.startDate || "", schedule: row.schedule || "", notes: row.notes || "", status: row.status === "archived" ? "active" : "archived" }); const response = await fetch(`/api/classes/${row.id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: row.name, stage: row.stage, grade: row.grade, courseType: row.courseType || "", startDate: row.startDate || "", schedule: row.schedule || "", notes: row.notes || "", status: row.status === "archived" ? "active" : "archived" }) }), data = await response.json(); setEditing(null); if (!response.ok) { setMessage(data.error || "更新班级失败"); return; } setMessage(row.status === "archived" ? "班级已恢复" : "班级已归档"); load(); };
  return <AppShell title="学生与班级" subtitle="班级课程时间线、学生成长档案与归档管理" actions={<><Link className="secondaryButton" href="/students?new=1">＋ 录入学生</Link><button className="primaryButton" onClick={() => edit()}>＋ 新建班级</button></>}>
    {message && <div className="saveToast" role="status">{message}</div>}
    <div className="subnav"><button className={filter === "active" ? "active" : ""} onClick={() => setFilter("active")}>进行中班级</button><button className={filter === "archived" ? "active" : ""} onClick={() => setFilter("archived")}>已归档</button><Link href="/students">学生档案</Link></div>
    <section className="cardsGrid">{rows.length === 0 ? <EmptyState title={filter === "archived" ? "还没有归档班级" : "还没有班级"} description={filter === "archived" ? "归档的班级会保留完整历史记录，必要时可以恢复。" : "创建班级后，可添加学生、安排课时并查看出勤与作业统计。"} action={filter === "active" ? <button className="secondaryButton" onClick={() => edit()}>创建第一个班级</button> : undefined} /> : rows.map((row) => <article className="classCard" key={row.id}><span>{row.stage} · {row.grade} · {row.status === "archived" ? "已归档" : "进行中"}</span><h3>{row.name}</h3><p>{row.courseType || "未设置课程类型"}</p><small>{row.schedule || "尚未设置固定上课时间"}</small><div><b>{row.studentCount || 0}</b> 名学生　<b>{row.lessonCount || 0}</b> 节课时　<b>{row.riskCount || 0}</b> 需关注</div><p className="classCardActions"><Link href={`/classes/${row.id}`}>查看班级</Link><button onClick={() => edit(row)}>编辑</button><button onClick={() => archive(row)}>{row.status === "archived" ? "恢复" : "归档"}</button></p></article>)}</section>
    {open && <div className="modalBackdrop"><div className="lessonModal small" role="dialog" aria-modal="true" aria-labelledby="class-title"><div className="modalTitle"><div><p>{editing ? "编辑班级" : "新建班级"}</p><h2 id="class-title">{editing ? "调整班级信息" : "建立一个教学班级"}</h2></div><button aria-label="关闭" onClick={() => setOpen(false)}>×</button></div><div className="formGrid"><label className="wide">班级名称<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>学段<select value={form.stage} onChange={(event) => setForm({ ...form, stage: event.target.value })}><option>初中</option><option>高中</option></select></label><label>年级<input value={form.grade} onChange={(event) => setForm({ ...form, grade: event.target.value })} /></label><label>课程类型<input value={form.courseType} onChange={(event) => setForm({ ...form, courseType: event.target.value })} placeholder="如：一对一、小班课" /></label><label>开课日期<input type="date" value={form.startDate} onChange={(event) => setForm({ ...form, startDate: event.target.value })} /></label><label className="wide">固定上课时间<input value={form.schedule} onChange={(event) => setForm({ ...form, schedule: event.target.value })} placeholder="如：每周六 14:00–16:00" /></label><label className="wide">备注<textarea value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></label></div><div className="modalActions"><button onClick={() => setOpen(false)}>取消</button><button className="primaryButton" onClick={save}>保存班级</button></div></div></div>}
  </AppShell>;
}
