import { eq } from "drizzle-orm";
import { getDb } from "../../../../db";
import { reflections, resources } from "../../../../db/schema";
import { audit, isDenied, requirePermission } from "../../../lib/access";

const values = (p: Record<string, unknown>) => ({ lessonId: p.lessonId ? Number(p.lessonId) : null, date: String(p.date), tags: String(p.tags || ""), problemType: String(p.problemType || ""), expectedVsActual: String(p.expectedVsActual || ""), effectivePractices: String(p.effectivePractices || ""), difficulties: String(p.difficulties || ""), studentEvidence: String(p.studentEvidence || ""), nextAction: String(p.nextAction || ""), actionCompleted: Boolean(p.actionCompleted), reusableMaterial: String(p.reusableMaterial || ""), isStrategy: Boolean(p.isStrategy), isPrivate: true, updatedAt: new Date().toISOString() });
export async function PUT(request: Request, context: { params: Promise<{ id: string }> }) { const access = await requirePermission("reflections:write"); if (isDenied(access)) return access; const { id } = await context.params, body = await request.json() as Record<string, unknown>, [row] = await getDb().update(reflections).set(values(body)).where(eq(reflections.id, Number(id))).returning(); await audit(access, "update", "reflection", id); return Response.json({ reflection: row }); }
export async function DELETE(_: Request, context: { params: Promise<{ id: string }> }) { const access = await requirePermission("reflections:write"); if (isDenied(access)) return access; const { id } = await context.params; await getDb().delete(reflections).where(eq(reflections.id, Number(id))); await audit(access, "delete", "reflection", id); return Response.json({ ok: true }); }
export async function POST(_: Request, context: { params: Promise<{ id: string }> }) { const access = await requirePermission("reflections:write"); if (isDenied(access)) return access; const { id } = await context.params, value = Number(id), db = getDb(), [reflection] = await db.select().from(reflections).where(eq(reflections.id, value)).limit(1); if (!reflection) return Response.json({ error: "反思不存在" }, { status: 404 }); const content = [reflection.effectivePractices && `有效做法：${reflection.effectivePractices}`, reflection.nextAction && `改进动作：${reflection.nextAction}`, reflection.reusableMaterial && `可复用素材：${reflection.reusableMaterial}`].filter(Boolean).join("\n\n"), [resource] = await db.insert(resources).values({ title: `教学策略 · ${reflection.date}`, type: "教学策略", tags: reflection.tags, url: "", content, sourceRef: `reflection:${reflection.id}`, visibility: "teacher", ownerId: access.id }).returning(); await db.update(reflections).set({ isStrategy: true, updatedAt: new Date().toISOString() }).where(eq(reflections.id, value)); await audit(access, "promote", "reflection", id, { resourceId: resource.id }); return Response.json({ ok: true, resourceId: resource.id }); }
