import Foundation

// Generated by `npm run release:domain -- your-domain.cn`.
enum ReleaseTarget {
    static let configured = true
    static let rootDomain = "daofazuoye.cn"
    static let webOrigin = "https://daofazuoye.cn"
    static let apiOrigin = "https://daofazuoye.cn"

    static var apiBaseURL: URL? {
        configured ? URL(string: apiOrigin) : nil
    }
}
