"use client";
import { ChangeEvent, useCallback, useEffect, useState } from "react";
import Link from "../../components/HardNavigationLink";

type ImportReport = { total?: number; valid?: number; warning?: number; blocked?: number; create?: number; update?: number; skip?: number; headers?: string[]; unknownColumns?: Array<{ name: string; suggestions?: string[] }>; model?: string | null };
type ImportItem = { id: string; sourceName: string; format: string; state: string; report: ImportReport; createdAt: string };
type Normalized = { date?: string; startTime?: string; endTime?: string; studentNames?: string[]; className?: string; courseName?: string; location?: string; fee?: number };
type Row = { id: number; rowNumber: number; sourceCell?: string; state: string; confidence: number; action: string; normalized: Normalized; issues: unknown[]; lessonId?: number };
type Detail = ImportItem & { rows: Row[]; mapping?: Record<string, string>; job?: { id: string; progress: number; stage: string; state: string; error?: { message?: string } }; undoUntil?: string };

function RowEditor({ row, importId, refresh }: { row: Row; importId: string; refresh: () => void }) {
  const [value, setValue] = useState<Normalized>(row.normalized), [busy, setBusy] = useState(false), [dirty, setDirty] = useState(false), [error, setError] = useState("");
  useEffect(() => { setValue(row.normalized); setDirty(false); setError(""); }, [row.normalized]);
  useEffect(() => { const protect = (event: BeforeUnloadEvent) => { if (!dirty) return; event.preventDefault(); event.returnValue = ""; }; window.addEventListener("beforeunload", protect); return () => window.removeEventListener("beforeunload", protect); }, [dirty]);
  const patch = (key: keyof Normalized, next: unknown) => { setValue((current) => ({ ...current, [key]: next })); setDirty(true); };
  async function save(ignore = false) { if (busy) return; setBusy(true); setError(""); const response = await fetch(`/api/v2/schedule-imports/${importId}/rows/${row.id}`, { method: "PATCH", headers: { "Content-Type": "application/json", "X-Operation-Id": crypto.randomUUID() }, body: JSON.stringify(ignore ? { state: "skipped" } : { normalized: value, confidence: 1 }) }), data = await response.json().catch(() => ({})) as { error?: string }; setBusy(false); if (!response.ok) { setError(data.error || "保存失败"); return; } setDirty(false); refresh(); }
  return <tr className={busy ? "v2-loading" : ""}><td>#{row.rowNumber}<br/><span className={`v2-status ${row.state}`}>{row.state}</span>{dirty && <small>未保存</small>}</td><td><input value={value.date || ""} onChange={(event) => patch("date", event.target.value)} type="date"/></td><td><input value={value.startTime || ""} onChange={(event) => patch("startTime", event.target.value)} placeholder="09:00"/></td><td><input value={value.endTime || ""} onChange={(event) => patch("endTime", event.target.value)} placeholder="10:30"/></td><td><input value={(value.studentNames || []).join("、")} onChange={(event) => patch("studentNames", event.target.value.split(/[、,，]/).filter(Boolean))} placeholder="学生"/></td><td><input value={value.className || ""} onChange={(event) => patch("className", event.target.value)} placeholder="班级"/></td><td><input value={value.courseName || ""} onChange={(event) => patch("courseName", event.target.value)} placeholder="课程"/></td><td><input value={value.location || ""} onChange={(event) => patch("location", event.target.value)} placeholder="地点"/></td><td>{Math.round(row.confidence * 100)}%<br/><small>{row.issues.map(String).join("；")}</small>{error && <small className="v2-form-error">{error}</small>}</td><td><button className="v2-primary" disabled={busy || !dirty} onClick={() => void save(false)}>保存</button> <button className="v2-secondary" disabled={busy} style={{ color: "#17352e", borderColor: "#d3dad4" }} onClick={() => void save(true)}>忽略</button>{row.lessonId && <Link className="v2-row-inline-button" href={`/v2/detail/lessons/${row.lessonId}`}>查看课时</Link>}</td></tr>;
}

export function ScheduleWorkspace() {
  const [imports, setImports] = useState<ImportItem[]>([]), [selected, setSelected] = useState<Detail | null>(null), [file, setFile] = useState<File | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const loadList = useCallback(async () => { const response = await fetch("/api/v2/schedule-imports", { cache: "no-store" }); if (response.ok) setImports(((await response.json()) as { imports: ImportItem[] }).imports || []); }, []);
  const load = useCallback(async (id: string) => { const response = await fetch(`/api/v2/schedule-imports/${id}`, { cache: "no-store" }); const data = await response.json() as Detail & { error?: string }; if (response.ok) setSelected(data); else setError(data.error || "读取失败"); }, []);
  useEffect(() => { loadList(); }, [loadList]);
  useEffect(() => { if (!selected || !["queued", "running"].includes(selected.job?.state || selected.state)) return; const timer = window.setInterval(() => { void load(selected.id); void loadList(); }, 2500); return () => window.clearInterval(timer); }, [load, loadList, selected]);
  async function upload() { if (!file) return; setBusy(true); setError(""); const form = new FormData(); form.append("file", file); const response = await fetch("/api/v2/schedule-imports", { method: "POST", headers: { "X-Operation-Id": crypto.randomUUID() }, body: form }), data = await response.json() as { id?: string; error?: string }; setBusy(false); if (!response.ok || !data.id) return setError(data.error || "上传失败"); setFile(null); await loadList(); await load(data.id); }
  async function action(kind: "confirm" | "undo") { if (!selected) return; if (kind === "confirm" && !window.confirm(`确认后台写入 ${selected.report.valid || 0} 行课表？系统会再次检查冲突，阻塞行不会写入。`)) return; if (kind === "undo" && !window.confirm("确认安全撤销本次导入？已产生后续业务记录的课时会保留并列入阻塞报告。")) return; setBusy(true); setError(""); const operationId = crypto.randomUUID(), response = await fetch(`/api/v2/schedule-imports/${selected.id}/${kind}`, { method: "POST", headers: { "Content-Type": "application/json", "X-Operation-Id": operationId }, body: JSON.stringify({ operationId }) }), data = await response.json() as { error?: string }; setBusy(false); if (!response.ok) return setError(data.error || "操作失败"); await load(selected.id); await loadList(); }
  async function jobAction(kind: "retry" | "cancel") { if (!selected?.job?.id) return; setBusy(true); setError(""); const response = await fetch(`/api/v2/jobs/${selected.job.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: kind }) }), data = await response.json() as { error?: string }; setBusy(false); if (!response.ok) return setError(data.error || "任务操作失败"); await load(selected.id); await loadList(); }
  function choose(event: ChangeEvent<HTMLInputElement>) { setFile(event.target.files?.[0] || null); }
  function downloadErrorReport() { if (!selected) return; const rows = selected.rows.filter((row) => row.state === "blocked" || row.state === "warning" || row.issues.length); const escape = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`; const csv = ["行号,来源位置,状态,日期,开始,结束,学生,班级,课程,地点,问题", ...rows.map((row) => [row.rowNumber, row.sourceCell, row.state, row.normalized.date, row.normalized.startTime, row.normalized.endTime, (row.normalized.studentNames || []).join("、"), row.normalized.className, row.normalized.courseName, row.normalized.location, row.issues.map(String).join("；")].map(escape).join(","))].join("\r\n"); const url = URL.createObjectURL(new Blob([`\uFEFF${csv}`], { type: "text/csv;charset=utf-8" })), anchor = document.createElement("a"); anchor.href = url; anchor.download = `课表导入-${selected.id}-错误报告.csv`; anchor.click(); URL.revokeObjectURL(url); }
  return <><section className="v2-hero"><div><p className="v2-eyebrow">INTELLIGENT SCHEDULE INTAKE</p><h2>先识别、校对和排除冲突，再写入正式课表。</h2><p>XLSX、CSV、WPS 导出的表格、图片和 PDF 均可进入同一校对流程。低置信字段不会被静默写入。</p></div><div className="v2-hero-actions"><label className="v2-primary" htmlFor="schedule-file" role="button" tabIndex={0} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); document.getElementById("schedule-file")?.click(); } }}>＋ 选择课表</label></div></section>
    <div className="v2-grid" style={{ marginTop: 17 }}><aside className="v2-card"><header className="v2-card-head"><div><h2>导入任务</h2><p>识别和写入进度会持续保存</p></div></header><div className="v2-upload"><input id="schedule-file" type="file" accept=".xlsx,.csv,.png,.jpg,.jpeg,.webp,.pdf" onChange={choose}/><label htmlFor="schedule-file" role="button" tabIndex={0} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); document.getElementById("schedule-file")?.click(); } }}><strong>{file?.name || "拖入或选择课表文件"}</strong><span>XLSX / CSV / 图片 / PDF，最大 20MB</span></label>{file && <button className="v2-primary" onClick={upload} disabled={busy}>{busy ? "正在识别…" : "开始智能识别"}</button>}</div><div className="v2-action-list" style={{ marginTop: 10 }}>{imports.map((item) => <button key={item.id} onClick={() => load(item.id)} style={{ border: 0, background: selected?.id === item.id ? "#eef2eb" : "transparent", textAlign: "left", width: "100%" }}><i>{item.report.total || 0}</i><span><b>{item.sourceName}</b><small>{item.format || "识别中"} · 阻塞 {item.report.blocked || 0}</small></span><em className={`v2-status ${item.state}`}>{item.state}</em></button>)}</div></aside>
      <section className="v2-card"><header className="v2-card-head"><div><h2>{selected ? selected.sourceName : "校对摘要"}</h2><p>{selected ? `共 ${selected.report.total || selected.rows.length} 行 · 当前阶段 ${selected.job?.stage || selected.state}` : "选择左侧任务查看识别结果"}</p></div>{selected && <span className={`v2-status ${selected.job?.state || selected.state}`}>{selected.job?.state || selected.state}</span>}</header>{error && <div className="v2-alert v2-error">{error}</div>}{selected ? <><section className="v2-metric-grid" style={{ gridTemplateColumns: "repeat(4,1fr)" }}><article className="v2-metric"><span>总行数</span><b>{selected.report.total || selected.rows.length}</b></article><article className="v2-metric"><span>可写入</span><b>{selected.report.valid || 0}</b></article><article className="v2-metric"><span>需核对</span><b>{selected.report.warning || 0}</b></article><article className="v2-metric"><span>阻塞</span><b>{selected.rows.filter((row) => row.state === "blocked").length}</b></article></section><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><button className="v2-primary" disabled={busy || selected.rows.some((row) => row.state === "blocked") || !["waiting_review", "partial"].includes(selected.state)} onClick={() => action("confirm")}>确认并后台写入</button>{selected.undoUntil && <button className="v2-secondary" style={{ color: "#17352e", borderColor: "#d3dad4" }} disabled={busy} onClick={() => action("undo")}>安全撤销</button>}{["queued", "running"].includes(selected.job?.state || "") && <button className="v2-secondary" style={{ color: "#17352e", borderColor: "#d3dad4" }} disabled={busy} onClick={() => jobAction("cancel")}>取消后台任务</button>}{["failed", "partial", "cancelled"].includes(selected.job?.state || "") && <button className="v2-secondary" style={{ color: "#17352e", borderColor: "#d3dad4" }} disabled={busy} onClick={() => jobAction("retry")}>重试并从原文件续跑</button>}</div>{selected.job?.error?.message && <p className="v2-alert v2-error">{selected.job.error.message}</p>}</> : <div className="v2-empty"><b>尚未选择导入任务</b>上传课表后会显示字段映射、置信度、冲突和重复检查。</div>}</section></div>
    {selected && <section className="v2-card v2-schedule-mapping" style={{ marginTop: 14 }}><header className="v2-card-head"><div><h2>字段识别与错误报告</h2><p>原表字段映射只作识别依据；逐行标准字段可在下方人工修正。</p></div>{selected.rows.some((row) => row.state === "blocked" || row.state === "warning" || row.issues.length > 0) && <button className="v2-secondary-on-light" onClick={downloadErrorReport}>下载错误报告 CSV</button>}</header><div className="v2-evidence-chips">{Object.entries(selected.mapping || {}).map(([field, source]) => <span key={field}><b>{field}</b>{source || "未识别"}</span>)}{!Object.keys(selected.mapping || {}).length && <span><b>视觉识别</b>图片/PDF 由视觉模型直接生成标准字段</span>}</div>{Boolean(selected.report.unknownColumns?.length) && <div className="v2-alert v2-error"><b>未识别列：</b>{selected.report.unknownColumns?.map((column) => `${column.name}${column.suggestions?.length ? `（建议：${column.suggestions.join("、")}）` : ""}`).join("；")}</div>}<small className="v2-form-note">识别来源：{selected.report.model || selected.format || "表格解析器"}。低置信、时间冲突、同名学生和重复课时均保留在逐行问题中。</small></section>}
    {selected && <section className="v2-card" style={{ marginTop: 14 }}><header className="v2-card-head"><div><h2>逐行校对</h2><p>直接修改标准字段；保存后重新执行身份匹配与时间冲突检查</p></div><span>{selected.rows.length} 行</span></header><div className="v2-table"><table><thead><tr><th>行</th><th>日期</th><th>开始</th><th>结束</th><th>学生</th><th>班级</th><th>课程</th><th>地点</th><th>置信度 / 问题</th><th>操作</th></tr></thead><tbody>{selected.rows.map((row) => <RowEditor key={row.id} row={row} importId={selected.id} refresh={() => load(selected.id)}/>)}</tbody></table></div></section>}</>;
}
