"use client";
import { useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { AppShell,EmptyState } from "../components/AppShell";
type Student={id:number;name:string;nickname:string;grade:string;foundationLevel:string;weakKnowledge:string;stageGoal:string;riskTags:string;riskConfirmed:boolean};type ClassRow={id:number;name:string};
const blank={name:"",nickname:"",grade:"高一",classId:"",guardianContact:"",foundationLevel:"",strengths:"",weakKnowledge:"",learningHabits:"",stageGoal:"",riskTags:"",riskConfirmed:"false",notes:""};
export default function StudentsPage(){const [rows,setRows]=useState<Student[]>([]),[classes,setClasses]=useState<ClassRow[]>([]),[open,setOpen]=useState(false),[form,setForm]=useState(blank),[q,setQ]=useState(""),[grade,setGrade]=useState(""),[risk,setRisk]=useState("");const load=async()=>{const [r,c]=await Promise.all([fetch(`/api/students?q=${encodeURIComponent(q)}&grade=${encodeURIComponent(grade)}&risk=${risk}`),fetch("/api/classes")]);setRows((await r.json()).students||[]);setClasses((await c.json()).classes||[])};useEffect(()=>{load();if(new URLSearchParams(location.search).get("new")==="1")setOpen(true)},[]);const visible=useMemo(()=>rows.filter(x=>!q||x.name.includes(q)||x.weakKnowledge?.includes(q)),[rows,q]);const save=async()=>{const r=await fetch("/api/students",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});if(r.ok){setOpen(false);setForm(blank);load()}};return <AppShell title="学生与班级" subtitle="个人隐私字段默认最小化展示" actions={<button className="primaryButton" onClick={()=>setOpen(true)}>＋ 录入学生</button>}>
 <div className="subnav"><Link href="/classes">班级</Link><button className="active">学生档案</button></div><div className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索姓名或薄弱知识点"/><select value={grade} onChange={e=>setGrade(e.target.value)}><option value="">全部年级</option>{["七年级","八年级","九年级","高一","高二","高三"].map(x=><option key={x}>{x}</option>)}</select><select value={risk} onChange={e=>setRisk(e.target.value)}><option value="">全部关注状态</option><option value="confirmed">已确认关注</option></select><button onClick={load}>筛选</button></div>
 <section className="panel tablePanel">{visible.length===0?<EmptyState title="没有符合条件的学生档案" description="调整筛选条件，或录入教学所需的最小信息。监护人联系方式不会出现在普通列表。" action={<button className="secondaryButton" onClick={()=>setOpen(true)}>录入第一名学生</button>}/>:<div className="studentTable">{visible.map(x=><Link className="studentRow" href={`/students/${x.id}`} key={x.id}><span className="avatar">{x.name.slice(0,1)}</span><div><h3>{x.name}{x.nickname&&<small>（{x.nickname}）</small>}</h3><p>{x.grade} · 基础水平：{x.foundationLevel||"待记录"}</p></div><div><span>薄弱知识点</span><b>{x.weakKnowledge||"暂无"}</b></div><div><span>阶段目标</span><b>{x.stageGoal||"待制定"}</b></div>{x.riskConfirmed&&<em className="riskBadge">教师确认关注</em>}</Link>)}</div>}</section>
 {open&&<div className="modalBackdrop"><div className="lessonModal"><div className="modalTitle"><h2>录入学生</h2><button onClick={()=>setOpen(false)}>×</button></div><div className="formGrid"><label>姓名<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>昵称<input value={form.nickname} onChange={e=>setForm({...form,nickname:e.target.value})}/></label><label>所属班级<select value={form.classId} onChange={e=>setForm({...form,classId:e.target.value})}><option value="">暂不分班</option>{classes.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>年级<select value={form.grade} onChange={e=>setForm({...form,grade:e.target.value})}>{["七年级","八年级","九年级","高一","高二","高三"].map(x=><option key={x}>{x}</option>)}</select></label><label>基础水平<input value={form.foundationLevel} onChange={e=>setForm({...form,foundationLevel:e.target.value})}/></label><label>优势<input value={form.strengths} onChange={e=>setForm({...form,strengths:e.target.value})}/></label><label>薄弱知识点<input value={form.weakKnowledge} onChange={e=>setForm({...form,weakKnowledge:e.target.value})}/></label><label>学习习惯<input value={form.learningHabits} onChange={e=>setForm({...form,learningHabits:e.target.value})}/></label><label className="wide">阶段目标<textarea value={form.stageGoal} onChange={e=>setForm({...form,stageGoal:e.target.value})}/></label><label>风险标签<select value={form.riskTags} onChange={e=>setForm({...form,riskTags:e.target.value})}><option value="">无</option><option>缺勤</option><option>作业拖延</option><option>知识漏洞</option><option>情绪/沟通关注</option></select></label><label>教师确认<select value={form.riskConfirmed} onChange={e=>setForm({...form,riskConfirmed:e.target.value})}><option value="false">不标记</option><option value="true">确认需关注</option></select></label><label className="wide">监护人联系方式（可选，受限查看）<input value={form.guardianContact} onChange={e=>setForm({...form,guardianContact:e.target.value})}/></label><label className="wide">备注<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><div className="privacyNote">风险标签必须由教师手动确认；系统不会自动作出评价性结论。监护人联系方式不在普通列表展示。</div><div className="modalActions"><button onClick={()=>setOpen(false)}>取消</button><button className="primaryButton" onClick={save}>保存学生</button></div></div></div>}
 </AppShell>}
