"use client";

import Link from "../../../../components/HardNavigationLink";
import { FormEvent, useCallback, useEffect, useState } from "react";

type Kind = "students" | "classes" | "lessons" | "papers" | "resources";
type Row = Record<string, unknown>;
const names: Record<Kind, string> = { students: "学生档案", classes: "班级详情", lessons: "课时详情", papers: "试卷详情", resources: "资源详情" };
const back: Record<Kind, string> = { students: "/v2/modules/students", classes: "/v2/modules/students", lessons: "/v2/modules/students", papers: "/v2/modules/papers", resources: "/v2/modules/resources" };
const text = (input: unknown, fallback = "—") => String(input ?? "").trim() || fallback;
const number = (input: unknown) => Number(input || 0);

async function json(path: string, init?: RequestInit) {
  const response = await fetch(path, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers || {}) } });
  const payload = await response.json().catch(() => ({})) as Row;
  if (!response.ok) throw new Error(text(payload.error, `请求失败（${response.status}）`));
  return payload;
}

export function EntityDetail({ kind, id }: { kind: Kind; id: number }) {
  const [data, setData] = useState<Row>({}), [students, setStudents] = useState<Row[]>([]), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const result = await json(`/api/v2/${kind}/${id}`); setData(result); if (kind === "classes") { const list = await json("/api/v2/students?status=active"); setStudents((list.students || []) as Row[]); } } catch (caught) { setError(caught instanceof Error ? caught.message : "详情暂时无法读取"); } finally { setLoading(false); } }, [id, kind]);
  useEffect(() => { void load(); }, [load]);

  const update = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setError(""); setNotice(""); const fields = Object.fromEntries(new FormData(event.currentTarget).entries()) as Record<string, string>; try { const payload: Row = { ...fields }; if (kind === "lessons") payload.classId = fields.classId ? Number(fields.classId) : null; if (kind === "students") payload.riskConfirmed = fields.riskConfirmed === "on"; await json(`/api/v2/${kind}/${id}`, { method: "PUT", body: JSON.stringify(payload) }); setNotice("详情已更新并写入审计记录。"); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "保存失败"); } finally { setSaving(false); } };
  const memberAction = async (studentId: number, method: "POST" | "DELETE") => { setSaving(true); setError(""); try { await json(`/api/v2/classes/${id}`, { method, body: JSON.stringify({ studentId }) }); setNotice(method === "POST" ? "学生已加入班级。" : "学生已从班级移除，历史教学证据仍保留。"); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "班级成员更新失败"); } finally { setSaving(false); } };
  const title = text(((data.student || data.class || data.lesson || data.paper || data.resource || {}) as Row).name || ((data.student || data.class || data.lesson || data.paper || data.resource || {}) as Row).title || ((data.student || data.class || data.lesson || data.paper || data.resource || {}) as Row).courseName, names[kind]);
  return <><section className="v2-detail-head"><div><Link href={back[kind]}>← 返回{nameof(kind)}</Link><p className="v2-eyebrow">V2 NATIVE DETAIL · #{id}</p><h2>{title}</h2><span>{names[kind]}与列表使用同一版本化业务数据</span></div><Link className="v2-secondary-on-light" href="/v2/assistant">✦ 让 AI 分析当前证据</Link></section>{error && <p className="v2-alert v2-error">{error}</p>}{notice && <p className="v2-alert">{notice}</p>}<div className={loading ? "v2-loading" : ""}>{kind === "students" && <StudentDetail data={data} update={update} saving={saving}/>} {kind === "classes" && <ClassDetail data={data} candidates={students} update={update} memberAction={memberAction} saving={saving}/>} {kind === "lessons" && <LessonDetail data={data} update={update} saving={saving}/>} {kind === "papers" && <PaperDetail data={data} id={id}/>} {kind === "resources" && <ResourceDetail data={data} update={update} saving={saving}/>}</div></>;
}

function nameof(kind: Kind) { return kind === "papers" ? "组卷工作台" : kind === "resources" ? "资源中心" : "学生、班级与课时"; }

function StudentDetail({ data, update, saving }: { data: Row; update: (event: FormEvent<HTMLFormElement>) => void; saving: boolean }) {
  const student = (data.student || {}) as Row, attention = (data.attention || []) as Row[], lessons = (data.lessonRecords || []) as Row[], submissions = (data.submissions || []) as Row[], results = (data.results || []) as Row[], wrong = (data.wrongQuestions || []) as Row[], evidence = (data.knowledgeEvidence || []) as Row[];
  return <><Metric items={[["课时记录", lessons.length], ["作业记录", submissions.length], ["测评记录", results.length], ["活跃错题", wrong.filter((row) => text(row.status) === "active").length]]}/><div className="v2-detail-grid"><section className="v2-card"><Header title="需要关注" detail="每条提醒都来自当前真实业务记录"/><div className="v2-native-list">{attention.map((row, index) => <article key={index}><div className="v2-avatar">!</div><div><h3>{text(row.title)}</h3><p>{text(row.evidence)}</p></div><em className={`v2-status ${text(row.level) === "high" ? "warning" : "completed"}`}>{text(row.level) === "high" ? "优先" : "常规"}</em></article>)}{!attention.length && <Empty title="没有紧急提醒"/>}</div></section><section className="v2-card"><Header title="知识与错题证据" detail="不把单次结果推断为长期结论"/><div className="v2-evidence-chips">{evidence.slice(0, 12).map((row, index) => <span key={index}><b>{text(row.knowledgeName)}</b>{text(row.level)} · {text(row.sourceType)}</span>)}</div><div className="v2-native-list compact">{wrong.slice(0, 8).map((row) => <article key={String(row.id)}><div className="v2-avatar">错</div><div><h3>{text(row.knowledgePoints, "未标知识点")}</h3><p>{text(row.stem).slice(0, 110)}</p><span>{text(row.reason, "待归因")}</span></div><em className="v2-status warning">{text(row.status)}</em></article>)}</div></section><section className="v2-card v2-detail-wide"><Header title="编辑学生档案" detail="联系方式等私密字段不在该普通详情接口中返回"/><form className="v2-form v2-edit-grid" onSubmit={update}><label>姓名<input name="name" defaultValue={text(student.name, "")} required/></label><label>昵称<input name="nickname" defaultValue={text(student.nickname, "")}/></label><label>年级<input name="grade" defaultValue={text(student.grade, "")} required/></label><label>学校<input name="school" defaultValue={text(student.school, "")}/></label><label>教材版本<input name="textbookVersion" defaultValue={text(student.textbookVersion, "")}/></label><label>考试目标<input name="examGoal" defaultValue={text(student.examGoal, "")}/></label><label>优势<textarea name="strengths" defaultValue={text(student.strengths, "")} rows={3}/></label><label>薄弱知识<textarea name="weakKnowledge" defaultValue={text(student.weakKnowledge, "")} rows={3}/></label><label>学习习惯<textarea name="learningHabits" defaultValue={text(student.learningHabits, "")} rows={3}/></label><label>阶段目标<textarea name="stageGoal" defaultValue={text(student.stageGoal, "")} rows={3}/></label><label>风险标签<input name="riskTags" defaultValue={text(student.riskTags, "")}/></label><label className="v2-check"><input name="riskConfirmed" type="checkbox" defaultChecked={Boolean(student.riskConfirmed)}/>教师已确认风险</label><input type="hidden" name="status" value={text(student.status, "active")}/><button className="v2-primary" disabled={saving}>{saving ? "保存中…" : "保存档案"}</button></form></section></div></>;
}

function ClassDetail({ data, candidates, update, memberAction, saving }: { data: Row; candidates: Row[]; update: (event: FormEvent<HTMLFormElement>) => void; memberAction: (studentId: number, method: "POST" | "DELETE") => void; saving: boolean }) {
  const item = (data.class || {}) as Row, members = (data.members || []) as Row[], lessons = (data.lessons || []) as Row[], assessments = (data.assessments || []) as Row[], weak = (data.weakKnowledge || []) as Row[], memberIds = new Set(members.map((row) => number(row.id)));
  return <><Metric items={[["班级成员", members.length], ["课时", lessons.length], ["出勤率", data.attendanceRate == null ? "—" : `${data.attendanceRate}%`], ["作业完成率", data.homeworkRate == null ? "—" : `${data.homeworkRate}%`]]}/><div className="v2-detail-grid"><section className="v2-card"><Header title="成员与风险" detail="移出班级不会删除学生历史记录"/><div className="v2-native-list">{members.map((row) => <article key={String(row.id)}><div className="v2-avatar">{text(row.name).slice(0, 1)}</div><div><h3>{text(row.name)} <small>{text(row.grade)}</small></h3><p>{text(row.weakKnowledge, "暂无薄弱点记录")}</p><button className="v2-row-inline-button" disabled={saving} onClick={() => void memberAction(number(row.id), "DELETE")}>移出当前班级</button></div><em className={`v2-status ${row.riskConfirmed ? "warning" : "completed"}`}>{row.riskConfirmed ? "需关注" : "正常"}</em></article>)}</div><form className="v2-form v2-add-member" onSubmit={(event) => { event.preventDefault(); const id = Number(new FormData(event.currentTarget).get("studentId")); if (id) void memberAction(id, "POST"); }}><label>添加学生<select name="studentId" required><option value="">请选择</option>{candidates.filter((row) => !memberIds.has(number(row.id))).map((row) => <option key={String(row.id)} value={String(row.id)}>{text(row.name)} · {text(row.grade)}</option>)}</select></label><button className="v2-primary" disabled={saving}>加入班级</button></form></section><section className="v2-card"><Header title="班级教学证据" detail="薄弱点人数按不同学生去重"/><div className="v2-evidence-chips">{weak.map((row, index) => <span key={index}><b>{text(row.name)}</b>{number(row.count)} 人</span>)}</div><div className="v2-native-list compact">{assessments.map((row) => <article key={String(row.id)}><div className="v2-avatar">测</div><div><h3>{text(row.title)}</h3><p>{text(row.date)} · {number(row.resultCount)} 份成绩</p><span>平均 {text(row.averageScore, "暂无")}/{text(row.totalScore)}</span></div></article>)}</div></section><section className="v2-card v2-detail-wide"><Header title="编辑班级" detail="班级归档属于敏感动作，本页不提供快捷删除"/><form className="v2-form v2-edit-grid" onSubmit={update}><label>名称<input name="name" defaultValue={text(item.name, "")} required/></label><label>学段<input name="stage" defaultValue={text(item.stage, "")} required/></label><label>年级<input name="grade" defaultValue={text(item.grade, "")} required/></label><label>课程类型<input name="courseType" defaultValue={text(item.courseType, "")}/></label><label>开始日期<input name="startDate" type="date" defaultValue={text(item.startDate, "")}/></label><label>常规安排<input name="schedule" defaultValue={text(item.schedule, "")}/></label><label>备注<textarea name="notes" defaultValue={text(item.notes, "")} rows={3}/></label><input type="hidden" name="status" value={text(item.status, "active")}/><button className="v2-primary" disabled={saving}>{saving ? "保存中…" : "保存班级"}</button></form></section></div></>;
}

function LessonDetail({ data, update, saving }: { data: Row; update: (event: FormEvent<HTMLFormElement>) => void; saving: boolean }) {
  const item = (data.lesson || {}) as Row;
  return <><Metric items={[["日期", text(item.date)], ["时间", `${text(item.startTime, "待定")}–${text(item.endTime, "待定")}`], ["班级", text(item.className, text(item.studentNames, "未关联"))], ["状态", text(item.status)]]}/><section className="v2-card"><Header title="课时、备课与课后记录" detail="调课建议可以由 AI 起草，但正式时间调整进入待确认中心"/><form className="v2-form v2-edit-grid" onSubmit={update}><label>日期<input name="date" type="date" defaultValue={text(item.date, "")} required/></label><label>开始<input name="startTime" type="time" defaultValue={text(item.startTime, "")}/></label><label>结束<input name="endTime" type="time" defaultValue={text(item.endTime, "")}/></label><label>课程名称<input name="courseName" defaultValue={text(item.courseName, "")} required/></label><label>学段<input name="stage" defaultValue={text(item.stage, "")} required/></label><label>年级<input name="grade" defaultValue={text(item.grade, "")} required/></label><label>地点<input name="location" defaultValue={text(item.location, "")}/></label><label>上课方式<select name="mode" defaultValue={text(item.mode, "offline")}><option value="offline">线下</option><option value="online">线上</option></select></label><label>课题<input name="topic" defaultValue={text(item.topic, "")}/></label><label>知识点<input name="knowledgePoints" defaultValue={text(item.knowledgePoints, "")}/></label><label>教学目标<textarea name="teachingGoals" defaultValue={text(item.teachingGoals, "")} rows={4}/></label><label>重点<textarea name="keyPoints" defaultValue={text(item.keyPoints, "")} rows={3}/></label><label>难点<textarea name="difficultPoints" defaultValue={text(item.difficultPoints, "")} rows={3}/></label><label>实际内容<textarea name="actualContent" defaultValue={text(item.actualContent, "")} rows={4}/></label><label>课堂活动<textarea name="activities" defaultValue={text(item.activities, "")} rows={3}/></label><label>作业<textarea name="homework" defaultValue={text(item.homework, "")} rows={3}/></label><label>下次计划<textarea name="nextPlan" defaultValue={text(item.nextPlan, "")} rows={3}/></label><input type="hidden" name="classId" value={text(item.classId, "")}/><input type="hidden" name="status" value={text(item.status, "draft")}/><button className="v2-primary" disabled={saving}>{saving ? "保存中…" : "保存课时"}</button></form></section></>;
}

function PaperDetail({ data, id }: { data: Row; id: number }) {
  const paper = (data.paper || {}) as Row, questions = (data.questions || []) as Row[], stats = (data.stats || {}) as Row, types = (stats.questionTypes || {}) as Row, difficulties = (stats.difficulties || {}) as Row;
  return <><Metric items={[["题目", questions.length], ["总分", text(paper.total_score, text(paper.totalScore, "0"))], ["题型", Object.keys(types).length], ["知识点", Array.isArray(stats.knowledge) ? stats.knowledge.length : 0]]}/><section className="v2-card v2-paper-export"><Header title="导出与打印" detail="Word 在服务器生成并写入导出任务记录；打印可在系统对话框中另存为 PDF"/><div className="v2-detail-actions">{[["student", "学生版 Word"], ["teacher", "教师版 Word"], ["answer", "答案版 Word"], ["analysis", "解析版 Word"]].map(([mode, label]) => <a className="v2-secondary-on-light" href={`/api/v2/papers/${id}/export?mode=${mode}`} key={mode}>{label}</a>)}<button className="v2-primary" onClick={() => window.print()}>打印 / 存为 PDF</button></div><small className="v2-form-note">导出文件始终通过登录态鉴权；不会生成公开直链。</small></section><div className="v2-detail-grid"><section className="v2-card v2-detail-wide"><Header title="试卷题目" detail="按当前试卷顺序与分值展示"/><div className="v2-search-results">{questions.map((row) => <article className="v2-question" key={String(row.id)}><header><span>第 {text(row.position)} 题</span><span>{text(row.question_type, text(row.questionType))}</span><span>难度 {text(row.difficulty)}</span><em>{text(row.paperScore, "0")} 分</em></header><h3>{text(row.stem)}</h3><div className="v2-reasons"><span>{text(row.knowledge_points, text(row.knowledgePoints, "知识点待完善"))}</span></div></article>)}</div></section><section className="v2-card"><Header title="题型结构" detail="用于检查比例"/><div className="v2-evidence-chips">{Object.entries(types).map(([key, item]) => <span key={key}><b>{key}</b>{number(item)} 题</span>)}</div></section><section className="v2-card"><Header title="难度梯度" detail="1–5 级分布"/><div className="v2-evidence-chips">{Object.entries(difficulties).map(([key, item]) => <span key={key}><b>难度 {key}</b>{number(item)} 题</span>)}</div></section></div></>;
}

function ResourceDetail({ data, update, saving }: { data: Row; update: (event: FormEvent<HTMLFormElement>) => void; saving: boolean }) {
  const item = (data.resource || {}) as Row;
  return <><Metric items={[["可见范围", text(item.visibility, "private") === "public" ? "公开" : "私有"], ["类型", text(item.type, "素材")], ["来源", text(item.sourceRef, "手工录入")], ["最后更新", text(item.updatedAt)]]}/><section className="v2-card"><Header title="编辑资源内容" detail="本页不改变公开范围；外部链接只允许 HTTP/HTTPS，私有附件仍走鉴权接口"/><form className="v2-form v2-edit-grid" onSubmit={update}><label>资源名称<input name="title" defaultValue={text(item.title, "")} required/></label><label>类型<select name="type" defaultValue={text(item.type, "备课素材")}><option>备课素材</option><option>教学策略</option><option>课件</option><option>外部链接</option><option>AI 学情报告</option></select></label><label>外部链接<input name="url" type="url" defaultValue={text(item.url, "")} placeholder="https://"/></label><label>标签<input name="tags" defaultValue={text(item.tags, "")} placeholder="高二, 论述题"/></label><label className="v2-detail-wide">正文与摘要<textarea name="content" defaultValue={text(item.content, "")} rows={14}/></label><button className="v2-primary" disabled={saving}>{saving ? "保存中…" : "保存资源"}</button></form>{Boolean(item.url) && <div className="v2-detail-actions"><a className="v2-secondary-on-light" href={text(item.url, "#")} target="_blank" rel="noreferrer">打开外部链接</a></div>}</section></>;
}

function Metric({ items }: { items: Array<[string, string | number]> }) { return <section className="v2-metric-grid v2-four-metrics">{items.map(([label, value]) => <article className="v2-metric" key={label}><span>{label}</span><b>{value}</b><small>来自当前业务记录</small></article>)}</section>; }
function Header({ title, detail }: { title: string; detail: string }) { return <header className="v2-card-head"><div><h2>{title}</h2><p>{detail}</p></div></header>; }
function Empty({ title }: { title: string }) { return <div className="v2-empty"><b>{title}</b>当前没有可显示的业务证据。</div>; }
