import { eq } from "drizzle-orm";
import { getDb } from "../../../../db";
import { feedback } from "../../../../db/schema";
import { audit, isDenied, requireClassAccess, requireFeedbackAccess, requireLessonAccess, requirePermission } from "../../../lib/access";

const idFrom = async (context: { params: Promise<{ id: string }> }) => Number((await context.params).id);
const values = (payload: Record<string, unknown>) => ({ lessonId: payload.lessonId ? Number(payload.lessonId) : null, studentId: payload.studentId ? Number(payload.studentId) : null, classId: payload.classId ? Number(payload.classId) : null, type: String(payload.type || "lesson"), tone: String(payload.tone || "专业简洁"), content: String(payload.content || ""), learningContent: String(payload.learningContent || ""), highlights: String(payload.highlights || ""), consolidate: String(payload.consolidate || ""), homeworkRequirements: String(payload.homeworkRequirements || ""), parentAdvice: String(payload.parentAdvice || ""), nextFocus: String(payload.nextFocus || ""), periodStart: String(payload.periodStart || ""), periodEnd: String(payload.periodEnd || ""), periodSummary: String(payload.periodSummary || ""), progress: String(payload.progress || ""), problems: String(payload.problems || ""), goals: String(payload.goals || ""), suggestions: String(payload.suggestions || ""), status: String(payload.status || "draft"), confirmedAt: payload.status === "confirmed" ? new Date().toISOString() : null, updatedAt: new Date().toISOString() });
export async function PUT(request: Request, context: { params: Promise<{ id: string }> }) { const access = await requirePermission("feedback:write"); if (isDenied(access)) return access; const id = await idFrom(context), denied = await requireFeedbackAccess(access, id); if (denied) return denied; const body = await request.json() as Record<string, unknown>, data = values(body); if (!data.content.trim()) return Response.json({ error: "反馈内容不能为空" }, { status: 400 }); if (access.role === "assistant") { if (data.lessonId) { const lessonDenied = await requireLessonAccess(access, data.lessonId); if (lessonDenied) return lessonDenied; } else if (data.classId) { const classDenied = await requireClassAccess(access, data.classId); if (classDenied) return classDenied; } } const [row] = await getDb().update(feedback).set(data).where(eq(feedback.id, id)).returning(); await audit(access, "update", "feedback", id, { status: row?.status }); return row ? Response.json({ feedback: row }) : Response.json({ error: "反馈不存在" }, { status: 404 }); }
export async function DELETE(_: Request, context: { params: Promise<{ id: string }> }) { const access = await requirePermission("feedback:write"); if (isDenied(access)) return access; const id = await idFrom(context), denied = await requireFeedbackAccess(access, id); if (denied) return denied; const [row] = await getDb().delete(feedback).where(eq(feedback.id, id)).returning(); await audit(access, "delete", "feedback", id); return row ? Response.json({ ok: true }) : Response.json({ error: "反馈不存在" }, { status: 404 }); }
