"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { AppShell } from "../components/AppShell";

type Item = Record<string, any> & { id: number; studentId: number; name: string; fromGrade: string; toGrade: string; status: string };
const targetYear = () => { const now = new Date(), start = now.getMonth() >= 8 ? now.getFullYear() : now.getFullYear() - 1; return `${start}-${start + 1}`; };
export default function AcademicYearsPage() {
  const [year, setYear] = useState(targetYear()), [run, setRun] = useState<Record<string, any> | null>(null), [items, setItems] = useState<Item[]>([]), [excluded, setExcluded] = useState<number[]>([]), [message, setMessage] = useState("");
  const loadedQuery = useRef(false);
  const preview = useCallback(async (selectedYear = year) => { const response = await fetch(`/api/academic-years/${encodeURIComponent(selectedYear)}/promotion`), data = await response.json(); if (!response.ok) { setMessage(data.error || "读取失败"); return; } setRun(data.run); setItems(data.items || []); setExcluded((data.items || []).filter((item: Item) => item.status === "excluded").map((item: Item) => Number(item.studentId))); setMessage(data.reminder); }, [year]);
  useEffect(() => { if (loadedQuery.current) return; loadedQuery.current = true; const requested = new URLSearchParams(window.location.search).get("year"); if (requested && /^20\d{2}-20\d{2}$/.test(requested)) { setYear(requested); void preview(requested); } }, [preview]);
  const confirmPromotion = async () => { if (!confirm(`确认按清单更新年级？已排除 ${excluded.length} 名学生。`)) return; const response = await fetch(`/api/academic-years/${encodeURIComponent(year)}/promotion`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ excludedStudentIds: excluded }) }), data = await response.json(); setMessage(response.ok ? `晋升完成：${data.confirmed ?? 0}人，排除${data.excluded ?? excluded.length}人。重复执行不会重复晋升。` : data.error || "确认失败"); if (response.ok) void preview(); };
  return <AppShell title="学年晋升" subtitle="9月只生成建议；教师排除特殊学生并确认后才更新"><div className="toolbar"><label>目标学年<input value={year} onChange={(event) => setYear(event.target.value)} /></label><button className="primaryButton" onClick={() => void preview()}>生成/查看晋升建议</button></div>{message && <div className="saveToast" role="status">{message}</div>}{run && <section className="panel"><div className="sectionTitle"><div><p>状态：{run.status === "confirmed" ? "已确认" : "待确认"}</p><h2>{year}学年晋升清单</h2></div>{run.status !== "confirmed" && <button className="primaryButton" onClick={() => void confirmPromotion()}>确认未排除学生</button>}</div><div className="tableWrap"><table><thead><tr><th>排除</th><th>学生</th><th>学校</th><th>当前</th><th>建议</th><th>状态</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><input type="checkbox" disabled={run.status === "confirmed"} checked={excluded.includes(Number(item.studentId))} onChange={() => setExcluded((values) => values.includes(Number(item.studentId)) ? values.filter((id) => id !== Number(item.studentId)) : [...values, Number(item.studentId)])} /></td><td>{item.name}</td><td>{item.school || "—"}</td><td>{item.fromGrade}</td><td>{item.toGrade}</td><td>{item.status === "excluded" ? "已排除" : item.status === "confirmed" ? "已更新" : "待确认"}</td></tr>)}</tbody></table></div></section>}</AppShell>;
}
